### PR TITLE
Add a version parsing and comparison API to librpmio

### LINKED ISSUE #561: Add an API + bindings for parsing EVR
Originally came up as PR #533, there should be rpm-provided API(s) and bindings for parsing (N)EVR into its components rather than forcing implementations to roll their own. Kinda obvious...

### PR DESCRIPTION
**Pull request by pmatilai**
This adds a (beginnings of) a version parsing and comparison API to librpmio.

Details in the commit messages, but the (obvious) motivation is to finally have a meaningful API for handling rpm versions in and out of rpm. For maximum coverage, this needs to be in librpmio which allows usage from Lua, macro engine and expression parser. 

--nopromote support is ripped out to the extent possible without requiring soname bump to avoid dragging that ancient remnant into the new API.

Fixes #561 and #897 and paves the way for #1217.

### CODE REVIEW

**Comment by pmatilai** [comment]
Rebase to clear fixups.

**Comment by ffesti** [comment]
Removing the nopromote API in Python but keeping it in C seems inconsistent. Not sure if I really care.

**Comment by ffesti** [comment]
Overall this looks good. I am wondering what all the malloc and free costs us as we might do a few version comparisons during a transaction. Probably not enough to actually worry. Converting the EVR of the rpmds object just for comparison seems kinda weird. I am fine with this as a first step but we should consider moving the rpmds to use versions from the start. Which asks the question how this relates to rpmsid...
That's not something we want to get into right now but we might want to think about in the 4.17 time frame. For now it is great we have something like this at all.

**Comment by pmatilai** [comment]
This doesn't actually add any mallocs that were not there before for the busy case of rpmds comparisons: previously the strings were strdup()'ed in rpmdsCompareEVR() before passing to parseEVR(), now this is happens in rpmevr.c instead. The ver handle is all alloced as a single blob so there's no added cost (except for some error checking).

As for rpmds and string pool, all good questions that occurred to me too, but I don't have immediate answers. It'd seem attractive to run the rpmds versions through this just for enforced error checking, but then those are in the strpool, and the pool has its own non-trivial cost, and the private pool trick we use elsewhere seems way out of proportion for storing a couple of tiny strings. 

My excuse for ripping epoch promotion from Python but leaving the ruins in C is basically just that in C, removing would require soname bump, but Python has nothing of the sort. I can certainly put it back there if you prefer.

BTW, last fixup added support for python (e,v,r) tuples as a way of creating version objects, I initially pushed the python bindigs a little bit too hastily :)

**Comment by pmatilai** [comment]
Another fixup to avoid multiple reallocations in rpmverEVR().

**Comment by pmatilai** [comment]
Rebased once more with some tweaks to gain support strings in Python labelCompare() essentially for free things like `rpm.labelCompare("1:1.0-1", "2.0-3")` now do the right thing without requiring the painful tuples.

**Comment by Vogtinator** [comment]
Just to make sure, this behaviour change of `rpm.vercmp` in lua is backwards-compatible, right?
I would assume so, as any segment is also a valid EVR, but there might be some edge case.

Currently we're doing the parsing "by hand" in lua: https://build.opensuse.org/package/view_file/Base:System/rpm/rpmsort?expand=1 I'm really looking forward to drop that for good.

**Comment by pmatilai** [comment]
It should be compatible for legit values of E, V, R. I'm quite positive you can come up with strange behavior differences if you feed it versions containing ':' or '-' though.

**Pull request merged**
