### PR TITLE
COPYING: Minor grammar fixes

### PR DESCRIPTION
**Pull request by cgwalters**
I was looking at this file in the context of dnf/rpm-ostree integration:
https://github.com/rpm-software-management/dnf/pull/991#issuecomment-355587679

The incorrect use of "it's" was distracting; I ended up rewording the initial
sentence to be more direct.

The second hunk is another grammar fix.

### CODE REVIEW

**Comment by pmatilai** [comment]
The rewording makes it look like the license is ONLY about the source when that certainly is not the case, NAK for that part. You need to be really, really careful when messing with license texts...

Either just fix the spelling to use "its" or drop the unnecessary mumbling about the source, ie something like "RPM is covered under two separate licenses".

**Comment by cgwalters** [comment]
Updated :arrow_up: to use your suggestion - though can you help me understand: what's the difference between "RPM" and "its source code"?  Documentation?

**Comment by pmatilai** [comment]
Licenses cover more than just the source. If you think about the main difference between GPL and LGPL (which incidentally happens to be the licenses at hand)? The latter permits more liberal linking against the *compiled library* of the software licensed under it. No source involved. Not to mention other runtime aspects, dynamic loading etc.

**Comment by pmatilai** [comment]
Anyway, thanks for the fixes, the "This alternatively" has annoyed me too for a long time but I never remembered to fix it :)

**Pull request merged**
