### PR TITLE
Fix python ts.addErase() not raising exception on not-found packages

### PR DESCRIPTION
**Pull request by pmatilai**
The code would only raise an exception if TransactionSetCore.addErase()
returned an error, but the catch is that with many kinds of argument
types we'd silently skip the whole addition because no headers were found.

This looks to be a regression introduced some eleven years ago in
commit 9b20c706a4f93266450fae2f94007343b2e8fd9e.

Fixes: #1214

### CODE REVIEW

**Comment by pmatilai** [comment]
Okay @ffesti pointed out that the initial version was buggy too if multiple entries were being processed, and the logic wasn't that clear anyway. Updated to just test for no matches-case explicitly, which is much more obvious.

**Comment by ffesti** [comment]
Still not quite sure what the right behaviour is here. Raising the exception when passing in an non existing header number is all fine. It may also be fine for a name/label that is not found in the rpmdb. Where things get murky is when passing in an empty match iterator. I could imagine some code may rely on this just working and doing nothing.

**Comment by pmatilai** [comment]
So that empty iterator will pass right through because that iterator is never false (another quirk in there, deity knows how long), and this new revision actually reintroduced the specific bug this was supposed to fix.

**Comment by pmatilai** [comment]
Eh, this is so broken I doubt anybody can have relied on any particular behavior.
On RPMDBI_PACKAGES mi is always true whether there is something on it or not, but eg 'name' matches actually mean something.

**Comment by pmatilai** [comment]
Eg:
```
>>> bool(ts.dbMatch('packages', 123456789))
True
>>> bool(ts.dbMatch('name', 'xzyd'))
False
>>> bool(ts.dbMatch('name', 'rpm'))
True
```

**Comment by pmatilai** [comment]
All that said, I do agree that allowing an empty match iterator seems like a useful case to support.

**Comment by pmatilai** [comment]
Okay, maybe third time's the charm... now with iterators specifically handled etc, it looks kinda nicer too.

**Comment by pmatilai** [comment]
One more tweak: testing for empty hdrs only actually makes sense for the case where we do our own dbMatch(), which makes the whole thing a little more obvious again.

**Pull request merged**
