### PR TITLE
Populate user and group data in cpio payload again

### PR DESCRIPTION
**Pull request by pmatilai**
In general, rpm populates the cpio header with the same info as the file lists in the header, although it only uses the latter. This is even documented in LSB (up to and including version 5). At some point, the user and group information has gotten dropped though, all files end up owned by root:root according to the cpio header.

The roots of that change go deeper than I care to dig, but I've noted this behavior in commit fc36f322e123a7421b798f12358cc701e28afbe0 already. The actual change has happened earlier, possibly 8b7b911a17f187822f6e72b162ef3bea39366176 but it's impossible to test stuff that old.

While the cpio format is on its way out, packages built with current rpm versions will live long into the future so we might as well fix this, I see no reason not to. Add a test as well.

Payload digest changes, causing all the other hashes to change too.

### CODE REVIEW

**Comment by ffesti** [comment]
I doubt that checking for the build time will work for long. You either need to check in the package, set the file dates manually or filter out the dates in the output.

**Comment by ffesti** [comment]
Looks like the CI agrees with me...

**Comment by pmatilai** [comment]
That's pretty funny :smile: I never so much as noticed there was a buildtime being included... and this is probably why the earlier test uses a custom queryformat instead of 'rpm -qpl'. Probably goes back to times before we had these source_date_epoch thingies...

**Comment by pmatilai** [comment]
Changed the date to be firmly in the past, otherwise it'd break in a year or so when cpio starts reporting the year instead of the hour.

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
