### PR TITLE
Introduce a new qualifier for meta dependencies (RhBug:1648721)

### PR DESCRIPTION
**Pull request by pmatilai**
Add a new "meta" qualifier for expressing dependencies that are not
concrete install- or run-time dependencies, and thus should not take
part in install ordering.

There are quite a lot of such dependencies in the wild, for example
versioned sub-package cross-dependencies are typically of this type
and a common source of unnecessary dependency loops. Another common
case are dependencies of meta-packages.

### CODE REVIEW

**Comment by pmatilai** [comment]
Just for the record, I'm not super happy with the name "meta", but it's by far the least-worst of the options that I've come across so far. Names are hard.

**Comment by ignatenkobrain** [comment]
I just realized, is it possible to generate deps with qualifiers by dependency generators?

**Comment by pmatilai** [comment]
Not possible. Traditionally all the generated dependencies have been strictly run-time dependencies and there has been no legit use-case, but if this meta-thing gets added, that situation changes somewhat.

In the meanwhile I also recalled some of the open questions surrounding this:
- any non-ordered dependency types in OrderWithRequires should optimally be errors or at least warnings because that just doesn't make any sense, currently the values are not sanity checked at all
- what combinations of pre/post/blaa and meta are legitimate?

**Comment by pmatilai** [comment]
FWIW, some of the alternative names suggested are

- "unordered" which would be a feature bit similar to "missingok" rather than the other "qualifiers" like pre/post which reflect package scriptlets. But whereas "missingok" is technically applicable to any dependency, "unordered" together with eg "post" makes no sense whatsoever. However some other qualifier (such as the suggested "meta") *can* be combined with others in the sense that it simply means: it is both an install and run-time dependency, something which is currently not possible within a single Requires: tag.
- "installed" would seem quite to the point, until you consider "Requires: foo" and "Requires(installed): foo" side by side - this seems to somehow to imply that "Requires: foo" does not include requirement to be installed, which is all confusing and wrong.

**Comment by pmatilai** [comment]
The more I think about this, the more I actually start to like the "meta" name: as opposed to the concrete dependencies like soname requires which are hard run-time requirements, this describes a more abstract relation. Such as the case of a meta-packages which can be used to pull in technically independent but functionally related pieces together, or the typical "Requires: %{name} = %{version}-%{release}" dependencies from sub-packages to the main package, which in presence of eg soname dependencies should not be strictly needed, but is commonly used to avoid having to support weird combinations of different versions.

**Comment by ffesti** [comment]
The way the current qualifiers work is very peculiar.

If none is given the Requires applies always and is used for ordering and must be obeyed for installed packages, too.
If any one is given (except `interp` which seams not to be used really) the requires only applies during the installation/erasure. Some of them are still used for ordering with `pre` and `preun` are given priority in case of dependency loops. 

Combining multiple qualifiers will make the Requires less specific (which is kinda odd). But it never to the point where they apply outside of the installation/erasure time. There currently is a bug (#1030) so adding the right qualifiers does not re-enable ordering but this will be fixed.

So multiple Requires lines with different qualifiers (and the same NFV) can be merged by adding the qualifiers, but Requires with and without qualifiers cannot.

This will make the new "meta" qualifier an oddball as it re-enables the Requires for installed packages which cancels one of the main traits of all other qualifiers. It also cancels ordering - unless combined with another qualifier requiring ordering. If implemented this way it can be combined with other qualifiers and has the same property of not being mergable with an non-qualified Requires.

**Comment by ffesti** [comment]
The current implementation does not work when combining meta with other qualifiers. isInstallPreReq() and isErasePreReq() need to be adjusted to to return 0 if RPMSENSE_META is set or their uses (in depends.c and rpmdb.c) need to be adjusted to take RPMSENSE_META into account there.

**Comment by pmatilai** [comment]
Rebased to resolve conflict from #1031

**Comment by ffesti** [comment]
Ok, these patches still need to be reordered. The https://github.com/rpm-software-management/rpm/pull/1028/commits/8c26fe84298ec922a4040a6a9c65ed2c73c39739 first and the last one (https://github.com/rpm-software-management/rpm/pull/1028/commits/2edc57ff1c1c40e6fa3ad3167e96965f567a7ddf) needs to be merged into the RPMSENSE_META patch (https://github.com/rpm-software-management/rpm/pull/1028/commits/b3b2cbabbf737eb175deca8377941ab1b8107286). I will do that as soon as this patch set has the green light.

With these patches the RPMSENSE_META should behave as described above even when mixed with other qualifiers: Don't enforce ordering but be taken into account even when already installed.

**Comment by pmatilai** [comment]
I'm fine with the change as such, I just can't help finding reqIgnoreIfInstalled() jarring as a name because it's so different from all the other things that are however tightly related. Consistency is good, even if the original names might not be that great. How about isTransientReq()?

**Comment by ffesti** [comment]
Ok, renamed macro, re-ordered, squashed.

**Comment by pmatilai** [comment]
Care to elaborate on "the logic" a little bit in the isTransient() commit message? I know and you know, but it's a nice opportunity to advance it from tribal knowledge to written knowledge.

**Comment by ffesti** [comment]
Ok, extended the commit message.

**Comment by pmatilai** [comment]
Cool, thanks. Looks good to me now, but GH wont let me approve my own PR. Funny that  :smile:

**Pull request merged**
