### PR TITLE
Add parsed and expanded spec to src.rpm header (#1241)

### PR DESCRIPTION
**Pull request by pmatilai**
The trend of packaging is to hide more and more of what actually happens
behind helper macros and other dynamically generated constructs. While
this is mostly a good thing, it makes understanding and postmortem
analysis harder than it should be. Add the spec in its parsed and
expanded form into the src.rpm header to make the actual contents of the
build more trackable.

It can be argued this does not belong in the header and should be in
payload instead, my rationale for the placement is that this way the
payload remains effectively arch independent, whereas the header already
heavily reflects the particular environment where it was built.

Probably worth noting that %setup and %patch built-in macros are not
properly expanded in the stored spec, but that's a separate issue
related the special way %prep is processed.

Fixes: #1241

### CODE REVIEW

**Comment by pmatilai** [comment]
Just realized that in this form the tag gets added too soon from dynamic spec generation POV, but that shouldn't be hard to change if/when needed.

**Comment by pmatilai** [comment]
Tag documentation added, tag addition moved to late src.rpm creation so it'll only be added to physical src.rpm files and will catch possible dynamic additions.

**Comment by bmwiedemann** [comment]
I found that unfortunately this change makes many of our rpm builds unreproducible, because our .spec files contain things like `make %{?_smp_mflags}` and that gets expanded depending on the build machine CPU core count.

Is there an easy way to disable this or do you have a different proposal of how to build bit-identical rpms again?

**Comment by StefanBruens** [comment]
@bmwiedemann - it may be possible to only put the core count into a shell variable, but the shell variable also must not be defined based on an rpm macro.

I.e. the `RPM_BUILD_NCPUS=\"%{_smp_build_ncpus}\"` in `%___build_pre` (`/usr/lib/rpm/macros`) already fails this condition.

**Pull request merged**
