### PR TITLE
brp-compress: Handle zstd compressed man/info pages

### PR DESCRIPTION
**Pull request by berolinux**
Handle zstd compressed man/info pages in brp-compress

Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@ignatenkobrain @pmatilai It seems like the tests are choking on `python` binary missing?

```
+/opt/rpm/tests/rpmtests.dir/at-groups/398/test-source: line 70: python: command not found
```

We probably need to request `/usr/bin/python` now...

**Comment by pmatilai** [comment]
> We probably need to request /usr/bin/python to be installed now...

Nah. What @berolinux needs to do is rebase his tree: https://github.com/berolinux/rpm says:
"This branch is 633 commits behind rpm-software-management:master. "

**Comment by Conan-Kudo** [comment]
Welp! 🐙

**Comment by berolinux** [comment]
rebased

**Comment by pmatilai** [comment]
Yup, much better now  :)
Thanks for the patch!

**Pull request merged**
