### PR TITLE
Some documentation improvements

### PR DESCRIPTION
**Pull request by DemiMarie**
This adds some documentation I wish I had when researching RPM’s security.

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]
I'm curious where you encountered a compiler that doesn't do this, but looks fine to me. 👍🏾

**Comment by DemiMarie** [comment]
> I'm curious where you encountered a compiler that doesn't do this, but looks fine to me.

At least GCC and Clang take advantage of signed integer overflow being undefined to perform optimizations, unless told not to.  And Clang *always* assumes that dereferencing NULL will never happen, and that the result of out-of-bounds pointer arithmetic will not be used.

**Comment by DemiMarie** [comment]
Right now, I would not be comfortable compiling RPM with any compiler except GCC unless optimizations were disabled.

**Comment by Conan-Kudo** [comment]
OpenMandriva has been shipping RPM compiled by Clang for three years now.

**Comment by DemiMarie** [comment]
> OpenMandriva has been shipping RPM compiled by Clang for three years now, with optimizations. I would think @berolinux would want to know about specific reasons not to do that...

My recommendation to @berolinux would be to pass `-fsanitize=undefined -fsanitize-minimal-runtime`.

**Comment by DemiMarie** [comment]
Also, the issue isn’t “Clang causes RPM to stop working in normal use”, but “clang optimizes out critical security checks”.  I have no evidence that this happens in practice, but it could start happening in any minor release.

**Comment by pmatilai** [comment]
Calm down please. The sky hasn't fallen in 20+ years of rpm being built with all manner of different compilers.

**Comment by pmatilai** [comment]
NAK.

I absolutely will not get into this sort of hair-splitting over what is just your average-if-old codebase of C.

**Pull request closed without merging**
