### PR TITLE
AIX has system instead of root as the primary group

### PR DESCRIPTION
**Pull request by ayappanec**
This PR is based on this issue https://github.com/rpm-software-management/rpm/issues/210

### CODE REVIEW

**Comment by ayappanec** [comment]
Thanks @pmatilai for the input. I will come up with the new changes

**Comment by ayappanec** [comment]
@pmatilai Just made few changes as you suggested. See here https://github.com/aixoss/rpm/commit/2aa6af684319f314407a1eaf58177209f14415f0

About the bunch of %defattr's , since i am not familiar with the code that much so that i didn't touch that part. If you have any suggestions , please let me know

**Comment by pmatilai** [comment]
Looks much better, thanks, please update this PR with the new version. 

Having to awk for the username seems a bit gross but then I would've expected `id` to take numbers since day one, which clearly is not the case (it doesn't work in RHEL-5 or -6 either) maybe we'll just have to live with it.

**Comment by pmatilai** [comment]
Oh and BTW, if this fixes the immediate issue you have and then we can deal with the build-side of things(%defattr and the like) in a separate patch later on.

**Comment by ayappanec** [comment]
Thanks @pmatilai . Is it okay if i open a new PR ? . I never tried updating a PR ;-(

**Comment by pmatilai** [comment]
Thats ok too :)

**Comment by ayappanec** [comment]
@pmatilai I just opened a new PR. Thanks

**Comment by pmatilai** [comment]
Superceded by #219.

**Pull request closed without merging**
