### PR TITLE
brp-remove-la-files: Remove symlinks, too

### PR DESCRIPTION
**Pull request by ffesti**
As we check for file contents delete symlink before looking at regular files.

Resolves: #3304

### CODE REVIEW

**Comment by pmatilai** [comment]
A test? You don't need to create a project with .la files in it and spec and all, just write a bunch of files to a directory and run the script on that.

I'd place the invocations in a for loop over the file type - otherwise it takes some squinting to see that it's all identical except for l/f passed to -type.

**Comment by ffesti** [comment]
Loop and test case added.

**Comment by fundawang** [comment]
what if just
```
find "$RPM_BUILD_ROOT" -type f,l -name '*.la'
```

**Comment by pmatilai** [comment]
> find "$RPM_BUILD_ROOT" -type f,l -name '*.la'

That's pretty much how this script started its life as, but it was discovered to remove non-libtool files too, see 432a91151a1f6d19d25e85b0f1af0a0ab6addc46

Unfortunately we didn't demand test-cases for that stuff back then.

**Comment by fundawang** [comment]
> > find "$RPM_BUILD_ROOT" -type f,l -name '*.la'
> 
> That's pretty much how this script started its life as, but it was discovered to remove non-libtool files too, see [432a911](https://github.com/rpm-software-management/rpm/commit/432a91151a1f6d19d25e85b0f1af0a0ab6addc46)
> 
> Unfortunately we didn't demand test-cases for that stuff back then.

I mean can throw loop away:
```
find "$RPM_BUILD_ROOT" -type f,l -name '*.la' 2>/dev/null -print0 |
  xargs -0 grep --fixed-strings '.la - a libtool library file' --files-with-matches --null |
  xargs -0 rm --force
```

**Comment by ffesti** [comment]
Yes, but does it process all links before all regular files?

**Comment by fundawang** [comment]
> Yes, but does it process all links before all regular files?
I guess no, it probably means (**file* or *link*), all the two types are listed together.

**Comment by ffesti** [comment]
Yup, this is why there is a loop. Otherwise we'd encounter dangling symlinks that won't get deleted.

**Pull request merged**
