### PR TITLE
rpmsign: don't create & free NULL pointer

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by pmatilai** [comment]
Patch is fine, but the commit message sort of misses the point - please change it to something like "eliminate unused leftover variable".

**Comment by ignatenkobrain** [comment]
@pmatilai done

**Comment by pmatilai** [comment]
Ack.

BTW, please don't place personal working branches on the main rpm repo, I'd rather keep that as the "canonical and official" repo where the only branches are for official releases.

**Comment by Conan-Kudo** [comment]
@pmatilai Actually, it looks like that was GitHub's fault. The name of the branch looks like how GitHub names them by default.

**Comment by pmatilai** [comment]
Branch names are irrelevant to the point: WIP / pull-request etc branches don't belong to the main repository.

**Comment by Conan-Kudo** [comment]
@pmatilai Well, can you merge it and then delete the branch?

**Comment by pmatilai** [comment]
FWIW, I've been intentionally leaving GH interactions to ffesti but he seems to be out of office for now so...

**Pull request merged**
