### PR TITLE
Trying to upstream debian patches: Fix compilation on platforms without MAP_POPULATE

### PR DESCRIPTION
**Pull request by KOLANICH**
https://salsa.debian.org/pkg-rpm-team/rpm/raw/master/debian/patches/map-populate.patch

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
I feel like this patch is just asking for trouble. Given that it touches the debuginfo generation code, I'm not terribly comfortable passing judgment here.

**Comment by KOLANICH** [comment]
>I think this desserves some better commit message 

I have just preserved the message present in the patch. BTW, it LGTM. How do you propose to change it?

**Comment by pmatilai** [comment]
> How do you propose to change it?

Just note that MAP_POPULATE is safe to drop in this manner as it's only an optimization, so future generations won't need to chase it down.

**Comment by Conan-Kudo** [comment]
@KOLANICH Here's a suggestion:

```
$ git commit --amend --author="Michal Čihař <nijel@debian.org>" --date="Sat, 11 Nov 2017 14:27:10 +0100"
```

With the following commit message:
```
tools/sepdebugcrcfix: Conditionally use MAP_POPULATE with mmap()

Not all architectures offer MAP_POPULATE. As MAP_POPULATE is only an
optimization to improve performance, it is safe to drop it when it is
unavailable.
```

**Comment by pmatilai** [comment]
Merged via #1006 . Thanks for the effort of bringing this upstream.

**Comment by KOLANICH** [comment]
Thanks.

**Pull request closed without merging**
