### PR TITLE
Localize our chroot in/out operations to minimize time spent inside

### PR DESCRIPTION
**Pull request by pmatilai**
The primary motivation here is to consolidate all database accesses
on one side of the chroot, currently it happens on both sides of the
border causing all sorts of issues and limitations (such as preventing
us from using more advanced modes of databases).
As a positive side-effect, the sections where we potentially run
inside chroot are more easily identifiable.

Consolidating on the outside may seem counter-productive, to improve
security it seems you'd want to spend as much time *in* as possible,
including database accesses. Unfortunately due to rpm's access patterns
and API promises, that's not really achievable (tried several approaches,
run into as many dead-ends).

Technically we could localize the chroot placement much further, but
doing so would change the side for transaction callbacks, which could
cause nasty breakage for our API users as various clients use those
callback slots to update their own databases and logs. So the chroot
spots here are selected to cover minimum possible code while preserving
the chroot side of callbacks and plugin slots: RPMCALLBACK_INST_OPEN/CLOSE,
ELEM_PROGRESS and VERIFY_* occur outside the chroot, everything else inside.
Of plugin slots, init/cleanup and tsm_pre/post occur outside, everything
else inside.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@pmatilai Is this something you want to also include for rpm 4.15?

**Comment by pmatilai** [comment]
Heaves forbid, no. Not at this point in the release process.

**Comment by pmatilai** [comment]
Refactored into two commits to eliminate the indentation problem in the first version, and clarified commit message.

**Comment by pmatilai** [comment]
Since there are no further comments...

**Comment by mlschroe** [comment]
My only concern is that the password/group lookups in rpmug.c need to be done in the chroot, but you probably already checked that.

**Pull request merged**
