### PR TITLE
WIP: Use Python Stable ABI for the bindings

### PR DESCRIPTION
**Pull request by encukou**
These are the changes needed to use Python's stable ABI. This allows the extension to be used without recompilation with multiple versions of Python (from 3.7 until an ABI break).

Hack to make this easier:
- type objects are allocated when the module loads, stored in global pointers, and never released
- the module may only be loaded once per process, so each type is leaked at most once, and the global pointers aren't clobbered.

There is no support for installing for, nor testing with, multiple versions of Python at once. That's left up to distributors for now. (AFAIK it's a bit of uncharted territorry for projects that aren't Python-first.)

The individual commits carry explanations for each kind of change, but the in-between commits won't necessarily build. (i.e. you'd need a Git *merge commit* to  preserve both messages and bisectability.)

I am asking for help with the build system. As it is (in the last commit), it's a bit chaotic:
- With CMake 3.26+, stable ABI will be used by default.
  - This requires Python 3.7+
  - This can be turned off using `cmake -DENABLE_PYTHON_SABI=OFF` (e.g. to allow an older Python version)
- With older CMake, or `ENABLE_PYTHON_SABI=OFF`, stable ABI is not used

If that's fine, I can put it in the build documentation.
If it would be better to build stable ABI even with older CMake, it shouldn't be hard to set the flag manually instead of using CMake's integration.

I've built and ran the tests with Python 3.6-3.12. Sadly I don't have easy access to 3.5 and below.

Fixes: #2345

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
> With CMake 3.26+, stable ABI will be used by default.

This is fine, we can work in subsequent PRs to handle it internally for older CMake versions.

**Comment by pmatilai** [comment]
I think, if we go for the stable ABI we should then stick to it too, meaning simply cut off support for versions where not available. 

Requiring Python >= 3.7 is not a problem, I'm just curious as to what makes that particular version special. Cmake >= 3.26 is too new for us to require though, but this shouldn't be hard to do manually. Looking at the cmake's FindPython module, something like `target_compile_definitions(_rpm PRIVATE Py_LIMITED_API=x)` in python/CMakeLists.txt I suppose.  There's something about linking to a specific library too, but according to https://docs.python.org/3/c-api/stable.html that's a Windows-only thing.

**Comment by Conan-Kudo** [comment]
@pmatilai I would just backport the FindPython module and conditionally use it if CMake is too old.

**Comment by pmatilai** [comment]
I did look at the FindPython module, and to me that looks just the kind of gibberish we left autotools behind for. No thanks. I'm fine importing it as long as it's somebody elses headache but that's the end of that.

**Comment by Conan-Kudo** [comment]
Well, I guess then we should hope for [my CentOS Stream MR](https://gitlab.com/redhat/centos-stream/rpms/cmake/-/merge_requests/11) to be merged? 😅

**Comment by Conan-Kudo** [comment]
As it stands, we gracefully fall back to the current behavior anyway, so I don't think the CMake stuff is a reason to hold up this PR.

**Comment by pmatilai** [comment]
See my earlier comment, I don't WANT it to fall back to current behavior because then you never really know whether a patch is SABI compliant or not because your setup *may* depend on these factors.

**Comment by encukou** [comment]
> Requiring Python >= 3.7 is not a problem, I'm just curious as to what makes that particular version special.

[`PySlice_GetIndicesEx`](https://docs.python.org/3/c-api/slice.html#c.PySlice_GetIndicesEx) uses a deprecated implementation (on all Python versions) if ABI compatibility with 3.6 is needed.
That implementation is only unsafe in rather exotic edge cases ([indexing by an object that has side-effects on conversion to `int`, or another thread changing a sequence size](https://github.com/python/cpython/issues/72054)), but it does emit a compile-time warning.
If y'all can live with the warning, I think (but haven't checked), that would allow ABI compatibility with Python 3.4+. But, IMO it's better to use version-specific ABI for such old Python versions.

> Requiring Python >= 3.7 is not a problem, I'm just curious as to what makes that particular version special. Cmake >= 3.26 is too new for us to require though, but this shouldn't be hard to do manually. Looking at the cmake's FindPython module, something like target_compile_definitions(_rpm PRIVATE Py_LIMITED_API=x) (where x is the desired version obviosly) for in python/CMakeLists.txt I suppose. There's something about linking to a specific library too, but according to https://docs.python.org/3/c-api/stable.html that's a Windows-only thing.

Here's what's different for stable ABI builds:

- Compiling with `Py_LIMITED_API=0x03070000`, so only “stable” API is allowed.
- Naming the `.so` appropriately. Currently `cmake` outputs `_rpm.so`, which doesn't need to change -- any Python will load it. In the future CMake *might* switch to `_rpm.cpython-311-x86_64-linux-gnu.so`/`_rpm.abi3.so`, but I bet it'll use a `cmake_policy` for that kind of change, so there'll be plenty of time to adjust.
- On Windows, linking with a different Python library if appropriate

So, yeah, adding `target_compile_definitions(_rpm PRIVATE Py_LIMITED_API=Py_LIMITED_API=0x03070000)` will do the trick.
But it might be better to use CMake's `Development.SABIModule` if it's available?

**Comment by encukou** [comment]
Would this work?

- CMake 3.26+ default:
   - Build for stable ABI using CMake's mechanism
   - Needs Python 3.7+
- Older CMake, and builds with `-DENABLE_PYTHON_SABI=OFF`:
  - Needs Python 3.2+
  - On Python 3.7+, build for stable ABI "manually" by defining 

(I haven't tested, I'm still not sure what should be done)

**Comment by pmatilai** [comment]
I think that's  still unnecessarily complicated :sweat_smile: 

In a case like this using cmake's integration doesn't help because it's only *more* code and fu to support. I don't really want to see a single option related to this because those are just extra baggage that can break and need testing. Just use the manual cmake thing always, unconditionally, and update the Python requirement in INSTALL to 3.7. We'll switch to the cmake integrated Development.SABIModule version when we some day bump our cmake version to one that supports it.

Apologies for not clearly stating this earlier.

**Comment by pmatilai** [comment]
The cmake nits aside, I briefly skimmed through this and seems like a lot of fairly mechanical transformations (even saw a mention of coccinelle in there), and nothing in the "OMG we can't do that" department.

So just trim out the extra complications from the cmake department and I'll be happy to merge.

**Comment by pmatilai** [comment]
I'd prefer the "Fix comment style" commit to be merged into the previous commit that introduces the comment, but other than that looks fine to me. Unless you have something else you're planning to work on here, just flag ready for review and I'll merge, we already did the review part here.

**Comment by encukou** [comment]
I did that, and I also updated the version in the `INSTALL` file.

I didn't test this build config with all the Python versions, and I won't get to that next week, but will do it the week of Oct 16. I find any issues, I can open a fixup PR.

**Comment by pmatilai** [comment]
Nice, thanks!

**Pull request merged**
