### PR TITLE
Fix out-of-tree builds

### PR DESCRIPTION
**Pull request by DemiMarie**

### CODE REVIEW

**Comment by ffesti** [comment]
I don't quite get this change. Why is srcdir removed from the dependency line but not the pandoc command?

**Comment by DemiMarie** [comment]
> I don't quite get this change. Why is srcdir removed from the dependency line but not the pandoc command?

I don’t quite understand this change either.  What I do know is that out of tree builds fail without it, but work with it.  I suspect it has to do with how GNU make does VPATH lookups.

**Comment by ffesti** [comment]
Can you please provide the command you used to build and may be even the error message you got?

**Comment by DemiMarie** [comment]
> Can you please provide the command you used to build and may be even the error message you got?

I used a complex custom shell script; I will try to reproduce without it.

**Comment by pmatilai** [comment]
A VPATH build in a read-only tree is done by each and every CI run via `make distcheck`, and clearly that is working just fine. This is some local issue in your setup.

**Pull request closed without merging**
