### PR TITLE
Trying to upstream Debian patches: Use the Debian standard (and safe) mechanism of generating temporary files.

### PR DESCRIPTION
**Pull request by KOLANICH**
From: https://salsa.debian.org/pkg-rpm-team/rpm/raw/master/debian/patches/tempfile.patch

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Why is this safe? And is this a universally available property?

**Comment by KOLANICH** [comment]
I am not the original author of the patch (and also in the patch metadata it is written that the author is unknown, but the maintainer says he doesn't remember any contributions whose author is unknown, the most likely the patch should be also attributed to him) but I guess that `tempfile` deals with the case when the file already exists. IDK though if `tempfile` is available in fedora.

**Comment by ignatenkobrain** [comment]
why not `mktemp`?

**Comment by pmatilai** [comment]
Please squash the commits, we don't want two separate commits for this. Also it'd be good to have the original author mentioned - surely Debian has package change history available somewhere?

Other than that, mktemp seems pretty obviously right thing to do here. The only question is whether the vpkg-provides.sh script should be just axed instead, in my 15+ years of rpm involvement I've yet to see a single person actually use or refer to it...

**Comment by Conan-Kudo** [comment]
@pmatilai 

Original patch header information:

```
    - vpkg-provides.sh, vpkg-provides2.sh: Use tempfile(1) for safe creation
      of all temporary files. Many changes and untested. These scripts do not
      work on linux anyway.
 -- Joey Hess <joeyh@debian.org>  Thu, 19 Dec 2002 00:31:10 -0500
```

For what it's worth, I've seen the script used for getting rpm to be useful on UNIX systems so that rpm functions as a package manager when the core system isn't managed by it (e.g. AIX mainly). I have a variation of this script I use for macOS as well.

**Comment by Conan-Kudo** [comment]
Also... It appears `mktemp(1)` does not exist on AIX, which might be why this script doesn't use it.

Cf. https://stackoverflow.com/questions/10224921/how-to-create-a-temporary-file-with-portable-shell-in-a-secure-way

**Comment by pmatilai** [comment]
Well, that's a good point. We'd be rendering this script unusable for what it does by making it "more correct" on Linux where it's not even supposed to be used at all. We also don't actually install these scripts since 2007 (see commit 4e52d18de873a861447a589f52c85de2326cd863) so I think it's best to just leave the bad alone, and Debian drop that unused patch, or just 'rm' the stupid file if it offends some checkers.

**Comment by KOLANICH** [comment]
>Also it'd be good to have the original author mentioned - surely Debian has package change history available somewhere?

It is stored in [the form of the patch](https://salsa.debian.org/pkg-rpm-team/rpm/raw/master/debian/patches/tempfile.patch) in which it is written

>Description: Use the Debian standard (and safe) mechanism of generating temporary files
>Author: Unknown

This metadata tags were added in https://salsa.debian.org/pkg-rpm-team/rpm/commit/9bc82bea6dc2af7f07c7dd5044d8cbe0c4ab4a2e#591d515b5331531e8f14b02280b3cb48e2bb72d2 by @nijel.

That file was introduced in https://salsa.debian.org/pkg-rpm-team/rpm/commit/bb4e4de86405c3d1fb77c53a71c4fc84f6f83d48#7925069534c3fb9b5bf5c78b20291c070694a2da by @lool

then the description was added in https://salsa.debian.org/pkg-rpm-team/rpm/commit/5c1b5e3a67e2170c9e0898a16ccf57a4f4f9bac8#4c9800bfef626d61e9bd3915cec97b4e42ad0224 by `Anand Kumria` (`wildfire@progsoc.org`, `wildfire@progsoc.uts.edu.au`, I haven't found any recent activity on GH by him, there are plenty of Anands Kumria on GitHub). Should we attribute the patch to him?

**Comment by Conan-Kudo** [comment]
@KOLANICH The patch was created by @joeyh in 2002, per `debian/changelog`.

**Comment by pmatilai** [comment]
Yup.

But more to the point: this file is not even installed anywhere. The patch was added in 2002, and still applies because the file is in the source tree but it hasn't been installed in the last 12 years. 

Just drop the patch, and lets leave the patch as it is to avoid breaking platforms to which the script is targeted for. Thanks for bringing it to our attention anyway.

**Pull request closed without merging**
