### PR TITLE
Handle revocation

### PR DESCRIPTION
**Pull request by nwalfield**
This cleans up https://github.com/rpm-software-management/rpm/pull/1993/commits/7e10e0d3572b79a210b14c6b00da8e68af7d8c0f as per the comments in the pull request.  I also:

  - Added my tests in place of @DemiMarie's, which used certificates that will expire in two years.
  - Added the missing break PR so that my test cases pass (https://github.com/rpm-software-management/rpm/pull/2026)
  - Dropped [6bf8f03](https://github.com/rpm-software-management/rpm/commit/6bf8f0350dedb8be5bcab94fdded73c00a37652d), as it is [a non-functional clean up](https://github.com/rpm-software-management/rpm/pull/1993#issuecomment-1100211400).
  - Dropped https://github.com/rpm-software-management/rpm/pull/1993/commits/4d19b426df1814c28591f3ffe206ead60ec8b0fa, as it [changes the semantics](https://github.com/rpm-software-management/rpm/pull/1993#issuecomment-1097830727).
  - Split https://github.com/rpm-software-management/rpm/pull/1993/commits/d6402e97fbba525f2ec0e7c02f8e112397666646 into two commits, as it represents two separate changes.

### CODE REVIEW

**Comment by DemiMarie** [comment]
> * Added my tests in place of @DemiMarie's, which used certificates that will expire in two years.

FYI, some of my tests cover very specific corner cases, such as packets in non-standard orders.  It might be better for to change the expiration dates.  Secret keys should also be included, so anyone could do that.

**Comment by DemiMarie** [comment]
@nwalfield: instead of dropping 4d19b426df1814c28591f3ffe206ead60ec8b0fa, it might be better to return `RPMRC_FAIL`, which matches Sequoia.

**Comment by nwalfield** [comment]
> > * Added my tests in place of @DemiMarie's, which used certificates that will expire in two years.
> 
> FYI, some of my tests cover very specific corner cases, such as packets in non-standard orders. Earlier versions of my patch, as well as current RPM, mishandled subkey revocation signatures after subkey binding signatures. Therefore might be better to just change the expiration dates. Secret keys should also be included, so anyone could do that.

If the packets are in non-standard order, then changing the expiration time will cause the certificate to be canonicalized on export.  When I look at the packets, they seem to be in standard order:

```
$ sq packet dump first-signing-key-revoked.asc | grep -E 'Packet,|Type:'
Public-Key Packet, old CTB, 51 bytes
User ID Packet, old CTB, 39 bytes
Signature Packet, old CTB, 154 bytes
    Type: PositiveCertification
Public-Subkey Packet, old CTB, 51 bytes
Signature Packet, old CTB, 171 bytes
    Type: SubkeyRevocation
Signature Packet, old CTB, 239 bytes
    Type: SubkeyBinding
          Type: PrimaryKeyBinding
Public-Subkey Packet, old CTB, 51 bytes
Signature Packet, old CTB, 239 bytes
    Type: SubkeyBinding
          Type: PrimaryKeyBinding
$ sq packet dump rpm.org-ed25519-subkey-test.pub | grep -E 'Packet,|Type:'
Public-Key Packet, old CTB, 51 bytes
User ID Packet, old CTB, 121 bytes
Signature Packet, old CTB, 148 bytes
    Type: PositiveCertification
Public-Subkey Packet, old CTB, 56 bytes
Signature Packet, old CTB, 182 bytes
    Type: SubkeyRevocation
Signature Packet, old CTB, 120 bytes
    Type: SubkeyBinding
Public-Subkey Packet, old CTB, 51 bytes
Signature Packet, old CTB, 239 bytes
    Type: SubkeyBinding
          Type: PrimaryKeyBinding
Public-Subkey Packet, old CTB, 51 bytes
Signature Packet, old CTB, 148 bytes
    Type: SubkeyRevocation
Signature Packet, old CTB, 239 bytes
    Type: SubkeyBinding
          Type: PrimaryKeyBinding
Public-Subkey Packet, old CTB, 397 bytes
Signature Packet, old CTB, 120 bytes
    Type: SubkeyBinding
$ sq packet dump rpm.org-ed25519-subkey-2-test.pub | grep -E 'Packet,|Type:'
Public-Key Packet, old CTB, 51 bytes
User ID Packet, old CTB, 121 bytes
Signature Packet, old CTB, 154 bytes
    Type: PositiveCertification
Public-Subkey Packet, old CTB, 56 bytes
Signature Packet, old CTB, 182 bytes
    Type: SubkeyRevocation
Signature Packet, old CTB, 120 bytes
    Type: SubkeyBinding
Public-Subkey Packet, old CTB, 51 bytes
Signature Packet, old CTB, 239 bytes
    Type: SubkeyBinding
          Type: PrimaryKeyBinding
Public-Subkey Packet, old CTB, 51 bytes
Signature Packet, old CTB, 148 bytes
    Type: SubkeyRevocation
Signature Packet, old CTB, 239 bytes
    Type: SubkeyBinding
          Type: PrimaryKeyBinding
Public-Subkey Packet, old CTB, 397 bytes
Signature Packet, old CTB, 120 bytes
    Type: SubkeyBinding
```

What were you trying to test exactly?

**Comment by nwalfield** [comment]
> @nwalfield: instead of dropping [4d19b42](https://github.com/rpm-software-management/rpm/commit/4d19b426df1814c28591f3ffe206ead60ec8b0fa), it might be better to return `RPMRC_FAIL`, which matches Sequoia.

Indeed.  Good catch.

**Comment by DemiMarie** [comment]
> > > * Added my tests in place of @DemiMarie's, which used certificates that will expire in two years.
> > 
> > 
> > FYI, some of my tests cover very specific corner cases, such as packets in non-standard orders. Earlier versions of my patch, as well as current RPM, mishandled subkey revocation signatures after subkey binding signatures. Therefore might be better to just change the expiration dates. Secret keys should also be included, so anyone could do that.
> 
> If the packets are in non-standard order, then changing the expiration time will cause the certificate to be canonicalized on export. When I look at the packets, they seem to be in standard order:
> 
> ```
> $ sq packet dump first-signing-key-revoked.asc | grep -E 'Packet,|Type:'
> Public-Key Packet, old CTB, 51 bytes
> User ID Packet, old CTB, 39 bytes
> Signature Packet, old CTB, 154 bytes
>     Type: PositiveCertification
> Public-Subkey Packet, old CTB, 51 bytes
> Signature Packet, old CTB, 171 bytes
>     Type: SubkeyRevocation
> Signature Packet, old CTB, 239 bytes
>     Type: SubkeyBinding
>           Type: PrimaryKeyBinding
> Public-Subkey Packet, old CTB, 51 bytes
> Signature Packet, old CTB, 239 bytes
>     Type: SubkeyBinding
>           Type: PrimaryKeyBinding
> $ sq packet dump rpm.org-ed25519-subkey-test.pub | grep -E 'Packet,|Type:'
> Public-Key Packet, old CTB, 51 bytes
> User ID Packet, old CTB, 121 bytes
> Signature Packet, old CTB, 148 bytes
>     Type: PositiveCertification
> Public-Subkey Packet, old CTB, 56 bytes
> Signature Packet, old CTB, 182 bytes
>     Type: SubkeyRevocation
> Signature Packet, old CTB, 120 bytes
>     Type: SubkeyBinding
> Public-Subkey Packet, old CTB, 51 bytes
> Signature Packet, old CTB, 239 bytes
>     Type: SubkeyBinding
>           Type: PrimaryKeyBinding
> Public-Subkey Packet, old CTB, 51 bytes
> Signature Packet, old CTB, 148 bytes
>     Type: SubkeyRevocation
> Signature Packet, old CTB, 239 bytes
>     Type: SubkeyBinding
>           Type: PrimaryKeyBinding
> Public-Subkey Packet, old CTB, 397 bytes
> Signature Packet, old CTB, 120 bytes
>     Type: SubkeyBinding
> $ sq packet dump rpm.org-ed25519-subkey-2-test.pub | grep -E 'Packet,|Type:'
> Public-Key Packet, old CTB, 51 bytes
> User ID Packet, old CTB, 121 bytes
> Signature Packet, old CTB, 154 bytes
>     Type: PositiveCertification
> Public-Subkey Packet, old CTB, 56 bytes
> Signature Packet, old CTB, 182 bytes
>     Type: SubkeyRevocation
> Signature Packet, old CTB, 120 bytes
>     Type: SubkeyBinding
> Public-Subkey Packet, old CTB, 51 bytes
> Signature Packet, old CTB, 239 bytes
>     Type: SubkeyBinding
>           Type: PrimaryKeyBinding
> Public-Subkey Packet, old CTB, 51 bytes
> Signature Packet, old CTB, 148 bytes
>     Type: SubkeyRevocation
> Signature Packet, old CTB, 239 bytes
>     Type: SubkeyBinding
>           Type: PrimaryKeyBinding
> Public-Subkey Packet, old CTB, 397 bytes
> Signature Packet, old CTB, 120 bytes
>     Type: SubkeyBinding
> ```
> 
> What were you trying to test exactly?

If I recall correctly, I was trying to test a revocation signature after a binding signature, and various orders of revoked and unrevoked signing-capable subkeys.  I was also trying to tests subkeys that cannot sign.  Subkeys without binding signatures also need to be tested.

**Comment by DemiMarie** [comment]
@nwalfield test 267 needs an update, and this PR needs a rebase.

**Comment by nwalfield** [comment]
Closing based on this comment from @pmatilai https://github.com/rpm-software-management/rpm/issues/1978#issuecomment-1111884647

**Pull request closed without merging**
