### PR TITLE
RFC Merge RPM 4.13.x os2 code changes

### PR DESCRIPTION
**Pull request by ydario**
I have committed the generic patches to RPM source tree.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
khm, that doesn't sound right ;)

**Comment by ignatenkobrain** [comment]
I suppose those changes were made against 4.13, but you need to rebase them against master

**Comment by ydario** [comment]
Son_Goku told me patches were ready for PR, but we spoke about rebasing too. So I opened the request to wait for comments :-)

**Comment by ignatenkobrain** [comment]
it's pretty much impossible to make any review here =( because files are mixed and so on. so please rebase it and force-push.

**Comment by ydario** [comment]
ok, going with rebase

**Comment by ignatenkobrain** [comment]
ok, superseded by #260

**Pull request closed without merging**
