### PR TITLE
Add --zlib-compress-debug-sections to find-debug-info.sh

### PR DESCRIPTION
**Pull request by vries**
The script find-debuginfo.sh has a --run-dwz switch to compress the debug
info using dwz.

Add a similar switch --zlib-compress-debug-sections that compresses the debug
info using objcopy --compress-debug-sections.

The two modes of compression can be used independently, so we can use one, or
the other, or both.

### CODE REVIEW

**Comment by pmatilai** [comment]
Seems harmless enough to me, but this isn't really my turf. Mark?

Is there some particular user / use-case for this?

**Comment by vries** [comment]
> Is there some particular user / use-case for this?

No, not for now.

The benefit of using the --zlib-compress-debug-sections option is that installed debug info gets smaller. The drawback is that loading debug information get slower. This may be an acceptable trade-off for either an an entire distro, or a subset of packages, experimentation is required to get that information. This option enables this kind of experimentation.

**Comment by rpm-maint** [comment]
Hi,

Sorry for the late reply.

On Thu, 2019-07-18 at 05:40 -0700, Tom de Vries wrote:
> The script find-debuginfo.sh has a --run-dwz switch to compress the debug
> info using dwz.
> 
> Add a similar switch --zlib-compress-debug-sections that compresses the debug
> info using objcopy --compress-debug-sections.

Note that eu-elfcompress does the same. Not that it really should
matter which tool does it. Currently find-debuginfo.sh uses tools from
both binutils and elfutils, it might be nice to only depend on one set
of tools (my preference would obviously be to migrate everything to the
elfutils toolset).

There is also zlib-gnu, the older, pre-standard, compression. Dunno if
we want to support that too.

> The two modes of compression can be used independently, so we can use one, or
> the other, or both.

I do think that this is a nice option to have in theory. But I haven't
tried it myself yet

> https://github.com/rpm-software-management/rpm/pull/795.patch
> https://github.com/rpm-software-management/rpm/pull/795.diff

-      id="`readelf -Wn "${RPM_BUILD_ROOT}/usr/lib/debug/.dwz/${dwz_multifile_name}" \
-	     2>/dev/null | sed -n 's/^    Build ID: \([0-9a-f]\+\)/\1/p'`"

I am slightly surprised we don't seem to use the dwz build-id. Could
you double check we don't actually need that id?

Also, is there really no distro that is contemplating to use this?
If not, then maybe it is better to not add the extra complexity till
someone really wants it.

Cheers,

Mark

**Comment by vries** [comment]
> Note that eu-elfcompress does the same. Not that it really should matter which tool does it.
> Currently find-debuginfo.sh uses tools from both binutils and elfutils, it might be nice to only
> depend on one set of tools (my preference would obviously be to migrate everything to the
> elfutils toolset).

I have no preference at this point. AFAIU both tools use the same zlib library to do the compression, so there's no benefit from choosing on or the other.

> There is also zlib-gnu, the older, pre-standard, compression. Dunno if we want to support that
> too.

I don't see that as useful now, but it's easy to add later if someone want this.

> I do think that this is a nice option to have in theory. But I haven't tried it myself yet

OK, good to hear.

>> https://github.com/rpm-software-management/rpm/pull/795.patch https://github.com/rpm-software-management/rpm/pull/795.diff
>> - id="`readelf -Wn "${RPM_BUILD_ROOT}/usr/lib/debug/.dwz/${dwz_multifile_name}" \ - 2>/dev/null | sed -n 's/^ Build ID: \([0-9a-f]\+\)/\1/p'`" 
> I am slightly surprised we don't seem to use the dwz build-id. Could you double check 
> we don't actually need that id?

AFAIU, yes, we don't need it. I've split this part off into a separate pull request: https://github.com/rpm-software-management/rpm/pull/825.

> Also, is there really no distro that is contemplating to use this? 
>If not, then maybe it is better to not add the extra complexity till someone really wants it

Well, my intention is to propose this as patch for the rpm package in openSUSE Tumbleweed, either as upstream backport, or as local patch. Obviously I'd prefer a backport ;) .

**Comment by pmatilai** [comment]
Dusting off old PRs... 

Has this gone into openSUSE by now, any experiences collected?
At any rate, you'll need to rebase this PR and get rid of the extra merge commit in order to proceed.

**Comment by pmatilai** [comment]
Closing due to inactivity, doesn't seem to be in Suse either.
Like noted above, this is easy enough to add if/when it becomes actually used and necessary.

**Pull request closed without merging**
