### PR TITLE
Introduce convenient %gsub macro to wrap Lua's string.gsub()

### PR DESCRIPTION
**Pull request by hroncok**
Related to https://github.com/rpm-software-management/rpm/issues/1219
Related to https://src.fedoraproject.org/rpms/python-rpm-macros/pull-request/101

Would you accept (something like) this? It is much easier than calling Lua directly from the spec.

### CODE REVIEW

**Comment by hroncok** [comment]
I like your questions but I don't have the answer. Would exposing Lua string methods on RPM macros make sense? E.g.:

```
%{version:gsub ~} -> as if rpm.expand("%version"):gsub(rpm.expand("~"), "") is called from Lua
%{version:gsub %{thingy} -} -> as if rpm.expand("%version"):gsub(rpm.expand("%{thingy}"), rpm.expand("-")) is called
%{version:gsub [^%%%%w]+ - 5)} -> ...
%{whatever:len}
%{name:lower}
%{commit:sub -8}
```

>     * you'd probably want to use `arg[n]` instead of `rpm.expand('%{?n})` for better control - for one, re-expanding the arguments tends to lead to %-escape hell as the arguments are already expanded once

I was aiming at compatibility with older RPM but %-escape hell seems like it is indeed not worthy.

**Comment by mlschroe** [comment]
Regarding making lua functions easier to access: it would not be hard to add function support to the expression parser:
```
%[lua:gsub("aaa", "a", "b", 2)]
```
Just a thought...

**Comment by jasontibbitts** [comment]
This interests me because I would really like to see simple alternatives to shelling out to sed and such available.  As far as I understand things, it's still not safe to parse an arbitrary specfile because it could shell out to anything.

**Comment by mlschroe** [comment]
I'll create a pull request.

**Comment by pmatilai** [comment]
> This interests me because I would really like to see simple alternatives to shelling out to sed and such available. As far as I understand things, it's still not safe to parse an arbitrary specfile because it could shell out to anything.

Yes, any macro can shell out to anything. Lua as it is in rpm doesn't make that any better because you can do and call out arbitrary stuff from there as well, but Lua does have language-level support for completely sandboxing code. OTOH to do useful thing, some amount of IO is usually required...

**Comment by DemiMarie** [comment]
> Lua does have language-level support for completely sandboxing code.

This assumes that there are no vulnerabilities in the Lua interpreter or in any of the C libraries made available to Lua programs.  This is a bad assumption.

**Comment by pmatilai** [comment]
> This assumes that there are no vulnerabilities in the Lua interpreter or in any of the C libraries made available to Lua programs. This is a bad assumption.

Here in the real world, people need to make assumptions about stuff working as per spec to get work done.

**Comment by hroncok** [comment]
> Regarding making lua functions easier to access: it would not be hard to add function support to the expression parser:
> 
> ```
> %[lua:gsub("aaa", "a", "b", 2)]
> ```
> 
> Just a thought...

Since `gsub()` is a method of string, would this expose string methods only, or would the actual call need to be `%[lua:string.gsub("aaa", "a", "b", 2)]`?

And considering I need to apply this method on macro value, would I need to do `%[lua:string.gsub(macros.foo, "a", "b", 2)]`? That is not such a big improvement over `%{lua:print((string.gsub(macros.foo, "a", "b", 2)))}`.

**Comment by mlschroe** [comment]
Yes, it's `lua:string:gsub`. We should probably introduce some functions that act as shortcuts, e.g. `gsub`.
And no, the arguments are NOT lua expressions. You need to do
```
%[lua:string.gsub("%foo", "a", "b", 2)]
```
or with the shortcut:
```
%[gsub("%foo", "a", "b", 2)]
```
(Note that it is `"%foo"`, `%foo` expands into a number. The expression parser is picky about its data types.)

**Comment by mlschroe** [comment]
Regarding `%{lua:xxx}`: I'm wondering if we should auto-print if the lua code returns a result. Panu?

**Comment by hroncok** [comment]
> Regarding `%{lua:xxx}`: I'm wondering if we should auto-print if the lua code returns a result. Panu?

That has a (relatively low) potential to break existing macros that have not expected this when they were written.

**Comment by mlschroe** [comment]
AFAIK lua doesn't return anything unless as explicit `return` statement is used, so auto-print should not break anything. OTOH it also does not save you much.

**Comment by pmatilai** [comment]
Oh. Auto-printing of returned values is one of those things that make you wonder how come nobody thought of this before :+1:

And yes, Lua only returns anything when explicit `return` is used so this should be safe, to the point that anything is.

**Comment by mkoncek** [comment]
I will add in a real-life scenario for which I could imagine a better way:
```spec
%global upstream_version 1.5.2-3
%global short_version %(echo %{upstream_version} | sed 's/-.*//')
```

**Comment by mlschroe** [comment]
Note that this works with the current rpm code:
```
%global short_version %[lua:string.gsub("%upstream_version","-.*","")]
```

**Comment by pmatilai** [comment]
Superceded by #2181. Thanks for the initiative, this resulted in multiple nice improvements in rpm!

**Pull request closed without merging**
