### PR TITLE
brp-compress: compress fish manpages

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by pmatilai** [comment]
/me wonders wtf are fish man pages but ... whatever :D

**Comment by ignatenkobrain** [comment]
@pmatilai `fish, the friendly interactive shell` ;)

**Comment by Conan-Kudo** [comment]
@pmatilai It's man pages for the best shell ever :)

https://fishshell.com/

**Comment by pmatilai** [comment]
Yes I can google you know ;)

**Pull request merged**
