### PR TITLE
zstd: use thread pool

### PR DESCRIPTION
**Pull request by marxin**
Starting from `zstd` version `1.4.7`, the library provides an experimental usage of thread pools (that's why `-DZSTD_STATIC_LINKING_ONLY=1` is needed). Using them can fully utilize CPU on one side and maintain memory utilization at the same time. Such an approach fixes #1324.

### CODE REVIEW

**Comment by marxin** [comment]
May I please ping this pull request, adding people who helped me in previous zstd-related PR: @ffesti @ignatenkobrain

**Comment by pmatilai** [comment]
Sorry but I can't see us accepting this. It's a layering violation, the build code cannot have any special knowledge of what goes on inside librpmio and vice versa.

Rpm really needs a resource manager (see #804)  ... which hopefully can somehow integrate with these library-specific things as well.

**Comment by marxin** [comment]
> Sorry but I can't see us accepting this. It's a layering violation, the build code cannot have any special knowledge of what goes on inside librpmio and vice versa.

Hm, that's a pity.

> 
> Rpm really needs a resource manager (see #804) ... which hopefully can somehow integrate with these library-specific things as well.

Are you planning to work on the feature in near future?

**Comment by pmatilai** [comment]
Been thinking about it on and off. It'd be one thing if it was just allocating cpu's out of N available, but we're married to OMP which doesn't want to be micro-managed from the outside, and then we have these independent libraries using their own threading schemes...

**Comment by marxin** [comment]
I see your concerns and the pull request is hack a bit. On the other hand, `zstd` provides a nice thread pool functionality and package build really benefits from it. Right now, packages like Firefox also mostly compressed in one thread as compression of the biggest `.rpm` takes minutes.

**Comment by pmatilai** [comment]
Yes, but rpm io is not limited to zstd. Zstd may be the hot new thing now, but who knows what that is 5 years from now. A few years ago it was XZ. The fact that there are compressor specific hacks allows these things to change over time with no changes to the surrounding code, and that's why we need to honor this abstraction. And yes, everything comes at a price.

**Pull request closed without merging**
