### PR TITLE
scripts/pythondistdeps: Various updates and fixes (no test suite)

### PR DESCRIPTION
**Pull request by torsava**
This is a modification of PR https://github.com/rpm-software-management/rpm/pull/1195, where I've deleted all mentions of the test suite.

CC @pmatilai, @Conan-Kudo, @ffesti, @hroncok

### CODE REVIEW

**Comment by torsava** [comment]
> This pull request **introduces 1 alert** when merging [592a6d5](https://github.com/rpm-software-management/rpm/commit/592a6d5980010c63eb76c31ddd8954fba9cbaa92) into [8734c1b](https://github.com/rpm-software-management/rpm/commit/8734c1b97e39e3c7d3ac8396c4d6a2733852545c) - [view on LGTM.com](https://lgtm.com/projects/g/rpm-software-management/rpm/rev/pr-b6979aa46105339f8a0843eae399433dc33d6444)
> 
> **new alerts:**
> 
> * 1 for Module is imported more than once

It's a lazy import so that if it's not needed, it doesn't slow down the execution.

**Comment by ignatenkobrain** [comment]
I would move `import re` to the top imports and just be done with it.

**Comment by hroncok** [comment]
> I would move `import re` to the top imports and just be done with it.

We can discuss this in a separate issue. It hasn't changed here.

**Comment by pmatilai** [comment]
Thanks for the patches and patience!

**Comment by torsava** [comment]
Thank you too, @pmatilai!

**Pull request merged**
