### PR TITLE
Add --excludeartifacts install option

### PR DESCRIPTION
**Pull request by pmatilai**
Like docs, configs etc, excluding artifacts from installation might
sometimes be desireable to eg save space. Inspired by
https://bugzilla.redhat.com/show_bug.cgi?id=1848199

### CODE REVIEW

**Comment by jnpkrn** [comment]
1. as mentioned at that bug, not sure if it's fortunate to mention something
   (`build-id` concept) that cannot be properly referenced, e.g. to `rpmbuild(8)`
   (closest is `tests/rpmbuild.at`: `build-id files should link to the .debug files`),
   perhaps more generic explanation would suffice, or documentation might
   be made more complete overall

2. meant to ask about the contrary and ... it's there already: `rpm -qA ...`,
   making this part a (silently applauded) non-issue

**Comment by jamescassell** [comment]
Is there a matching dnf options, like `--setopt=tsflags=noartifacts,nodocs`?

**Comment by jnpkrn** [comment]
Good point, I think updating this is a prereq:
https://github.com/rpm-software-management/dnf/blob/master/dnf/base.py#L503-L515

**Comment by jamescassell** [comment]
Thanks for the link! (permalink for posterity: https://github.com/rpm-software-management/dnf/blob/7fb5d83d1872fead362057d014f431a26ffab6e9/dnf/base.py#L503-L515 )

**Comment by jnpkrn** [comment]
(note that reference-file-by-tag, which I did with 2nd iteration, is "perma" enough in 99.99% cases)

**Pull request merged**
