### PR TITLE
Use long PGP Key IDs for all outputs

### PR DESCRIPTION
**Pull request by ffesti**
Here how dropping the Short PGP KEy IDs in favor of long ones would look like. We still need to discuss if this really is a change we want in this magnitue or if we need to keep the old behavior at some places.

### CODE REVIEW

**Comment by nwalfield** [comment]
If you are considering breaking the output format, then I would strongly encourage you to just use the full fingerprint.

A key ID is only 64-bits.  Happily, the security of key IDs does not depend on collision resistance, [which has already been demonstrated to be broken](https://nullprogram.com/blog/2019/07/22/), but collisions can trigger implementation bugs since they are hard to test, and attacks are only going to get stronger.

**Comment by pmatilai** [comment]
We want to move to full fingerprint sure, but since it appears we can't do that without changes to rpm-sequoia (and the legacy parser) we might as well do this as an interim step to find out what exactly (if anything) breaks. It'll be a good while before the change (in either shape) hits the end-user systems.

Another rather user-visible instance of the short keyid use is the gpg-pubkey version, that'll need to change too and it's probably the bigger headache compatibility-wise.

**Comment by nwalfield** [comment]
There's another option: we use fingerprints when available and long key IDs otherwise.  I think this would be a less invasive change.  What do you think?

**Comment by pmatilai** [comment]
It's a different kind of invasive if the output keeps changing.

One important thing here is that there needs to be a clear and easy mapping from the message to what we import to the database, and vice versa.

**Comment by pmatilai** [comment]
So really, I'd merrily merge this change if you change the "other side" of the equation too, ie the imported keys.

It may not be our end goal but it's step up from the disaster where we are currently, and having that step up cemented in the code is a hundred times better than finding ourselves in the same situation in March because unexpected stuff happened. Having the short -> long keyid change in now will also help shake out anything that may be relying on that format in the meanwhile (by the way of dogfooding this stuff on real systems).

**Comment by ffesti** [comment]
Turns out we actually can output the fingerprints without changing the backends.

**Comment by ffesti** [comment]
I have added these changes to #3321. So it is redundant now. Closing.

**Pull request closed without merging**
