### PR TITLE
Preset db backend according to availability

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Not that I particularly object to the PR as a whole, but why are we listing rpmdb backends in `--showrc` instead of making a dedicated option for it?

**Comment by pmatilai** [comment]
I think listing in --showrc is good, but it doesn't have to be the only means of getting this info.

**Comment by lnussel** [comment]
:shrug: whatever you prefer. No is also a valid answer. just found myself looking for the info :)

**Review by Conan-Kudo — APPROVED** [review]
I'm fine with it, but I'd like an option specifically for getting rpmdb backend options that doesn't involve `--showrc`.

**Comment by pmatilai** [comment]
Yup, we can add something else too but this is very useful info in the showrc dump as is. And as this isn't adding any public API or switches it can be freely further worked upon. Thanks for the patch!

**Pull request merged**
