### PR TITLE
Run binary package generation and file classification in parallel threads

### PR DESCRIPTION
**Pull request by pmatilai**
This is a more elaborate version of #226, with various internal issues fixed first for cleaner and simpler resulting code.

### CODE REVIEW

**Comment by pmatilai** [comment]
Added parallel file classification, which is beneficial for some cases.

Most of the time, the dependency generator is the biggest bottle-neck however. That's a *much* tougher nut to crack though: there are huge gains to be made even without parallelisation there, but it needs a massive overhaul to make that possible.

**Comment by voxik** [comment]
I just wonder, how this influences the console output. Will it be still always readable or will there happen some output race conditions and it won't be readable anymore?

**Comment by pmatilai** [comment]
Well, why don't you see for yourself?

**Comment by pmatilai** [comment]
@ffesti spotted a bug in the binaryPackages() for loop logic, fixed in the first push but then a regression introduced in commit  0f21bdd0d7b2c45564ddb5a24bbebd530867bd54 caused one test to fail. Now rebased on top of the regression fix... pffft.

**Comment by pmatilai** [comment]
Maybe third time's the charm... while walking the dog I remembered the hash table added in commit e33045e35c09cda530a9e665c367693e285b6511 that wasn't there when these patches were created needs thread protection now.

**Pull request merged**
