### PR TITLE
RPM 4.17.1.1 regression update

### PR DESCRIPTION
**Pull request by dmnks**

### CODE REVIEW

**Comment by dmnks** [comment]
Oops, forgot to add the "Preparing for..." commit... please don't merge yet :smile:

**Comment by dmnks** [comment]
OK, should be ready now.

**Comment by dmnks** [comment]
Note that I didn't bump the libtool version as these two patches don't touch the library at all.

**Comment by pmatilai** [comment]
The things we do for regressions :sweat_smile:

**Pull request merged**
