### PR TITLE
Add pgpDig functionality to the Sequoia backend

### PR DESCRIPTION
**Pull request by nwalfield**
This reverts commit 87c4eee816a4ddd4291cf1211c0290f3a731be73.

### CODE REVIEW

**Comment by nwalfield** [comment]
@pmatilai, this is ready for review.

**Comment by pmatilai** [comment]
Actually I think this should be against 4.18.x branch, we want these interfaces gone going forward.

**Comment by nwalfield** [comment]
I've backported the changes to the 4.18.x branch.  The test suite passes using libgcrypt, but still fails pending https://github.com/rpm-software-management/rpm/pull/2063, which should be trivial to backport to 4.18.x.

**Comment by pmatilai** [comment]
Somehow failed to realize just how much stuff (shuffling things around etc) this backport will involve, but ... oh well. Thanks.

**Comment by nwalfield** [comment]
No worries!  Thanks for following up quickly.

**Pull request merged**
