### PR TITLE
Fix prefix match searches on strings containing % on sqlite backend

### PR DESCRIPTION
**Pull request by pmatilai**
SQL LIKE is a quirky thing when you only really want exact matches
on a substring. Which begs the question, if we want exact matches on
substring then why not do just that? Why not, indeed. This avoids
escaping madness and the need to use custom extensions for such
a mundane, trivial thing.

Fixes: #1018

### CODE REVIEW

**Comment by pmatilai** [comment]
And yeah. I *knew* I was missing something painfully obvious here. Just how hard can it be...? :joy:

**Comment by mlschroe** [comment]
Do we still need that length comparison then?

Also, the sqlite documentation says that for text string the length is UTF8 characters, not bytes. So this might not work correctly for non-ASCII.

Oh, that's also true for the LENGTH function, it returns characters not bytes. I.e. the original code is also incorrect.

**Comment by mlschroe** [comment]
You could use `INSTR(key, '%q') = 1` but that may be a too slow.

**Comment by mlschroe** [comment]
Or: `SUBSTR(key,1,LENGTH('%q')) = '%q'`

But it's also a bit unsafe to assume that `strlen(key) == keylen`. (OTOH the prefix iterator is currently not exposed and for rpm's usage the length matches).

**Comment by pmatilai** [comment]
Argh, I totally missed the characters vs bytes distinction.
Maybe it is easiest to just add a custom match afterall :roll_eyes:

**Comment by pmatilai** [comment]
Thanks for the review!

**Pull request merged**
