### PR TITLE
Add 'string' into query format extensions in man-pages

### PR DESCRIPTION
**Pull request by pavlinamv**

### CODE REVIEW

**Comment by pmatilai** [comment]
Might want to note that this is also the default format, so using it is generally redundant.

**Comment by pavlinamv** [comment]
Yes, there is no need to use ":string".  But it is supported.

**Comment by pmatilai** [comment]
Yes, and I'm asking that you mention it is the default format to make people aware that it's something they don't need to use. It's basically a side-effect of a code cleanup (in commit 2bfc0fad3876bcee0143664cae9f0f0107a86a33), not something that ever needed using or advertising.

**Comment by pavlinamv** [comment]
Mentioning ":string" in that part of man page, will not cause any problems. But if ":string" is not there, it looks like that it is not supported.

**Comment by pmatilai** [comment]
Ehm. I'm not arguing *against* this addition. I just ask that while we're at it, you *also* document that it's the default format! A simple "(default)" would do. I sure don't want to do *another* pull request just to add that!

**Comment by pmatilai** [comment]
Thanks.

**Pull request merged**
