### PR TITLE
Fix gpg key loading

### LINKED ISSUE #1543: Reconsider GPG key loading from %_keyringpath
At the moment rpm will load keys from a pre-defined directory (`%{_keyringpath}`) and **only** if no keys are found there, will it try to load keys from the rpmdb: https://github.com/rpm-software-management/rpm/blob/1efe530450b5bdbd90128327be56c87fa1b6843b/lib/rpmts.c#L382

This is a bit unfortunate imho, because at least as far as I am aware, no distribution really uses `%_keyringpath` to store keys there (the directory does not exist on openSUSE Tumbleweed nor on Fedora 33 and it is also not provided by any package). Now if someone drops a `*.key` file into `%_keyringpath`, they'll effectively kill key verification as everyone appears to be storing keys in the rpmdb nowadays.

Therefore I would propose to revert https://github.com/rpm-software-management/rpm/commit/9d200565744d3023053d64f627c82cf2451fa701.

### PR DESCRIPTION
**Pull request by D4N**
This fixes #1543

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

**Comment by pmatilai** [comment]
I agree we need to decide what to do with this issue, just not sure that this is necessarily it.
At least the debug message is now even more wrong: the on-disk files as keyring is not "legacy" because it was never even the current thing by any standards.

I'd actually be happier to just remove the whole on-disk keyring thing. This stuff needs a rethink, but that approach isn't it.

**Comment by Conan-Kudo** [comment]
Yocto unfortunately uses the on-disk keyring, so we can't completely remove it.

**Comment by pmatilai** [comment]
We can, but not without a warning and a good reason.

The problem is that it's actually a security hole of a kind, it allows any arbitrary package to drop in files that immediately become system-wide trusted keys. That same thing can of course be seen as a feature.

The biggest issue is that these don't play well together, so maybe it should simply be a compile-time option instead... dunno.

**Comment by Conan-Kudo** [comment]
It's unfortunate that it's trusted without verification. If the feature worked like how it does in DNF (where it's read and imported on request with user interaction), then it'd be salvagable. But it's not. ☹️

**Comment by pmatilai** [comment]
Okay, after a brief consultation with inner demons, submitted #1575 to resolve the issue by making it configurable. 

Thanks for the patch + discussion though as it helped drive this old thing forward finally.

**Pull request closed without merging**
