### PR TITLE
Add an option for zstd long distance matching compression 

### PR DESCRIPTION
**Pull request by kontura**
The behavior is supposed to match the `--long[=#]` option of zstd binary.

We want to add zstd compression to createrepo_c through rpmio and we would like to use this option to make smaller repodata.

### CODE REVIEW

**Comment by pmatilai** [comment]
The problem here is that it reserves a letter in a common namespace for a highly compressor-specific option. I've no objections to support compressor-specific things somehow, but we need to isolate them to a section of their own somehow, eg put them after an optional extra delimiter in the string, so we can have one code to parse the common parts and each compressor can have their own code for their specifics.

Also, is this option specific to compression-time only, or is it relevant for decompression too? We have no means to separate the two ATM, and this is an issue with the T-options too, it shouldn't actually be stored in the rpmio string as it's not relevant for decompressing.

The other thing here, although largely not actually introduced in this patch, is that the warning messages are a bit hysterical: they're awfully verbose, yet manage to say remarkably little: none of them say what the invalid value is, only that they'll be using something else. I'd suggest collapsing all those messages to a RPMLOG_DEBUG message which just says "invalid value %d for %s, using %d" essentially.

**Comment by ffesti** [comment]
Ok, sorry this took this long. I finally came up with a simple solution to the name space problem: We use lower case letters for global options and upper case letters for compressor specific options. This works fine with `T` for threads as it is also only supported by some compressors.

So I changed the option to the letter to `L`. Otherwise the patch is unchanged and merged into master.
Thanks for the patch!

**Comment by ffesti** [comment]
This new options needs to be documented along with several more. Opened #1895 for this purpose.

**Comment by dmnks** [comment]
> We use lower case letters for global options and upper case letters for compressor specific options.

Sadly, this is not 100% true, there's e.g. the `s` for "small mode" in the [bz2 compressor](https://sourceware.org/git/?p=bzip2.git;a=blob;f=bzlib.c;h=21786551b60bd37254954ee53220b0fda80da007;hb=HEAD#l1408) which is handled by the library itself. So while most of the compressor options are handled by us via the respective API calls, in this case it's passed directly in the mode string. I'm not sure if this is important enough to mention in the docs (once we have them), though.

**Pull request closed without merging**
