### PR TITLE
Drop extra newlines from spec parser messages

### PR DESCRIPTION
**Pull request by dmnks**
Please see commit messages for more info.

### CODE REVIEW

**Comment by pmatilai** [comment]
FYI, a PR with failed checks will generally not get much attention. This looks like it just needs some test output updated to the new reality. That case is actually a good argument for the change, the newline(s) make no sense at all.

I'm inclined to think the format string should be in charge of the formatting though, rather than content. There may be cases where you want to omit the newline, and a missing `\n` in printf/log message strings tends to look like, and usually is, a bug.

**Comment by dmnks** [comment]
> FYI, a PR with failed checks will generally not get much attention. This looks like it just needs some test output updated to the new reality. That case is actually a good argument for the change, the newline(s) make no sense at all.

Yeah, I'll fix that.

> I'm inclined to think the format string should be in charge of the formatting though, rather than content.

Agree, although in this case, we're just making use of the fact that the string already has a newline.

We could keep the `\n`s in the format string, and strip it from the content (line buffer here) instead. However, that would require a `strchr()` as we don't store the line's length anywhere. Alternatively, we could store the length (which we know at the time of parsing, actually). Would that be better?

**Comment by dmnks** [comment]
Looking again, it seems like we already do store the length, in `ofi->readPtr`.

**Comment by pmatilai** [comment]
Another thing is that there are *lot* more error messages referring to spec lines than the ones updated here. So something is not quite adding up.

**Comment by pmatilai** [comment]
On a related note, we could use a dedicated spec error reporting function. Our error messages are *all over* the place in terms of formatting and style. If there was one place to fixup such things... 

(and here we have another seemingly trivial ting threatening to quickly escalate out of orbit :rofl: )

**Comment by dmnks** [comment]
I should've mentioned in the commit message that this wasn't intended as a 100% fix of all the messages that print a spec line. Although I did, of course, look through all of them in `parseSpec.c`, so that file is covered.

**Comment by dmnks** [comment]
> On a related note, we could use a dedicated spec error reporting function. Our error messages are _all over_ the place in terms of formatting and style. If there was one place to fixup such things...
> 
> (and here we have another seemingly trivial ting threatening to quickly escalate out of orbit rofl )

Yeah, ideally. We could then also handle the extra newline there, as well as e.g. print the line number together with the actual text (which we now only do in some cases).

**Comment by dmnks** [comment]
OK, turns out the other `parse*.c` files also emit such messages.

So my next plans are:

1. Check if the extra newlines are also present with the other messages that format a spec line (outside of `parseSpec.c`)
2. See if we could have a specialized logging function for spec parsing errors/warnings
3. Rework the patch as appropriate

**Comment by pmatilai** [comment]
The extra newlines are indeed there, try eg "%trigger" line to trigger various errors, but probably varies from one error to another due to all sorts of internal wacko.

The path of less changes may be instead eliminating the newlines as we parse, but there could be dragons in that direction too. If we need to change every other log message in the build code, we should probably take the opportunity to improve the error logging in general, like you noted by putting it into a specialized function for uniform formatting etc. And *if* we go there, outputting the problematic line on a different line from the error message would probably make sense (compare to eg gcc/clang error reporting)

**Comment by dmnks** [comment]
I haven't had a chance to get back to this, so closing now. I'll make another attempt later, perhaps...

**Pull request closed without merging**
