### PR TITLE
Fixes for some issues on Arm platforms

### PR DESCRIPTION
**Pull request by nullr0ute**
We're seeing a few issues on Arm platforms [1], ARMv7 and aarch64, and review there's a few issues and clarifications needed around the way some of the Arm features work. This fixes up the issues seen and clarifies a few details of some of the Arm architecture quirks.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1562084

Signed-off-by: Peter Robinson <pbrobinson@gmail.com>

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@nullr0ute The only potentially legitimate commit here is https://github.com/rpm-software-management/rpm/pull/901/commits/790b0ec08027ba1676acc4091045d78e65aa8f2d, as this one is actually about fixing the problem referenced in the RH bug linked in the PR description.

**Comment by Conan-Kudo** [comment]
Note that even that fix as it stands will break OpenMandriva, who wrote that to support their distribution. If you want to alter it, work with @berolinux to fix it properly.

**Comment by pmatilai** [comment]
Have I ever mentioned I hate arm patches, because the only guaranteed thing is that nobody agrees on how they should be, and I can't be the judge since I don't have a clue.

The commits being reversed have gone in to fix somebody elses issues, and we can't revert them just like that. You'll need to work with the other Arm people to come up with solutions that work for everybody.

**Comment by nullr0ute** [comment]
> As noted above, this needs to be worked out between various Arm maintainers to come up with solutions that work for everybody. We're not on a seesaw.

Maybe if there was engagement from the Arm maintainers in other distros to confirm they were OK with the patches before they were merged we wouldn't have the issue in the first place :-/

I will get people from Arm to confirm the correctness of each patch.

**Comment by nullr0ute** [comment]
> Note that even that fix as it stands will break OpenMandriva, who wrote that to support their distribution. If you want to alter it, work with @berolinux to fix it properly.

I don't see where you support armv5tl, and you provided no details in the commit as to why it was being added, but I'm happy enough to drop those patches as I've long since stopped caring about anything to do with < ARMv7.

**Comment by nullr0ute** [comment]
> This whole PR is awful.

Please keep the discussion technical. Comments like these are a matter of opinion and are useful in productive technical discussion. 

> And the commit about `aarch64` and `arm64` "not being equivalent": tough. In virtually _every_ single non-rpm/non-gcc platform, they _are_ equivalent. We did the same thing for `amd64` and `ia32e` for `x86_64`.

But we're not talking about non rpm and non gcc platforms here. This is very explicitly about rpm. Could you link to details, git commits or software is perfectly fine, how OpenMandriva uses this as I'm very interested in the technical use case so I can understand the reasons.

**Comment by pmatilai** [comment]
> Maybe if there was engagement from the Arm maintainers in other distros to confirm they were OK with the patches before they were merged we wouldn't have the issue in the first place :-/

Said patches sat in our public pull-requests for significant time, some literally for months. Nobody objected.

Now, I'm not interested in any blame games here, I just want the Arm maintainers to
1) settle this among yourselves
2) make arrangements to prevent this from happening again

**Comment by nullr0ute** [comment]
> Said patches sat in our public pull-requests for significant time, some literally for months. Nobody objected.

As the Arm maintainer in Fedora, mostly in my spare time, I unfortunately don't have the time to follow every list of every bit of software available in Fedora to see how it might affect the Fedora/RHEL/CentOS ecosystem.

> Now, I'm not interested in any blame games here, I just want the Arm maintainers to

Me either.

>     2. make arrangements to prevent this from happening again

Would a list of architecture (arm/power/s390x/risc-v etc) people the rpm maintainers could reach out to be of assistance so that they know who to reach out to when an architecture change is posted so they can be clarified be of use moving forward.

**Comment by pmatilai** [comment]
> Would a list of architecture (arm/power/s390x/risc-v etc) people the rpm maintainers could reach out to be of assistance so that they know who to reach out to when an architecture change is posted so they can be clarified be of use moving forward.

Works for me.

I don't know if GitHub has anything to offer for such an "special interest group" functionality, but one possible old-school solution could be something like a kernel style MAINTAINERS file where subsystem maintainers (be them individuals or special interest groups) can announce themselves.

**Comment by nullr0ute** [comment]
> I don't know if GitHub has anything to offer for such an "special interest group" functionality, but one possible old-school solution could be something like a kernel style MAINTAINERS file where subsystem maintainers (be them individuals or special interest groups) can announce themselves.

I'm happy with a MAINTAINERS file or similar, basically I'm happy with whatever works for the maintainers. I'll work on adding an initial version in a different PR. We can always move it to something github related in the future if something better comes along.

**Comment by puiterwijk** [comment]
> > Would a list of architecture (arm/power/s390x/risc-v etc) people the rpm maintainers could reach out to be of assistance so that they know who to reach out to when an architecture change is posted so they can be clarified be of use moving forward.
> 
> Works for me.
> 
> I don't know if GitHub has anything to offer for such an "special interest group" functionality, but one possible old-school solution could be something like a kernel style MAINTAINERS file where subsystem maintainers (be them individuals or special interest groups) can announce themselves.

This sounds like a perfect case of [CODEOWNERS](https://help.github.com/en/articles/about-code-owners) to me if different arches can be moved to different files (imports or something perhaps), who can then automatically be asked for review by GitHub.

**Comment by pmatilai** [comment]
> This sounds like a perfect case of CODEOWNERS to me if different arches can be moved to different files (imports or something perhaps), who can then automatically be asked for review by GitHub.

Oh, perfect. Thanks for the pointer!

**Comment by pmatilai** [comment]
Okay, on a closer look not *perfect* but much better than nothing. If arch maintainers are subscribed to, say, rpmrc.in and lib/rpmrc.c it'll go a *long* way towards avoiding such incidents in the future.
At any rate, having the contacts documented somewhere is the all-important first step.

**Comment by Conan-Kudo** [comment]
@nullr0ute `armv5tl` was used in Mageia, and I upstreamed those changes from Mageia as the rpm comaintainer to reduce the patch load and make our rpms workable on other distros (having "special" architectures is not great...). We used it as the baseline "synthetic" architecture to support many classes of older ARM hardware (RPi 1, old Android devices, weird SBCs, IPMI SoCs, etc.).

The armv8 stuff from OpenMandriva is from @berolinux, and he can explain that one better than I could.

**Comment by nullr0ute** [comment]
> @nullr0ute `armv5tl` was used in Mageia, and I upstreamed those changes from Mageia as the rpm comaintainer to reduce the patch load and make our rpms workable on other distros (having "special" architectures is not great...). We used it as the baseline "synthetic" architecture to support many classes of older ARM hardware (RPi 1, old Android devices, weird SBCs, IPMI SoCs, etc.).

That's really strange given the rest of the Linux ecosystem used 5tel as there were literally no chips ever that didn't have the "enhanced DSP" option. Pity all this useful information wasn't provided in the commit message, it helps understand reasons for it.

> The armv8 stuff from OpenMandriva is from @berolinux, and he can explain that one better than I could.

Why wasn't there attribution/sign-off by? Could someone provide more details, I want to understand the details of how this would be used. There's users of Debian packages in Fedora and in all the time we've supported aarch64 this was never requested because there's other means of dealing with this.

**Comment by Conan-Kudo** [comment]
> That's really strange given the rest of the Linux ecosystem used 5tel as there were literally no chips ever that didn't have the "enhanced DSP" option. Pity all this useful information wasn't provided in the commit message, it helps understand reasons for it.

That was in my early days of doing this kind of work, I didn't know that I could do more than `git commit -m` yet. Sorry!

> Why wasn't there attribution/sign-off by? Could someone provide more details, I want to understand the details of how this would be used. There's users of Debian packages in Fedora and in all the time we've supported aarch64 this was never requested because there's other means of dealing with this.

I'm pretty sure the armv8 commits were written by him and have his sign-off.

As for the `arm64`/`aarch64` thing, I wrote it after encountering a number of issues at work trying to deal with converting debs to rpms for AArch64 (for reasons I can't go into, unfortunately) as well as having people wanting to use the Debian arch names in spec files (because things like Go, Rust, Docker, etc. have adopted the Debian arch names instead of the RPM or gcc ones) to mean the equivalent RPM ones. Rather than trying to fight it, I just wanted to make it work.

**Comment by nullr0ute** [comment]
I've dropped the patches for armv5tl

**Comment by nullr0ute** [comment]
> As for the `arm64`/`aarch64` thing, I wrote it after encountering a number of issues at work trying to deal with converting debs to rpms for AArch64 (for reasons I can't go into, unfortunately) as well as having people wanting to use the Debian arch names in spec files (because things like Go, Rust, Docker, etc. have adopted the Debian arch names instead of the RPM or gcc ones) to mean the equivalent RPM ones. Rather than trying to fight it, I just wanted to make it work.

These should be included in your own local rpm macros files then

**Comment by pmatilai** [comment]
I'm trying to stay out of this as much as possible, but the arm64 architecture and its reasoning does seem dubious. We do have a similar mess around x86_64 aka amd64 aka ia32e aka emt64t, but those names actually existed in the wild during the early days of the x86 64bit revolution.

I think upstream rpm should never ever *generate* packages with "arm64" as architecture, but having a courtesy compat mapping to it seems mostly harmless. So maybe drop the build side mapping, but leave the other compat mappings in place? That'd be similar to how em64t alias is handled.

Other than that, glad to see progress is being made.

**Comment by pmatilai** [comment]
As for the armv8 variants, the original PR has extensive discussion on the details:
https://github.com/rpm-software-management/rpm/pull/425

My takeaway from that is pretty much that these extra variants are there "just in case" for symmetry with armv7, despite the platform being noted as entirely different and not strictly needing such things. I doubt anybody expected these to *break* things, but as they are...

**Comment by nullr0ute** [comment]
> I think upstream rpm should never ever _generate_ packages with "arm64" as architecture, but having a courtesy compat mapping to it seems mostly harmless. So maybe drop the build side mapping, but leave the other compat mappings in place? That'd be similar to how em64t alias is handled.

This is something we categorically don't want in Fedora, it will create a support nightmare where things that might work in Fedora won't work elsewhere, we have explicitly not added this mapping from out outset of aarch64 for that reason and we really don't want it now. If it's something that an end user wishes to do it should be perfectly doable via a macro in /etc/rpm* or similar (note I've not checked how local user macros are handled).

**Comment by Conan-Kudo** [comment]
> This is something we categorically don't want in Fedora, it will create a support nightmare where things that might work in Fedora won't work elsewhere, we have explicitly not added this mapping from out outset of aarch64 for that reason and we really don't want it now.

I don't agree at all. There is no conceivable reason that this would cause a "support nightmare", given the common acceptance of `arm64` == `aarch64` across tools and operating systems. In doing this, tools like `alien` work out of the box properly for going back and forth between rpm and deb, since there is a mapping for the architecture labels. People who are conventionally used to the other name will get the expected architecture when writing spec files to build packages, and so on.

I'm sorry we don't live in a perfect world where everybody uses rpm and bows to the will of a person on how architectures are named and referenced, but sadly it is necessary to deal with conventions like this.

**Comment by nullr0ute** [comment]
> I don't agree at all. There is no conceivable reason that this would cause a "support nightmare", given the common acceptance of `arm64` == `aarch64` across tools and operating systems. In doing this, tools like `alien` work out of the box properly for going back and forth between rpm and deb, since there is a mapping for the architecture labels. People who are conventionally used to the other name will get the expected architecture when writing spec files to build packages, and so on.

That use can can be handled just as effectively in alien like it does with a whole bunch of architecture translations in Alien/Package/Rpm.pm eg:
<pre>
                elsif ($arch eq 'ppc') {
                        $arch='powerpc';
                }
                elsif ($arch eq 'x86_64') {
                        $arch='amd64';
                }
                elsif ($arch eq 'em64t') {
                        $arch='amd64';
                }
                elsif ($arch =~ m/i\d86/i || $arch =~ m/pentium/i) {
                        # Treat 486, 586, etc, as 386.
                        $arch='i386';
                }
</pre>

**Comment by pmatilai** [comment]
@nullr0ute , let me get this straight: it's the armv8* maps that are actually breaking Fedora, the arm64 is just something you disagree with but isn't breaking anything (at the moment anyway), right?

**Comment by nullr0ute** [comment]
> @nullr0ute , let me get this straight: it's the armv8* maps that are actually breaking Fedora, the arm64 is just something you disagree with but isn't breaking anything (at the moment anyway), right?

Correct, but we do not want to ship the arm64 mapping in a stable release because it is not something we want to have to support long term.

**Comment by pmatilai** [comment]
Ack, thanks for confirming.

As for arm64, the cat is out of the bag though as it has been shipped in a stable rpm release now.

**Comment by pmatilai** [comment]
Eep, hit send too soon.

I still think that at least the ability to build arm64 packages should be removed regardless, I don't see technical justification for that. As for installing... are the actual .arm64 rpm packages in the wild? That's the sole excuse for the alias madness on x86-64 side, and I'd rather avoid repeating that mess unless we absolutely have to. Our arch names are generally based on kernel uname / gcc names, and deviating from those shouldn't be done lightly.

**Comment by dmach** [comment]
I'm also in favor of removing arm64.
Unfortunately as @Conan-Kudo mentioned, we're not living in a perfect world and the value has been in upstream for some time and removing it means a regression.
Couldn't we split the arm64 removal into a separate PR and remove it when we have confirmation that everything works as expected? I don't think that arm64 is related to rhbz#1562084 and needs to go to Fedora 31 as part of the release blocker fix.

**Comment by nullr0ute** [comment]
> As for arm64, the cat is out of the bag though as it has been shipped in a stable rpm release now.

It hasn't shipping in a stable Fedora release though, and while I understand the concerns of upstream maintainers, my concern is primarily for the Fedora/RHEL/CentOS ecosystem.

**Comment by jonmasters** [comment]
Let me be very, very clear:

The name of the 64-bit Arm architecture state in which 64-bit binaries are executed is - and always has been - "aarch64". There was never an "arm64", nor does it exist. The name "arm64" is also an explicit violation of Arm's trademark policy.

When Arm first created the 64-bit Arm architecture, they explicitly and proactively asked that we (and everyone else) use the name "aarch64" to describe it so that it would not contain a trademarked name, and because it was their architecture to name since they invented it in the first place and did the initial enablement work for toolchains and other prerequisite components for bringup.

There were two categories of responses to this polite and reasonable request:

1. Those who listened and collaborated to adopt the name of the architecture
2. Those who did not listen and chose the name "arm64" for other reasons

The name of the architecture is - and always has been - "aarch64". The name "arm64" is not a valid name and it should not be perpetuated simply because some chose to use it instead.

**Comment by Conan-Kudo** [comment]
> There was never an "arm64", nor does it exist. The name "arm64" is also an explicit violation of Arm's trademark policy.
> [...]
> Those who did not listen and chose the name "arm64" for other reasons

I have to respectfully disagree. Aside from compilers, virtually every other ecosystem has mapped the AArch64 ISA to the `arm64` name. The fact that Arm Holdings has not gone after _any_ of them (such as FreeBSD, OpenBSD, Docker, Debian/Ubuntu, Google, etc.) amounts to tacit acceptance of the name, from my perspective.

In fact, people are _more_ likely to call it ARM64 than they are AArch64, simply because the ARM64 name is used everywhere except by ARM itself.

**Comment by jonmasters** [comment]
@Conan-Kudo I understand your perspective. And I agree that "arm64" is widely used. But that usage is unfortunate. The reason that it is NOT used in the Fedora/RHEL/CentOS ecosystem is out of respect for, and as a courtesy to Arm, who requested the original usage of "aarch64".

I'm not trying to rewrite history though. I'm simply trying to explain why the difference exists. There are many other technical reasons why introducing mappings between arm64->aarch64 cause problems in the Fedora/RHEL/CentOS universe.

Thanks.

**Comment by pmatilai** [comment]
Nobody has answered my earlier question, so lets repeat that:

**Are the actual .arm64 rpm packages in the wild?**

If not, then there's zero reason for rpm (and others) to carry the compat crap around, and all the more reason to revert that stuff before it spreads.

**Comment by Conan-Kudo** [comment]
@pmatilai I don't know of any publicly distributed RPMs in this manner yet.

That said, is it possible to make it so that `arm64` causes `aarch64` RPMs to be created? When I wrote https://github.com/rpm-software-management/rpm/commit/236d6f5a2b924266b1249a82875b595e8758c52b, I followed the mapping structure for `amd64` and `x86_64`, but I only intended for it to be that if `arm64` is used in a spec or as inputs, it would produce the correct `aarch64` rpm. Beyond that, I don't particularly care.

**Comment by Conan-Kudo** [comment]
I'm also trying to maintain spec-level compatibility between debbuild and rpmbuild, and supporting accepting `arm64` on both sides helps with that.

**Comment by pmatilai** [comment]
> @pmatilai I don't know of any publicly distributed RPMs in this manner yet.

Okay, lets keep it that way then! We don't want to repeat the alias madness that took place with x86-64 in the early days.

> That said, is it possible to make it so that `arm64` causes `aarch64` RPMs to be created? When I wrote [236d6f5](https://github.com/rpm-software-management/rpm/commit/236d6f5a2b924266b1249a82875b595e8758c52b), I followed the mapping structure for `amd64` and `x86_64`, but I only intended for it to be that if `arm64` is used in a spec or as inputs, it would produce the correct `aarch64` rpm. Beyond that, I don't particularly care.

Translating arm64 into aarch64 if encountered seems like a reasonable compromise to me conceptually. How feasible that is I can't say offhand, it's *ages* since I last touched any rpmrc stuff.

**Comment by nullr0ute** [comment]
> Nobody has answered my earlier question, so lets repeat that:
> 
> **Are the actual .arm64 rpm packages in the wild?**
> 
> If not, then there's zero reason for rpm (and others) to carry the compat crap around, and all the more reason to revert that stuff before it spreads.

None that I'm aware of publicly, which is precisely why I don't want this out in a stable Fedora release because we absolutely don't want to be stuck with supporting this at all.

**Comment by nullr0ute** [comment]
> @pmatilai I don't know of any publicly distributed RPMs in this manner yet.
> 
> That said, is it possible to make it so that `arm64` causes `aarch64` RPMs to be created? When I wrote [236d6f5](https://github.com/rpm-software-management/rpm/commit/236d6f5a2b924266b1249a82875b595e8758c52b), I followed the mapping structure for `amd64` and `x86_64`, but I only intended for it to be that if `arm64` is used in a spec or as inputs, it would produce the correct `aarch64` rpm. Beyond that, I don't particularly care.

So that patch AFAICT won't do that at least from an rpmbuild point of view, if it's used from an alien or related PoV there's translation options in that code base to deal with that use case so the patches should go there not into rpm itself

**Comment by pmatilai** [comment]
@Conan-Kudo , for the reason pointed out above, there can be no "arm64" -> "aarch64" translation in rpm, contrary to what I said earlier about it seeming like a reasonable compromise. 

What I can accept is an "arm64" macro which includes all the 64bit Arm architectures similar in spirit to %power64 and %mips64 but I that probably doesn't help your case because it cannot be used for translating from one thing to another (as it's expected to consist of more than one entry in the future)

**Comment by pmatilai** [comment]
Oh, ugh. Now that I started rebasing rawhide to 4.15.1 I notice Fedora also reverted 8c3a7b8fa92b49a811fe36b60857b12f5d7db8a8 and upstream should've probably done the same because now the detection code can come up with architectures that are not in the rpmrc anymore.

Which means that as far as ARM is concerned, I just released a pile of :hankey:

**Comment by nullr0ute** [comment]
> Oh, ugh. Now that I started rebasing rawhide to 4.15.1 I notice Fedora also reverted [8c3a7b8](https://github.com/rpm-software-management/rpm/commit/8c3a7b8fa92b49a811fe36b60857b12f5d7db8a8) and upstream should've probably done the same because now the detection code can come up with architectures that are not in the rpmrc anymore.
> 
> Which means that as far as ARM is concerned, I just released a pile of hankey

I had put a revert in Fedora, I intend to put a commit the same as in the libdnf PR to ensure the same logic but due to other commitments I'd not got that post F-31 GA. I will endevour to priortise it  in the next few days, can we just add the revert in the short term in Fedora?

**Pull request merged**
