### PR TITLE
Doc Rework

### PR DESCRIPTION
**Pull request by ffesti**
This is an attempt to solve #1666. We have some documentation on https://rpm.org that lives in the `rpm-web` repo and the docs in `doc/manual` that should stay in the sources repo. Currently these are duplicated and can't be kept in sync easily.

These changes re-arange the files so `docs/manual` (sic!) can be rendered as GitHub pages - just as rpm.org. Using the same `_layout` would allow just binding the two GH pages together with links and have them work nearly seamlessly together.

Unfortunately GH pages does not support `doc/` as a location - only `docs` *sigh*
Preview of the result can be seen in the GH pages of my private repository: http://ffesti.github.io/rpm/manual/

I would like to also find a way to have the man pages rendered, too.
We might consider pushing some of these changes out after 4.17 forks away as so many files moving around between alpha and the release is kinda arkward.

### CODE REVIEW

**Comment by ffesti** [comment]
OK, here a preview on how markdown man pages could look like: http://ffesti.github.io/rpm/man/

Still needs some work:
* Add `pandoc` as dependency and though make the test suite pass again.
* Check if both the Markdown and the resulting man pages are OK. This is just piping everything blindly through `pandoc` 
* Put some work into a CSS that suites the man pages better than the current one.

**Comment by ffesti** [comment]
Looks like pandoc has issues with the French and Japanese files. This work for me locally. There are probably still some packages missing in the `ci/Dockerfile. Unfortunately the error messages are all but helpful *sigh*

**Comment by ffesti** [comment]
OK, build is fixed.

**Review by pmatilai — APPROVED** [review]
Rebase and ship it... the longer this lingers, the more conflicts and other issues gather up.

I consider myself fairly old-school, but I can tell you I wont be missing those roff-formatted man-pages a single bit.

**Comment by pmatilai** [comment]
On a related note, having the manual actually rendered someplace nicely highlights how rough, raw and miserably inadequate the content is :sweat_smile:

**Pull request merged**
