### PR TITLE
Don't let macro '%-x' add extra space between flag and argument

### LINKED ISSUE #2454: Macro %-x modifies original flag if argument follows without intervening space
See the following example:
```
$rpm --version
RPM version 4.14.3

$ rpm --define '%foo(b:) %{-b}' --eval '%foo -b2'
-b 2
```
The macro adds a space between flag and argument, which may affect passing to applications as shown by the following example:

```
$ python3 -bb
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
<CTRL-D>
``` 
Passing the option through a rpm macro returns: 
```
$ rpm --define '%foo(b:) python3 %{-b}' --eval '%foo -bb` 
python3 -b b
```
Running the generated command fails: 
```
$`rpm --define '%foo(b:) python3 %{-b}' --eval '%foo -bb'` 
python3: can't open file 'b': [Errno 2] No such file or directory
```

### PR DESCRIPTION
**Pull request by rhabacker**
Fixes #2454, depends on #2449  (the commits from #2449 are included to avoid breaking CI)

### CODE REVIEW

**Comment by pmatilai** [comment]
FWIW, you can build without rpm-sequoia by supplying `-DWITH_INTERNAL_OPENPGP=ON` to cmake.

**Comment by rhabacker** [comment]
> FWIW, you can build without rpm-sequoia by supplying `-DWITH_INTERNAL_OPENPGP=ON` to cmake.

Thanks for this pointer, which I can confirm that it works 

To run the generated `rpmbuild` it looks to be required to install the build and use environment variable `RPM_CONFIGDIR` and  `LD_LIBRARY_PATH` e.g. 
```
cd ~
git clone https://github.com/rpm-software-management/rpm.git
cmake -S rpm -B rpm-build
cmake --build rpm-build
cmake --build rpm-build --target install DESTDIR=$PWD/rpm-install
RPM_CONFIGDIR=$PWD/rpm-install/usr/local/lib/rpm LD_LIBRARY_PATH=$PWD/rpm-install/usr/local/lib64 $PWD/rpm-install/usr/localbin/rpmbuild --define='%foo(b:B:) %{-b}' --eval '%foo -b2 -b a=2 -B4 dsfdfdf'
-b a=2
```

**Comment by rhabacker** [comment]
> This may fix a use-case for you but is likely to break it for several others.

A number of conditions are required for this to cause a problem:
1. in the parameter list of a macro `x:`must be specified.
2. `%-x` is used in the macro in question
3. the calling program supports only `-x<value>` and `-x <value>` is passed and vice versa. 

In the following examples from the list given: 

> /usr/lib/rpm/macros:1407:%__scm_apply_hg(qp:m:)\
> /usr/lib/rpm/macros:1408:%{__hg} import - %{-p:-p%{-p*}} %{-q} -m %{-m*} --user "%{__scm_author}"

This post already contains a workaround for the mentioned problem, as [`git am`](https://linux.die.net/man/1/hg) requires the same syntax as the `patch` command with `-p<n>`. Only the value of `%-p` is used and is thus independent of the passing form.

> /usr/lib/rpm/macros:1427:%__scm_apply_git_am(qp:m:)\
> /usr/lib/rpm/macros:1428:%{__git} am %{-q} %{-p:-p%{-p*}}

This occurrence is also a workaround for the problem mentioned, since [`git am`](https://git-scm.com/docs/git-am#Documentation/git-am.txt--pltngt) requires `-p<n>`. Only the value of `%-p` is used and is thus independent of the passing form.

> /usr/lib/rpm/macros:1433:%{__quilt} import %{-p:-p%{-p*}} %{1} && %{__quilt} push %{-q}

According to https://linux.die.net/man/1/quilt the format is `-p <n>`, but the listed location uses `-p<n>`, so it must work, otherwise it would already be reported as a problem.  Only the value of `%-p` is used and is thus independent of the passing format.

> /usr/lib/rpm/macros:1453: local options = rpm.expand("%{-q} %{-p:-p%{-p*}} %{-m:-m%{-m*}}")\

Only the value of `%-p` is used and is thus independent of the passing form.

**Comment by pmatilai** [comment]
As per the ticket conclusion, sorry but NAK: https://github.com/rpm-software-management/rpm/issues/2454

Apologies for taking so long with this.

**Pull request closed without merging**
