### PR TITLE
Fix case of LIBLZMA_FOUND variable

### PR DESCRIPTION
**Pull request by rphibel**
In pkg_check_modules command, LIBLZMA is all uppercase. So in variable LIBLZMA_FOUND, LIBLZMA should also be all uppercase.

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]
🤦🏾

**Comment by pmatilai** [comment]
I'll take a :facepalm: for that, but another :facepalm: belongs to the fella who named the module itself `FindLibLZMA`.

**Comment by pmatilai** [comment]
But really, a truckload of :facepalm:'s to those who have let all this inconsistency into cmake.

The module is FindLibLZMA, the variables are all uppercase but then the imported target is LibLZMA::LibLZMA. In https://cmake.org/cmake/help/latest/module/FindLibXml2.html the _FOUND variable is miXedCase LibXml2_FOUND but all the others are uppercase. In https://cmake.org/cmake/help/latest/module/FindLibArchive.html it's all mixed-case as per the module name.

**Comment by pmatilai** [comment]
In any *case*, thanks for spotting and the patch!

**Comment by Conan-Kudo** [comment]
We're not using FindLibLZMA in here, though. We use `pkg_check_modules()` and made the variable `LIBLZMA`, so that's why it's `LIBLZMA` and not `LibLZMA`.

**Comment by pmatilai** [comment]
Oh, that too. Let's just agree there are many, many many facepalms involved :laughing:

**Pull request merged**
