### PR TITLE
Standardize on OCI images in test-suite

### PR DESCRIPTION
**Pull request by dmnks**
This replaces per-distro backends (currently only `mktree.fedora`) with a universal OCI-based backend. It's based on the original `mktree.podman` but enhanced to work for native development, too. Related refactorings are included.

See the commit messages for details.

Fixes: #2643

### CODE REVIEW

**Comment by dmnks** [comment]
OK, fixed a few typos and thinkos in the commit messages :smile:

**Comment by pmatilai** [comment]
Hmm. I'm getting a LOT of failures when running this as "make check" locally on F38, before and after doing an 'rm -rf *' of the entire build tree:

>  Subject: [rpm 4.19.90] rpmtests: 5 116 117 149 165 297 298 401 403 404 407 408 413 431 434 435 436 437 438 439 440 442 443 444 445 446 447 448 449 450 451 452 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 failed

Stuff like:
> +++ /srv/rpmtests.dir/at-groups/5/stderr	2023-10-26 07:20:24.427086905 +0000
@@ -0,0 +1,4 @@
+ls: cannot access 'librpm.so.*.*': No such file or directory
+ls: cannot access 'librpmbuild.so.*.*': No such file or directory
+ls: cannot access 'librpmio.so.*.*': No such file or directory
+ls: cannot access 'librpmsign.so.*.*': No such file or directory

> +++ /srv/rpmtests.dir/at-groups/116/stderr	2023-10-26 07:20:26.007099877 +0000
@@ -0,0 +1,3 @@
+bwrap: execvp /usr/lib/rpm/rpmuncompress: No such file or directory
+tar: This does not look like a tar archive
+tar: Exiting with failure status due to previous errors

Hmm okay, that happens when you build with `-DCMAKE_INSTALL_PREFIX=/usr` - I build that way because it allows me to use the devel version as if it was the system rpm. So something here clashes with the idea of placing rpm where the system version was.

Another random observation: mktree.docker seems to be suffering from a minor schizophrenia, because it mostly talks about Podman inside :sweat_smile: Maybe it should be mktree.oci instead?

**Comment by dmnks** [comment]
> Hmm. I'm getting a LOT of failures when running this as "make check" locally on F38, before and after doing an 'rm -rf *' of the entire build tree:

Ugh, I haven't tested the non-default (`/usr/local`) prefix... *This* is why PRs are actually valuable, it seems like :sweat_smile: Of course it *has to* work with any prefix, that was the requirement from the start (and seems like the current Fedora backend does work). I'll have a look, thanks!

> Another random observation: mktree.docker seems to be suffering from a minor schizophrenia, because it mostly talks about Podman inside 😅 Maybe it should be mktree.oci instead?

The symlink really is meant as just a silly "shortcut" for something like (in the CI):

```
USE_DOCKER=1
./mktree.podman ...
```

But I agree, `mktree.oci` was also on my mind, it's perhaps more "correct" as it says "make an OCI-based test tree" (much like e.g. the `mkfs.*` binaries). Let me change it then :smile:

**Comment by dmnks** [comment]
BTW, we could just use Podman in the CI now, too. The Ubuntu version deployed there is recent enough to have Podman in a recent-ish version, too, and is even installed by default.

The only "advantage" (or rather a side effect) of Docker is that it must run with root privileges, in which case we get that one test covered which is normally disabled in unprivileged containers because it needs to create devices (or something like that, don't remember exactly). But we could do the same with Podman, I believe, just running it as root in that VM.

**Comment by dmnks** [comment]
Could you please try a completely new build in a separate build dir? Just to rule out any local build configuration.

**Comment by dmnks** [comment]
Oh, you mentioned you recreated the entire build tree (not just `tests/`), nevermind then... myster deepends :laughing:

**Comment by pmatilai** [comment]
I guess you need to do that 'rm -rf *' of the build tree for the prefix to really take effect - that way I can reliably reproduce the failures.

Looking at the build log makes it kinda obvious what is going on. With a `-DCMAKE_INSTALL_PREFIX=/usr` build, the build inside the image ends up installing to the default prefix:

```
Install the project...
-- Install configuration: ""
-- Installing: //usr/local/share/man/man1/gendiff.1
-- Installing: //usr/local/share/man/man8/rpm2cpio.8
-- Installing: //usr/local/share/man/man8/rpm.8
-- Installing: //usr/local/share/man/man8/rpmbuild.8
```

...but then the build itself is expecting to be in /usr prefix due to the "outside" configuration, and at that point its no wonder it fails.

**Comment by dmnks** [comment]
I actually did precisely that, removed the whole build dir and created it from scratch, and yet, it works :laughing: But, one important difference perhaps is that I did *not* configure anything besides the prefix, i.e:
```
$ mkdir _build
$ cd _build/
$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
$ make check
```

Did you use some other cmake options too?

**Comment by dmnks** [comment]
OK, tried with a couple more config options, namely:
```
export CFLAGS="-Og -g"

cmake \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DENABLE_WERROR=ON \
	-DENABLE_BDB_RO=ON \
	-DWITH_FSVERITY=ON \
	-DWITH_IMAEVM=ON \
	-DWITH_FAPOLICYD=ON \
	-DRPM_VENDOR=redhat \
	$*
```

... and it worked for me, too. Strange, strange...

**Comment by pmatilai** [comment]
Okay with offline debugging with @dmnks , the difference came from me not having `buildah` installed, and cmake reporting
> -- Using mktree backend: podman (native: OFF)

After installing buildah that changes to ON, and the test-suite passes. So the apparent configuration leakage is an issue only in the non-native mode.

**Comment by dmnks** [comment]
Indeed, sorry for not pointing that (new requirement) out in the beginning, somehow that didn't even cross my mind :smile: 

I can now reproduce this in non-native mode with a different prefix. Something is leaking into the image even if it shouldn't. Will fix.

Meanwhile, I'm thinking if we shouldn't just use Podman to apply the RPM layer on top of the base layer, instead of Buildah. Podman allows that too, just needs one extra step or so.

**Comment by pmatilai** [comment]
In general, less build dependencies is better but only if skipping buildah is truly trivial. I don't want us to sink yet more time into *that*.

**Comment by dmnks** [comment]
Yup, I'll see if it can be done with Podman just as easily and go from there.

**Comment by dmnks** [comment]
Just FTR, culprit found, it's because the `rpmtests.sh` wrapper runs `rpmtests` from the local build directory if it exists, even in non-native mode. Working on a fix now.

**Comment by dmnks** [comment]
Fixed version pushed:

* Don't build local test files if we're in non-native mode (this fixes the above issue)
* Drop the Buildah dependency (was trivial in the end)
* Rename to `mktree.oci`
* Remove the confusing `mktree.docker` symlink, use an env var instead
* Minor fixups that I've found along the way

**Comment by pmatilai** [comment]
Works for me :+1:

**Pull request merged**
