### PR TITLE
Allow signing with ECDSA keys

### PR DESCRIPTION
**Pull request by mlschroe**
Key import and verification already works, it's just that rpm does not know where to put the signature.

### CODE REVIEW

**Comment by mlschroe** [comment]
See also 23770e1a4f28c56a31fe600cae332c77333b60b6

**Comment by pmatilai** [comment]
Clearly it's Monday - took me a few moments to see the difference to https://github.com/rpm-software-management/rpm/commit/23770e1a4f28c56a31fe600cae332c77333b60b6 :sweat_smile: 

I'd be wary of adding any default rule there but clearly ECDSA belongs to DSA as much as EDDSA does, no objection on that.

These things should have tests, really. Care to add some, or should I just add a ticket to remind us to add one of these days?

**Comment by mlschroe** [comment]
I can add both an ed25519 and an nist p-256 key test.

**Comment by mlschroe** [comment]
Ok, done.

**Comment by pmatilai** [comment]
Excellent, thanks!

**Pull request merged**
