### PR TITLE
Add macro '%-x**' containing all occurrences of the flag '-x'

### LINKED ISSUE #546: RFE: access to multivalued flags
many commands nowadays accept multiple instances of the same flag (for example dnf can take several -x flags with different values)

when you write a macro that calls such a command you want to use the same syntax and have  %{?-x} output all the -x flags 

unfortunately rpm "helpfully" shortens %{?-x} to just the last one

since changing this would probably break compatibility somewhere, please add a %{?-x**} shorthand meaning all the -x flags with their values

### PR DESCRIPTION
**Pull request by rhabacker**
Fix #546

### CODE REVIEW

**Comment by rhabacker** [comment]
This pull request required several push forces because the master branch of rpm on openSUSE 15.4 could not be built due to the missing package rpm-sequoia. The patch was therefore developed on rpm-4.14.x and ported to the master branch.

**Comment by rhabacker** [comment]
> depends on #2455

Dropped that dependency.

**Comment by rhabacker** [comment]
Is there anything else that would block the merge? I need this feature to fix a problem I am having on https://build.opensuse.org/project/show/windows:mingw:win32.

**Comment by rhabacker** [comment]
> Is there anything else that would block the merge? I need this feature to fix a problem I am having on https://build.opensuse.org/project/show/windows:mingw:win32.

The dbus project has reported a problem in this regard on https://gitlab.freedesktop.org/dbus/dbus/-/issues/455 for which this support is required, since the associated macro mingwxx-cmake must be adapted to filter out all occurrences of -Dxxx and --xxx together with -B and -S.  

Alternatively, this functionality would have to be (re)implemented as a lua macro, which in my opinion is a waste of time, since there is already a solution with this merge request.

**Comment by DemiMarie** [comment]
@pmatilai what about quoting each argument separately, or making them available as a Lua array?  IMO any macro this complex should probably be written in Lua.

**Comment by rhabacker** [comment]
> @pmatilai what about quoting each argument separately, 

I checked how quotes in strings are handled correctly with the changes from this pull request:

    $ ../rpm-build/rpm --define '%foo(D:) %{-D**}' --eval '%foo -D11  -D 22 -D"33" -D"44 55" -D "66 77"    argument'
     -D11 -D 22 -D"33" -D"44 -D "66

The result is that the parameter `-D"44 55"` and `-D "66 77"` are not recognized correctly.

But the same issue also happens with the present macros related to returning flags and/or values 

    $ ../rpm-build/rpm --define '%foo(D:) %{-D}' --eval '%foo -D"44 55"   argument'
    -D"44

    ../rpm-build/rpm --define '%foo(D:) %{-D*}' --eval '%foo -D "44 55"   argument'
    "44

so there is no difference here.

**Comment by rhabacker** [comment]
> ...  The conclusion is that something similar must be done before calling getopt in rpm to process macro parameters with quotes.

There is already a function named [`splitQuoted()`](https://github.com/rpm-software-management/rpm/blob/51c596a6c893824d459ddc6ac28ea28e9f391bd4/rpmio/macro.c#L963), which splits the arguments, currently only separated by space and tabs.

It looks like a candidate for processing quotes.

**Comment by ferdnyc** [comment]
@rhabacker 

> shows that the quoting is done by the shell and not by getopt itself. The conclusion is that something similar must be done before calling getopt in rpm to process macro parameters with quotes.

Isn't that `%quote`, like @pmatilai mentioned? Going back to your experiments (braces added to output for clarity):

```console
$ rpm --define '%foo(D:) [%{-D}]' --eval '%foo -D%{quote:44 55} argument' 
[-D 44 55]
$ rpm --define '%foo(D:) [%{-D*}]' --eval '%foo -D%{quote:44 55} argument'
[44 55]

**Comment by mlschroe** [comment]
With the new ME_QUOTED support added end of last year we could make this work correctly. So the question is if we want `%-x**` or not.

**Comment by mlschroe** [comment]
I don't think %-x** should repeat the option name, though. It should just be the arguments, i.e. just like %-x* but with multiple values.

**Comment by pmatilai** [comment]
Like I said before, I'm not convinced this is the way we want to represent the multivalue case.

Assuming we can technically do this now, is there a reason not to put those values into the normal -x* macro? It seems to me we can't really break any significant existing users as we just haven't supported multiple flags before, so macros can't have been using them much. 

And, I concur with @DemiMarie here - I tend to think this would be better left to Lua where an array of values can be properly dealt with.

**Comment by mlschroe** [comment]
Historically it has always been just the last occurrence, so I don't think we can change this.

Regarding the array of values part: we now can deal properly with it because of ME_QUOTED.  But I'm fine if the functionality is only available to lua (but it currently is not).

**Comment by mlschroe** [comment]
(We might be able to change the behavior of %-f so that it includes all occurrences, but even that makes me a bit uneasy.)

**Comment by pmatilai** [comment]
I know its that way historically, just doubtful of people actually relying on multivalues being handled that way. But then, I wouldn't know.

Yet another possibility could be letting macros declare the way they want their arguments, ie "I can handle multiple values, bring em on", just like we have a way to disable all pre-processing.

**Comment by pmatilai** [comment]
Just realized %{-f} and %{-f*} explictly documented as being the last occurence. So yep, we can't change that.

**Comment by mlschroe** [comment]
But the change that documented it was commit a5bd7571358c7974da1c909e331525b13dce1264 by Ralf done March 2023....

**Comment by pmatilai** [comment]
Actually, there is a kind of a way to access the values from Lua even now.

%-f* macro has the last definition of the macro. If you pop (ie undefine) it, you get the one underneath. And with that, you can walk all the values. It wont work on normal macros as "%undefine -f*" is not permitted, but rpm.undefine() in Lua bypasses that check.

Not that this is something I'd recommend for use.

**Comment by ferdnyc** [comment]
> With the new ME_QUOTED support added end of last year we could make this work correctly. So the question is if we want `%-x**` or not.

Speaking of `ME_QUOTED`: On a somewhat related note, am I doing something wrong or does `%{quote}` seem to not play nicely with `%{**}`?

```console
$ rpm --define '%foo(D:) %{**}' --eval '%foo -D"33 44"  argument' 
-D"33 44" argument

$ rpm --define '%foo(D:) %{**}' --eval '%foo -D%{quote:33 44}  argument'
-D33 44 argument
```

**Comment by mlschroe** [comment]
That looks like the correct output to me. Why do you think it doesn't work? Note that %quote does not add any quotes, the effect is purely internal. Here's how to make it visible:
```
$ rpm --define '%foo(D:) %{shescape %{**}}' --eval '%foo -D"33 44"  argument' 
'-D"33' '44"' 'argument'
$ rpm --define '%foo(D:) %{shescape %{**}}' --eval '%foo -D%{quote:33 44}  argument'
'-D33 44' 'argument'
```

**Comment by pmatilai** [comment]
I'll note that this is *a* solution to a problem that still stands, but it still doesn't feel any more like the *right* solution after 1.5 years.

Thanks for the PR though, perhaps this will inspire another solution that does feel right. In the meanwhile though, I agree with @DemiMarie and others that macros of this complexity are best dealt with in Lua. I'd rather just make the multiple options more accessible there.

**Pull request closed without merging**
