### PR TITLE
ndb: add verify method and cleanup code

### PR DESCRIPTION
**Pull request by mlschroe**
This commit adds a verify method for ndb's Packages.db database.
It also cleans up the pkgdb code a bit:

* removed unused lzo compression code
* added some more comments and fixed spelling mistakes
* made "ordered slots" flag a boolean
* fixed a corner case where a package id lookup could segfault
  if no packages were in the database
* no longer free the pkgid hash all the time

### CODE REVIEW

**Comment by pmatilai** [comment]
Please split to individual commits.

**Comment by mlschroe** [comment]
I kind of fail to see the point, but I'll do it anyways just to please you.

**Comment by pmatilai** [comment]
These are essentially unrelated changes, hence they belong to separate commits. It might not seem that valuable to the author, but it makes reviewing much easier, and the biggest value of strict commit-per-logical-change comes over time from bisecting, cherry-picking etc. 

Lumping such changes into one pull-request is absolutely fine of course.

**Comment by mlschroe** [comment]
I get that, but I was under the impression that ndb is still marked as experimental. (That's about to change in the near future, though.)

Anyway, force pushed to multiple commits.

**Comment by pmatilai** [comment]
Oh, I don't see experimental status affecting change-per-commit requirement at all, as the commits will remain forever regardless of the status. Various other aspects can be somewhat relaxed on experimental code of course.

Anyway, splitting up much appreciated, thanks.

**Pull request merged**
