### PR TITLE
Add support for "pinned" tests

### PR DESCRIPTION
**Pull request by dmnks**
Whenever we bump the RPM version in cmake, certain tests also need updating, e.g. those that compare package digests or RPM sonames as those are subject to the version number.

Up until now, this had to be done manually by running the test-suite, looking at the failed tests' diffs and fixing up the expected outputs by hand.

No more!  Separate those tests and add the "make pinned" cmake target to update them automatically.  This makes use of the new-ish atshell feature which runs a shell/command (*.sh scripts in tests/pinned/ in this case) in the standard test environment in order to get the new outputs.

See the included README for more details.

### CODE REVIEW

**Comment by dmnks** [comment]
Yup, I knew the "static" name probably wasn't great because of what you said but also because those tests aren't really "static" any more than the normal tests, actually quite the opposite :smile: 

For some reason, "pinned" doesn't sound very descriptive either, though. And "check-pinned" even less so... Also, in that case we should probably move all the test-related targets to the "check-" prefix (which gets unwieldy pretty quickly :smile: ).

But "static" is a no-go, I agree. I'll give it a quick thought and do a fixup. Thanks!

**Comment by pmatilai** [comment]
Pinned is not really descriptive but at least it wont be confused with something else in the build system domain. But yup, perhaps we can come up with something actually descriptive. Names are hard :laughing:

**Comment by pmatilai** [comment]
For other random ideas, perhaps something better would be in the direction of what it actually does, eg "version-diff", or what it relates to: preparing for release (release-prep) or such.

**Comment by dmnks** [comment]
"version-diff" indeed is perhaps closer to what it does, however it just happens that these tests depend on the version. There might as well be other tests (in the future) that depend on some other baked-in value.

"release-prep" is similarly too generic because this really is just about the tests, not necessarily about an imminent release (e.g. we need to "pin" these tests even if we bump the micro version to .99 on master). But yup, I was too thinking of having a "release" target that would automate some of the release prep work, in which case this target would be made a dependency of it.

Other ideas:
* rebase-tests
* reproducible-tests (as this is the topic of the signature-verification test)

**Comment by dmnks** [comment]
The idea behind this kind of tests is basically this: We need to *track* the expected output in the repository so that we ensure it's always the same when running the given test, which is why don't just dynamically determine the expected output at test-runtime. At the same time, we need this output to be easily regenerated based on the current repo content.

**Comment by dmnks** [comment]
... which makes me think about another target name: update-tests :smile:

**Comment by dmnks** [comment]
And perhaps, if we were to put all the test-related targets behind the "check-" prefix, then "check-update" perhaps...

**Comment by dmnks** [comment]
Oh! That's a pretty good idea! :smile: 

... except that "mutable" is already used in the test context. But - that doesn't matter much, I suppose. It's a lower-level detail that's relevant when *writing* a test. Otherwise, "mutable" is indeed the best fit.

So, let's just go with that.

**Comment by pmatilai** [comment]
Yeah, mutable and immutable are generic concepts and used in multiple places already. So if you really want to pinpoint it, "update-mutable-tests" :smile:

**Comment by dmnks** [comment]
OK, in the end I went with simply `pinned`. When I was updating the commit, it became apparent "mutable" just didn't fit well in the context, and also clashed with the other meaning I'd mentioned...

**Comment by dmnks** [comment]
I also updated the README to make it a bit more clear.

**Comment by pmatilai** [comment]
Three weeks should be enough think-time for this and since I didn't come up with anything...

**Pull request merged**
