### PR TITLE
Implement a database cookie API for determining whether rpmdb has cha…

### PR DESCRIPTION
**Pull request by pmatilai**
…nged

Add rpmdbCookie() public function and matching python bindings.
The returned value is an opaque string which changes any time the rpmdb
is changed (eg packages added or removed, rebuild changes things etc).
A key point is that this is entirely database backend agnostic.

The actual implementation here is an SHA1 hash of RPMDBI_NAME keys and
the corresponding package offsets, but this is an implementation detail
that can be changed anytime and callers must not rely on. The only thing
that matters is whether the string equals an earlier cookie value or not.
A cryptographic hash seems like an overkill, but then it saves us the
headaches of coming up with something that reflects order changes etc.

Closes: #388

### CODE REVIEW

**Comment by mlschroe** [comment]
This assumes that the iterator always returns the entries in the same order, which might not be true for some db implementations (randomization as a security feature). But feel free to ignore this for now ;)

**Comment by pmatilai** [comment]
We can always have an optional per-db cookie implementation if it becomes necessary. It's not like the cookie needs to be consistent across different implementations, it's merely handy if it can be implemented that way.

In the meanwhile, I realized this version is quite flawed as it just hashes the names without considering how many of them there might be. I guess this really needs to look at both the keys and the data of an index and hash it all to really account for rpmdb rebuilds and the like. (the flaw comes from initially thinking in terms of main package db which of course is quite different)

**Comment by pmatilai** [comment]
Pushed an update which hashes the package offsets per each key as is necessary for correct operation in various cases - add test for that too.

**Comment by pmatilai** [comment]
Pushed an update to make rpmdbIndexIteratorPkgOffsets() const correct while at it.

**Pull request merged**
