### PR TITLE
Add comments for SHA-2 file digest variants

### PR DESCRIPTION
**Pull request by tyll**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
I don't see anything wrong with this, but is `11` really SHA-224? That seems worse than `10`...

**Comment by tyll** [comment]
According to the code `11` is SHA-224: https://github.com/tyll/rpm/blob/744fe3b1043ecd5e0854a535489435a2fe8ad027/rpmio/rpmpgp.h#L268

It seems to be there for cosmetic reasons according to:
https://bugzilla.redhat.com/show_bug.cgi?id=608599
https://github.com/tyll/rpm/commit/20cfa7d2b4c927798ad38126821d194fafd93ffe

**Comment by pmatilai** [comment]
The defining document for these values is rfc-4880:
https://tools.ietf.org/html/rfc4880#section-9.4

The comments in rpmpgp.h date back to (and are copy-pasted from) the now obsolete RFC-2440, might be more productive to actually delete it all and just provide a link to RFC-4880 instead. A header file is not really the place to document the entire protocol, especially as rpm implements only a tiny fraction of it all.

**Comment by n3npq** [comment]
RFC 4880 changes too slowly to add new algorithms. Tracking GNUPG is likely faster/saner.

FWIW, AFAIK (I wouldn't have added to the "official" OpenPGP space if not so) gnupg has assigned 11 to SHA224:
`rpmiotypes.h:    PGPHASHALGO_SHA224		= 11,	/*!< SHA-224 */`

**Comment by n3npq** [comment]
Checking libgcrypt-1.7.6 ... yes 11 is the GnuPG assignment.

`$ find . -type f -exec grep SHA224 {} \;
	* gcrypt.h (GCRY_MD_SHA224): Change value from 306 to 11 to match
	* gcrypt.h: Add GCRY_MD_SHA224.
    GCRY_MD_SHA224  = 11,
`

**Comment by tyll** [comment]
I am fine with changing this to just mention the RFC 4880 instead. Btw. initially I got to this code because I wanted to figure out the meaning of the `filedigestalgo` RPM header field in the python code, i.e.:
`import rpm; rpm.TransactionSet().dbMatch().next()["filedigestalgo"]`

Is there a place where the python module is documented where I could add an reference to this as well (if it is missing).

**Comment by pmatilai** [comment]
There's no good place anywhere in rpm to document the meaning of individual tags I'm afraid. I was about to say you should use the rpm.files/fi APIs instead of tag values for file information but seems retrieving the digest algo is not supported, sigh...

Anyway, much easier to merge than argue, thanks for the patch.

**Pull request merged**
