### PR TITLE
Add tests for multiple file trigger prefixes

### PR DESCRIPTION
**Pull request by dmnks**
Funnily enough, we never tested multiple prefixes.  No wonder there were some bugs lurking in the dark corners (see #3048 and #3267)!

- Add yet another test spec for triggers! (There's never enough of them)
- Have the scripts print the prefix(es) that triggered them
- Add an unused /etc prefix to test just that - an unused prefix
- Shuffle the prefixes randomly in some scripts, to make it more interesting (and to verify that the order doesn't affect anything)
- Rename the existing "basic file triggers 2" to make it better reflect its main goal (which is "runtime arguments") and to make it more consistent with the newly added one

### CODE REVIEW

**Comment by dmnks** [comment]
Note that this now expectedly fails in the CI, it's supposed to go with #3267.

**Comment by dmnks** [comment]
I've realized we were missing a similar test for regular triggers... so I've added one for those, too.

**Comment by pmatilai** [comment]
You can mark these with AT_XFAIL_IF so they show up as expected failures and then my PR can just drop that.

**Comment by dmnks** [comment]
> You can mark these with AT_XFAIL_IF so they show up as expected failures and then my PR can just drop that.

Done.

**Comment by pmatilai** [comment]
Yay, more tests :grin:

**Pull request merged**
