### PR TITLE
Implement --json query format

### PR DESCRIPTION
**Pull request by pmatilai**
The existing --xml output is extremely useful when inspecting oddities but the format is such an eyesore. JSON is much saner to look at.

Details in the commits and their messages, but the first commits are just refactoring to make this feasible. The actual feature in the last commit is quite small, as often happens the tests are bigger than the actual patch.

### CODE REVIEW

**Comment by mlschroe** [comment]
Seems like it's missing escaping of weird characters like everything < 0x20 (most important`\n`), the `\` and the `"` characters.

**Comment by pmatilai** [comment]
Oh, indeed. It's just the kind of dumb luck to miss such characters in the test-material you try to reparse for validation :sweat_smile: The newlines in base64Format() was trying to ring some bells but was too busy hacking the rest of it up.

**Comment by pmatilai** [comment]
There you go, that hopefully covers it. Annoyingly this also easily doubles the patch size, as these things always do. 

Also all this string appending is of course all horribly inefficient, but that can be improved later.

**Comment by mlschroe** [comment]
Your `\r` escaping has a typo: it uses \t instead of \r.

**Comment by mlschroe** [comment]
Aaand, if `c` is signed, doesn't the < 0x20 break utf8?

**Comment by pmatilai** [comment]
All your remarks should be covered now, just squashed the fixups in the last push.

Oh and thanks for the review! I'm not friends with escapes so I conveniently tend to forget all about them. My main motivation with this one was human consumption more than computer, but of course if we claim it's json then it should be valid json...

**Review by mlschroe — APPROVED** [review]

**Pull request merged**
