### PR TITLE
rpmsign: support EdDSA signatures

### PR DESCRIPTION
**Pull request by DemiMarie**
They were previously rejected

### CODE REVIEW

**Comment by pmatilai** [comment]
It certainly is not an RSA signature. See the discussion in #1202 and related.
As the multiple signature support work hasn't progressed anywhere (and it wont anytime soon), perhaps we should consider just reusing the DSA tag for this afterall. I guess that's what @mlschroe originally had in mind?

**Comment by DemiMarie** [comment]
> It certainly is not an RSA signature. See the discussion in #1202 and related.
> As the multiple signature support work hasn't progressed anywhere (and it wont anytime soon), perhaps we should consider just reusing the DSA tag for this afterall. I guess that's what @mlschroe originally had in mind?

I don’t particularly care which tag is used, so long as it works.  Can we eliminate the distinction in RPMv6?

**Comment by pmatilai** [comment]
Seems like a revised version of #1500 accidentally ended up in this PR. No matter, I far prefer this version and splitting this to yet more PR's wouldn't actually help anything. Also, @mlschroe seems to be busy but he did indicate the preference for existing tags in #1202 so...

Thanks for the patches!

**Comment by Conan-Kudo** [comment]
> I don’t particularly care which tag is used, so long as it works. Can we eliminate the distinction in RPMv6?

We'd need _some_ way to tell what keys are what type, but there are certainly better ways to do it. Ideally, RPMv6 would also include fixing support for multiple signatures.

**Pull request merged**
