### PR TITLE
RPM 4.19.1.1 bugfix update

### PR DESCRIPTION
**Pull request by dmnks**
This is a small bugfix-only update addressing a number of regressions and other, mostly build-related issues. A changelog preview follows:

#### Fixes
* *Packaging:* Don't warn about missing user/group on skipped files <sup>Regression</sup> ([#2814](https://github.com/rpm-software-management/rpm/pull/2814))
* *Packaging:* Make user/group lookup caching thread-safe <sup>Regression</sup> ([#2843](https://github.com/rpm-software-management/rpm/pull/2843))
* *Lua interface:* Fix regression in Lua scriptlet runaway child detection <sup>Regression</sup> ([#2818](https://github.com/rpm-software-management/rpm/pull/2818))
* *Build:* CMakeLists.txt: restore readline support as an explicit option <sup>Regression</sup> ([#2852](https://github.com/rpm-software-management/rpm/pull/2852))
* *Build:* Fix unconditional uses of Linux-specific extensions <sup>Regression</sup> ([#2812](https://github.com/rpm-software-management/rpm/pull/2812))
* *Build:* Add missing include for check_symbol_exists ([#2831](https://github.com/rpm-software-management/rpm/pull/2831))
* *Build:* Don't use _nl_msg_cat_cntr if it's not available ([#2856](https://github.com/rpm-software-management/rpm/pull/2856))

Resolves: #2878

### CODE REVIEW

**Comment by pmatilai** [comment]
There are a few memleak fixes + maybe the unsigned buildtime thing that might be worth considering too. Although, there's always the next release, so up to you.

**Comment by dmnks** [comment]
> There are a few memleak fixes

Oh, you mean (some commits from) #2879. Indeed, I somehow ignored this whole PR due to it starting with "Add support for ..." :smile: I'll look at those patches and see if cherry picking at least some of them would make sense, thanks.

> + maybe the unsigned buildtime thing that might be worth considering too.

If you mean commit 97aa64d8281974fb369c66d5aef8650515b89c52, that one is included in this PR. Or was there some other patch, too?

> Although, there's always the next release, so up to you.

Agreed in general. These micro-micro releases are supposed to be rather small so that we can produce them more often.

**Comment by dmnks** [comment]
> I confirmed that this still builds on macOS, using [these commands](https://github.com/rpm-software-management/rpm/issues/2807#issuecomment-1877296382)–the only difference being that I added `readline` to `PKG_CONFIG_PATH` like this:
> 
> `PKG_CONFIG_PATH=/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig`
> 
> So this looks great to me 👍

Sounds good, thanks for checking!

**Comment by pmatilai** [comment]
> > There are a few memleak fixes
> 
> Oh, you mean (some commits from) #2879. Indeed, I somehow ignored this whole PR due to it starting with "Add support for ..." 😄 I'll look at those patches and see if cherry picking at least some of them would make sense, thanks.

Yup, those. OTOH you could just as well pick the entire PR because the "add support" is only a developer/CI feature - one could argue memory leaks + the like are *more* important for stable releases than development ones.

> > * maybe the unsigned buildtime thing that might be worth considering too.
> 
> If you mean commit [97aa64d](https://github.com/rpm-software-management/rpm/commit/97aa64d8281974fb369c66d5aef8650515b89c52), that one is included in this PR. Or was there some other patch, too?

Oh, ack, just missed that (was looking at the highlights more than actual commits it seems :sweat_smile: (

> 
> > Although, there's always the next release, so up to you.
> 
> Agreed in general. These micro-micro releases are supposed to be rather small so that we can produce them more often.

:+1:

**Pull request merged**
