### PR TITLE
Add --generate-subpackages to find_lang.sh

### PR DESCRIPTION
**Pull request by ffesti**
Use the new dynamic spec feature to create language sub packages.

The is more of a RFC as there are a few things that need more polishing. The code for getting the language description is a bit ad-hoc and may need to switch to another entry in `locale` data. Suggestions welcome.

The package declaration should probably also move into a macro. Probably to the point where the spec parts are only one macro with the right parameters

### CODE REVIEW

**Comment by ffesti** [comment]
Moved package template into `macros.in`. Modeled the sub packages on https://fedoraproject.org/wiki/Packaging:Langpacks but I am interested to hear what other distributions use or would prefer.

**Comment by pmatilai** [comment]
FWIW, I haven't looked at this in any great detail (find_lang.sh is something I try to steer clear of whenever I can) but seems okay to me. But no comments from other distros at all?

Let's try tagging a few people, including from #1276 which this AFAICS fixes. @sdp5, @lnussel, @Conan-Kudo,  @mlschroe (and feel free to add more)

**Comment by sdp5** [comment]
@juhp

**Comment by sdp5** [comment]
As mentioned [here](https://github.com/rpm-software-management/rpm/pull/1485#issuecomment-789710406), such groupings can be seen in flatpak.

**Review by pmatilai — APPROVED** [review]

**Comment by ffesti** [comment]
Now only generates one sub package per language  (2 or 3 letter code) instead of for each locale (LL_CC). Adjusted the test case to check for that by using `de_DE` as example.

**Pull request merged**
