### PR TITLE
RPM 4.18.2 bugfix update

### PR DESCRIPTION
**Pull request by dmnks**
This is a bugfix update with a few small enhancements on top. Let me know if I've missed your favorite patch.

Fixes: #2710

### CODE REVIEW

**Comment by dmnks** [comment]
@ffesti I was wondering about ced4d24f0. Does it have any uses outside the Dynamic spec feature?

**Review by pmatilai — APPROVED** [review]
Just FWIW, looks fine to me.

**Comment by dmnks** [comment]
Forced pushed to move the backported GH actions commit to its proper chronological place (as per the master branch).

**Comment by pmatilai** [comment]
Hey, sorry for the last-minute request but something I ran into just now: please include 37b963fa51d6ad31086a6e345ce6701afda5afff (and why not the rest of the rpm2archive fixes too).
This is actually in preparation for v6 where rpm2cpio as we know it no longer works, so we need to start nudging people towards rpm2archive. And to do that, we need to have it working similarly to the rather well known rpm2cpio.

**Comment by dmnks** [comment]
Oh, sure. And commit bb1eeb4 as well. Not too late; just in time :smile:

**Comment by pmatilai** [comment]
Seems we have some more last-minute candidates :innocent: 
https://github.com/rpm-software-management/rpm/pull/2759 and https://github.com/rpm-software-management/rpm/pull/2758/commits/6773676e2e62e35d347c54f2f15e8f0354e4893b

**Comment by dmnks** [comment]
Friday is the perfect release day :smile:

**Comment by dmnks** [comment]
Added the following commits:

* 37b963fa5 Allow piping from rpm2archive
* 5e22e0c58 rpm2archive: Properly parse popt options
* 7feccb696 rpm2archive: Don't print usage on no arguments
* 37ec18d86 Fix silent wait when missing input RPM package
* f8b4c99bd Properly document our different macro types and their scopes
* e85a8a636 Document rpmdb --exportdb and --importdb switches + minor other tweaks
* 173b737f4 Expose and document rpmdb --verifydb operation
* bb1eeb491 Allow SOURCE_DATE_EPOCH=0 again
* 4d219ed46 Switch brp-compress to bash
* e3ab8a987 Split the dependency generation test into individual checks
* 7d3d9041a Fix sbit removal if fchmodat() doesn't support AT_SYMLINK_NOFOLLOW
* f6b47609a Document rpm2cpio as obsolete, add pointer to rpm2archive.

**Comment by dmnks** [comment]
One last update:

Added adafe8d04 to avoid spurious test backports and moved the "Prepare for release ..." commit to the top.

**Pull request merged**
