### PR TITLE
Do not fail if there is no "$temp"/res.* file

### PR DESCRIPTION
**Pull request by ggardet**

### CODE REVIEW

**Comment by pmatilai** [comment]
The all-important question "why?" is unaswered in the commit message.

What's the scenario where this happens? I'm not that familiar with the debuginfo stuff, but on the outset it looks like something failed if no res.* files were created...

**Comment by bugfinder** [comment]
okay, to the why...
so find-debuginfo fires up multiple threads to split off debuginfo using the run_job function. rpm runs scripts usually with "-e",
so aborts subscripts on error. now if for some reason the debug-splitting tool fails, that job will abort.

Now if you have 8 files that are problematic in the tree, and you have 8 or less jobs, the find-debuginfo will abort as no single
res.$number has been written. If you happen to have more than 8 jobs, the build will succeed, which makes the whole process
somewhat random.

If you really want to abort on encountering errors in the debug split, this would need to be done differently, but here this is just
to get some consistency, regardless on the number of jobs used,

I hope that scheds some light on the idea behind the patch.

**Comment by pmatilai** [comment]
Ok. Just put that rationale into the commit message and I'm fine with it.

**Comment by ggardet** [comment]
Updated the commit message.

**Comment by ggardet** [comment]
@pmatilai Is it ok for you now?

**Comment by pmatilai** [comment]
Sorry, managed to forget this whole thing. Yeah much better now, thanks!

**Pull request merged**
