### PR TITLE
set a %_specfile macro during build, holding full path to spec file

### PR DESCRIPTION
**Pull request by proyvind**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
what is your use-case?

**Comment by proyvind** [comment]
https://github.com/proyvind/rpm/blob/pyspec/python/rpm/generate.py

I'm using it in the python module spec generator (dependent on rpminterp PR, pyspec branch depends on _specfile which is why a new branch were created), where the python script reads the spec file to determine what sections etc. that is defined in the spec or not.

This allows for overriding defaults from the generated spec easily as a regular spec without having to pass extra arguments to the pyspec() function generating the spec.

Default pyspec() example:
$ cat ~/rpmbuild/SPECS/python-pyliblzma.spec 
%{python:pyspec("pyliblzma")}

$ rpmspec -P ~/rpmbuild/SPECS/python-pyliblzma.spec 
Name:           python-pyliblzma
Version:        0.5.3
Release:        1
Summary:        Python bindings for liblzma
Source0:        https://pypi.python.org/packages/17/48/5292ade507dafe573360560ba53783395587dc42eb32b347feb2ac70fc6b/pyliblzma-0.5.3.tar.bz2
License:        LGPLv3
Group:          Development/Python
Url:            https://launchpad.net/pyliblzma
BuildRequires:  pkgconfig(python-2.7) python-setuptools

%description
PylibLZMA provides a python interface for the liblzma library.
        to read and write data that has been compressed or can be decompressed
        by Lasse Collin's xz / lzma utils.

%prep
%setup -qDTn pyliblzma-0.5.3

%build
CFLAGS='-O2 -g' python2 setup.py  build --executable='python2 -s'

%install
CFLAGS='-O2 -g' python2 setup.py  install -O1 --skip-build --root /home/peroyvind/rpmbuild/BUILDROOT/python-pyliblzma-0.5.3-1.x86_64

%check
python2 setup.py test

%files
%doc COPYING
%doc NEWS
%doc THANKS
/usr/lib64/python2.7/site-packages/liblzma.py*
/usr/lib64/python2.7/site-packages/lzma.so
/usr/lib64/python2.7/site-packages/pyliblzma*.egg-info

Example with custom sections:
cat ~/rpmbuild/SPECS/python-pyliblzma.spec 
Patch0: somepatch.patch
Version: 0.5.2
Release: 2

%{python:pyspec("pyliblzma")}


%build
whoopidoopidoo

%install
somestufff

%check
someotherstuff

$ rpmspec -P ~/rpmbuild/SPECS/python-pyliblzma.spec
Patch0: somepatch.patch
Version: 0.5.2
Release: 2

Name:           python-pyliblzma
Summary:        Python bindings for liblzma
Source0:        https://pypi.python.org/packages/79/d7/2ca6de56df030a6be411b664e48cee3a3feaf1312bfa9556fd9abab4dcd1/pyliblzma-0.5.2.tar.bz2
License:        LGPLv3
Group:          Development/Python
Url:            https://launchpad.net/pyliblzma
BuildRequires:  pkgconfig(python-2.7) python-setuptools

%description
PylibLZMA provides a python interface for the liblzma library.
        to read and write data that has been compressed or can be decompressed
        by Lasse Collin's xz / lzma utils.

%prep
%setup -qDTn pyliblzma-0.5.2
/bin/cat /home/peroyvind/rpmbuild/SOURCES/somepatch.patch | 
/bin/patch -p1 -s --fuzz=0 -s -U

%files
%doc COPYING
%doc NEWS
%doc THANKS
/usr/lib64/python2.7/site-packages/liblzma.py*
/usr/lib64/python2.7/site-packages/lzma.so
/usr/lib64/python2.7/site-packages/pyliblzma*.egg-info


%build
whoopidoopidoo

%install
somestufff

%check
someotherstuff

**Comment by pmatilai** [comment]
Nope, I don't like it any more than the last time around, and I don't see anything here that would change my mind - "without having to pass extra arguments" doesn't sound like a very convincing argument.

**Comment by proyvind** [comment]
then you don't seem to figure out what I'm trying to describe my needs for.

What I demonstated was how through the embedding of python interpreter through the rpminterp PR, a complete and automatically self-maintained spec file for python packages from a single line calling a python function for template generation.

In order to easily override template defaults by simply defining it in spec as by regular practice rather than having to pass specific function arguments for this, the spec file needs to be read as some tags, as well as sections aren't macro defined and possible to check whether defined or not without being able to parse the spec file. Especially as the spec parser & macro interpreter only reads one direction and not able to read ahead, it's impossible to implement any macros/functions with actions of determined by anything not already processed before while parsing spec file.

So any kind of templating regardless of rpminterp/pyspec are already strongly limited by not allowing spec file to be self-aware when ie. writing regular macros for such purposes currently already independent of what my needs for and attempt at achieving.

As this has already been implemented and in use by others as well with @mlschroe attempting to pushing this upstream before, there are obviously practical uses of and desire for this functionality that argues for why it should be merged.
So in stead of the need for making strongly convincing arguments for a trivial one-line piece of code of benefit to packaging, the more rational matter of discussion here should rather be why not and strong arguments against.

**Comment by pmatilai** [comment]
You know, that level of hackery and trickery sounds more like an argument AGAINST this than for it.

I'm sure there are all sorts of funky hacks that allowing spec to access itself would enable. And my message is: find some better way of doing it.

**Comment by proyvind** [comment]
I describe to you exactly what my use case is, with both examples and code branches referred to, demonstrating obvious benefits by themself, with this one being the simplest and least trivial to maintain is also explained exactly what further benefits would bring to the rpminterp/embeddded python interpreter & pyspec generator.

I also point out limitations of the dinousaur rpm macro interpreter, which is just one of many (#222 was actually my initial motivation for why I decided on python being the perfect candidate for build time alternative interpreter to rpm's own macro interpreter btw. as lua for what should be obvious reasons didn't suffice technically, nor especially wrt. common packagers' knowledge and skills regarding) why you should provide packagers with the freedom of %_specfile to get around these limitations.

You are simply not speaking from a packagers POV, for which this is certainly more about reducing the level of horrible, distro fragmented macro hackery and of rpm distros due to what was a neat standard rpm specific macro interpreter at the time of implementation, it's simply not kept up with the times nor ensured any sense of package standardizing or anything beyond RPM based distro.

Debian in contrast, while not particularly fond of debian packaging, they do at least outsource it to shell scripts rather than relying on own interpreter not able to keep up with times, which RPM's dinosaur macro interpreter is unable to do by itself, nor not really allowing for means of getting past the limited focus and priorities on rpm package management as which makes up the most critical users of rpm, namely package maintainers.

My level of hackery is quite sane and absolutely the definite best effort with what's possible and currently in place, if you dispute this, you can't possibly haved bothered trying to understand the matter, relationship  with rpminterp #190, pyspec (https://github.com/proyvind/rpm/tree/pyspec) and the huge benefits to packagers.

rpminterp (which I still haven't received a comment on) & this PR opening up for more freedom to allow packagers to reduce their number of lines per spec down all the way down to just a single line, able to automatically maintain itself on rebuilds is something I'd like to see any remotely valid arguments against. Not to forget the fact that one leaves it possible for third parties using rpmbuild for package maintenance will be allowed complete freedom to enhance packaging without rpmbuild being a roadblock/bottleneck for. 

Active in the field of rpm packaging within Mandrake Cooker since 2001, I can clearly on the behalf of packager maintainers for sure state that %_specfile is something desired and used by packagers, not increasing the level of hackery, but rather reducing and getting around rpmbuild hackery and limitations.

What pety dispute over a single one-line commit which even has been rejected when pushed by @mlschroe in the past, which should be indication enough of it's usefulness and benefits from it...

**Comment by matejcik** [comment]
@pmatilai In python-rpm-macros, I have code falling back to looking for `%name.spec` in `%_specdir` and `%_sourcedir`, which works reasonably well.

In other words, people who want to mess with spec file contents can already find it, except their solutions are made more fragile by not having this feature.

**Comment by proyvind** [comment]
yupp, spec file name might not necessarily be %name.spec.. :|

**Pull request closed without merging**
