### PR TITLE
Come up with %_smp_flto macro that expands in a similar way to _smp_mflags.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by marxin** [comment]
Sorry. Currently -flto=N option can make LTO linking phase parallel. It's desired to expand the RPM macro when a package is built in order to shorted build time of a package.

**Comment by marxin** [comment]
Hello. May I please remind this patch review?

**Comment by Conan-Kudo** [comment]
@marxin Could you please reword the commit message to include an explanation of why you want this?

**Comment by pmatilai** [comment]
NAK as it is now. Copy-paste approach is not going to cut it. We need a separate macro that just figures out the number of cpu's we're allowed to use, which can be then used by any macros needing that info.

Also this is a bit different from -j as AFAICS this is used for enabling LTO regardless of the number of cpus, so the name is misleading / non-descriptive.

**Comment by marxin** [comment]
> NAK as it is now. Copy-paste approach is not going to cut it. We need a separate macro that just figures out the number of cpu's we're allowed to use, which can be then used by any macros needing that info.
> 
> Also this is a bit different from -j as AFAICS this is used for enabling LTO regardless of the number of cpus, so the name is misleading / non-descriptive.

You are right, refactoring was needed. Should be updated now.
Ready to be merged?

**Comment by pmatilai** [comment]
That's indeed much better, thanks. There's still the naming mismatch with the concept though: %_smp_flto enables LTO regardless of number of cpus, and flto is the name of the compiler switch, the feature is simply LTO. Maybe it should be %_lto_mflags instead?

How you envision this gets used in practise - is it something that eg distros might want to enable by default some day, or is it strictly per-spec thing? Just thinking whether there should be some integration with %make_build for example.

**Comment by pmatilai** [comment]
Right. But the place in %optflags points out that this a not *make* flag like -j is but compiler flag. So maybe it really should be _lto_cflags, or something like that, instead of _mflags.

The other thing I'm wondering if this is something that needs a special disabler (no matter what you do there'll be somebody who needs a way to disable it :smile: ) or if just redefining it to %{nil} is sufficient (probably it is).

**Comment by marxin** [comment]
> Right. But the place in %optflags points out that this a not _make_ flag like -j is but compiler flag. So maybe it really should be _lto_cflags, or something like that, instead of _mflags.

Done in updated version of the patch.

> 
> The other thing I'm wondering if this is something that needs a special disabler (no matter what you do there'll be somebody who needs a way to disable it  ) or if just redefining it to %{nil} is sufficient (probably it is).

I was thinking about something like:
https://github.com/openSUSE/rpm-config-SUSE/pull/5
Do you believe it should land in rpm package and not in the SUSE-specific one?

**Comment by pmatilai** [comment]
The %{optflagsnolto} approach doesn't scale. When the next similar thing comes along, you'd then need variants for the entire matrix of possibilities. A simple and generic (if a bit crude) way to disable it is:
```%define _lto_cflags %{nil}```

The question is whether that's sufficient or if there should be some sort of more user-friendly "disable lto" macro. OTOH those "user-friendly" disablers tend to suffer from various other side-effects...

**Comment by marxin** [comment]
> The question is whether that's sufficient or if there should be some sort of more user-friendly "disable lto" macro. OTOH those "user-friendly" disablers tend to suffer from various other side-effects...

That works fine for me! Then I won't need the
openSUSE/rpm-config-SUSE#5

Can the SR be merged now?

**Comment by pmatilai** [comment]
I guess we're happy with the macro itself now, but the commit message doesn't match the action even remotely. Ideally this would be two commits, one for the _smp_mflags refactoring and a second one to add the new macro, and a proper rationale + explanations. For example, _smp_mflags doesn't behave identically now because previously we didn't supply -j at all in the case of single cpu.

**Comment by marxin** [comment]
> I guess we're happy with the macro itself now, but the commit message doesn't match the action even remotely. Ideally this would be two commits, one for the _smp_mflags refactoring and a second one to add the new macro, and a proper rationale + explanations. For example, _smp_mflags doesn't behave identically now because previously we didn't supply -j at all in the case of single cpu.

Done.

**Comment by pmatilai** [comment]
I edited the %_lto_cflags commit message a bit and merged this manually.

Thanks for the patch!

**Comment by marxin** [comment]
> I edited the %_lto_cflags commit message a bit and merged this manually.
> 
> Thanks for the patch!

Thank you very much for help.
Btw. when is planned another rpm release?

**Pull request closed without merging**
