### PR TITLE
Drop support for installing v3 packages

### PR DESCRIPTION
**Pull request by pmatilai**
Retain support for reading v3 packages but refuse to install them. Plenty of details in the commit messages, enjoy :smile: 

Fixes: #1107

### CODE REVIEW

**Comment by pmatilai** [comment]
FWIW, my initial version placed the RPMTAG_HEADERIMMUTABLE test to addTe() which would be more central, but that lacks the means to return a meaningful error code for the situation. And it would prevent removing such packages from the db if you still happened to have one.

**Comment by ffesti** [comment]
Commit messages of the first patch talks about versions before 4.0.2 while https://github.com/rpm-software-management/rpm/pull/3305/commits/3e24b095c7ce0397c6211d2cebe5530154ef13fc says "the immutable region as we know it appears in commit
https://github.com/rpm-software-management/rpm/commit/7dbc73fec627ec4760f8b031df64ee659c6e6a86, so apparently in 4.0.4."

Not sure if this really inconsistent but is looks funny.

**Comment by pmatilai** [comment]
Oh, good spotting. I ended up doing reordering the commits after some research etc so it might not be entirely coherent. I'll double-check and fix those.

**Comment by pmatilai** [comment]
Commit messages updated wrt the version history in particular, some of it wasn't very coherent really :smile:

**Pull request merged**
