### PR TITLE
Support libgrypt as crypto library

### PR DESCRIPTION
**Pull request by mlschroe**
Choice is good ;)

### CODE REVIEW

**Comment by mlschroe** [comment]
Seems we should get rid of AM_PATH_LIBGCRYPT ;(

**Comment by Conan-Kudo** [comment]
@mlschroe Any particular reason for libgcrypt (from GnuPG) vs libnettle (from GnuTLS)? The relative complexity of detecting gcrypt and the somewhat insufferable upstream concerns me slightly...

**Comment by mlschroe** [comment]
No, nothing particular. Libgcrypt is approved by our sec folks, I need to ask them about libnettle.

(Detecting gcrypt is not an issue)

**Comment by mlschroe** [comment]
There doesn't seem to support for a "fips mode", where some unsave digests are forbidden. So it's not something I can use for SUSE. Still, adding support for it seems to be pretty easy, I can do it if there's interest in merging it.

**Comment by Conan-Kudo** [comment]
@mlschroe Hmm, there's a FIPS mode for GnuTLS, I thought that also meant the underlying nettle library had one. I'd prefer to see a GnuTLS version simply because it's easier to build across platforms...

**Comment by pmatilai** [comment]
In a perfect world I'd be much happier with less choice over crypto implementations, but as it is, with our default being something of a cross between a gorilla and an elephant on our back, and the nicer one being license-restricted... 

Did a quick performance comparison between the variants, ```time ./rpm -qa|wc -l``` on my laptop, results are fastest from three runs each:

$time ./rpm -qa|wc -l

* openssl:
        real    0m1.609s
        user    0m1.523s
        sys     0m0.111s

* libgcrypt:
        real    0m1.983s
        user    0m1.902s
        sys     0m0.130s

* nss:
        real    0m2.683s
        user    0m2.580s
        sys     0m0.124s

* beecrypt:
        real    0m4.706s
        user    0m4.610s
        sys     0m0.115s

This comparison is quite favorable too:
$ wc -l  rpmio/digest_*.c
  507 rpmio/digest_beecrypt.c
  404 rpmio/digest_libgcrypt.c
  532 rpmio/digest_nss.c
  833 rpmio/digest_openssl.c

It's the simplest of them all code-wise and second fastest overall, beating our current default at both and with a nice license. Not to mention just a fraction of the size of the nss on the library side. What's not to like?

I'll be happy to merge, but I'd actually suggest going one step further: add a separate commit to make libgcrypt the default.

**Comment by Conan-Kudo** [comment]
@pmatilai Perhaps we may want to add a commit to deprecate NSS backend or just straight rip it out?

**Comment by pmatilai** [comment]
Ripping out is a bit radical at this point, I'd start by changing the default. 

We do need to think about removing too,  while the crypto situation warrants *some* choice, I don't believe in choice for choice's sake, and even less so when I'm the one who gets to maintain them all. Also I wouldn't start with nss - despite it being a bit of a monster, it's at least reasonably fast and maintained upstream. Yes, I'm looking at you beecrypt...

**Comment by pmatilai** [comment]
Anyway... guess @mlschroe is busy, so lets get this merged and I'll do a separate PR for changing the default when I get around to it.

**Comment by pmatilai** [comment]
Oh and thanks @mlschroe , this was a very welcome addition.

**Comment by pmatilai** [comment]
Default change submitted as PR #832

**Comment by Conan-Kudo** [comment]
@pmatilai The main reason I suggest removing NSS is because NSS has become increasingly troublesome to use for anything except Firefox, and nowadays, NSS upgrades often require rebuilding everything dependent on NSS to continue working properly. We've had incidents where rpm was broken because someone forgot to do that, so I feel that it probably makes sense to eliminate NSS as a backend because of it.

**Comment by pmatilai** [comment]
I'm quite aware of what a PITA NSS is, been all along (took years to really tame it for rpm). But it also has FIPS mode and the like which are important to some, and despite all the pain it actually *is* actively maintained upstream. So no matter how much I hate it, I don't see it being the first in the slaughter line. None of these things require a whole lot of maintenance, so getting rid of them is not a huge priority anyway.

**Pull request merged**
