### PR TITLE
Add %__autoreconf macro

### PR DESCRIPTION
**Pull request by kloczek**
This macro still is missing in whole set of auto tools macros.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
I would rather see all autofoo macro being removed... but for the completeness sake, looks good.

**Comment by kloczek** [comment]
Majority of the most Linux distributions still uses auto tools and it will be like this for next couple of years.
If someone want to use for example -Wl,--as-needed or LTO transparently all what is needed to prepare all those projects is call autoreconf before configure execution.
If it is necessary to use aclocal, autoconf, libtoolize or automake usually it is clear sign that auto suite is not finished or it is wrongly implemented.
Just checked my own stash of already cleaned packages and:
<pre>[tkloczko@domek SPECS.g2v]$ grep ^autoreconf *| wc -l
300
[tkloczko@domek SPECS.g2v]$ grep &quot;^%meson &quot; *| wc -l
105
[tkloczko@domek SPECS.g2v]$ grep &quot;^%cmake &quot; *| wc -l
21
[tkloczko@domek SPECS.g2v]$ ls -1 | wc -l
489
</pre>
Yesterday in my own set of macros I've changed %__{aclocal,automake,autoconf,libtool,autoreconf} macros to be listed with full path.
Would you accept as well that kind of patch as well?
Effectively such change reduces number of syscalls by few during whole build process but provide all those macros with full path is important from security point of view as most of the distributions has /usr/local/bin on the front of the $PATH. In other words with full paths it is not possible to alter build process by putting copies of the auto tools in /usr/local/bin.
I'm still reviewing all other macros to apply similar changes to mask in macros pull paths to all used during build process commands. Those masking is as well important for me as I've started building Solaris (not rpm but IPS one) packages using rpm spec files. In other words this macros masking allows reuse almost 100% of the Linux build procedure on Solaris as well.

**Comment by pmatilai** [comment]
> I would rather see all autofoo macro being removed...

Likewise. I've never seen any of those macros actually used, heck I didn't even know we had such macros.

**Comment by Conan-Kudo** [comment]
@pmatilai They are used in a few places and distros. But the main usage probably stopped when `%GNUconfigure` went away. There's a `%autoreconfigure` macro floating around somewhere that uses these as well...

**Comment by pmatilai** [comment]
> But the main usage probably stopped when %GNUconfigure went away. 

Ah of course. Thanks for pointing that out, it's actually good reason to get rid of them: #691

**Comment by ffesti** [comment]
Ok, they are all gone now. Closing this.

**Comment by kloczek** [comment]
Mageira, OpenMandriva are using those macross on massive scale.
Fedora spec files are using those mscros as well.
You just broke many packages. Please rollback this patch
<pre>[root@domek SPECS.fedora]# grep __auto *
<font color="#CD00CD">fastbit.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">fastbit.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>make} --copy --no-force
<font color="#CD00CD">iec16022.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">iperf.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">libticonv.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>header}
<font color="#CD00CD">libticonv.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>make} --add-missing
<font color="#CD00CD">libticonv.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">lucidlife.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">OpenIPMI.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>header}
<font color="#CD00CD">OpenIPMI.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>make} --add-missing --copy --foreign --force-missing
<font color="#CD00CD">OpenIPMI.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">qrencode.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">slurm.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
<font color="#CD00CD">slurm.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>make} --no-force
<font color="#CD00CD">trafshow.spec</font><font color="#00CDCD">:</font>%<font color="#CD0000"><b>__auto</b></font>conf
<font color="#CD00CD">vtun.spec</font><font color="#00CDCD">:</font>%{<font color="#CD0000"><b>__auto</b></font>conf}
[</pre>

**Comment by pmatilai** [comment]
Distros are free to add these macros to their own macro files if they see fit. They don't belong in rpm though.

**Comment by kloczek** [comment]
Problem is that in this case we are talking about macros so far provided by vanilla rpm and those macros are used by multiple distributions.
If you don;t care about OOTB macros why art all rpm provides any macros?
Why rpm cannot create platform to exchange build procedures between distributions because this move definitely cuts off such possibilities.

**Pull request closed without merging**
