### PR TITLE
Add an error message when rpm fails to open a pipe for shell expansion

### PR DESCRIPTION
**Pull request by pavlinamv**

### CODE REVIEW

**Comment by pmatilai** [comment]
Yup, an error message is indeed missing there. The message lacks context though, might want to add the command it's trying to execute to give both the user and the developer who gets bugged a little bit of context as to what rpm was trying to do (although the command itself has little to do with the failure in this case)

Also when system calls (and similar) fail, it's usually a good idea to add strerror(errno) to the output to give the user a clue as to why it failed. popen() errno behavior seems a bit strange though, the manual says "The popen() function does not set errno if memory allocation fails." but that's exactly what I get if I make the shell unexecutable. ENOMEM seems a bit unexpected in that situation :D

**Comment by pavlinamv** [comment]
Changed (added the command it's trying to execute and strerror(errno)).

**Comment by pavlinamv** [comment]
Removed unnecessary "mb->error = 1;" line.

**Comment by pmatilai** [comment]
Right, I noticed but forgot to mention setting mb->error becoming redundant, thanks.

As for the error message, if you grep around a bit you'll notice that the common pattern for these things is:

<error message>:<what>:<why>

...where <what> is a file name or similar, and in this case it'd be the macro, and <why> is the strerror(errno) / %m. It might actually be the unexpanded macro that makes it easier to trace the origin, but not sure about that.

**Comment by pavlinamv** [comment]
Commit message is corrected according to @pmatilai's comment.

**Pull request merged**
