### PR TITLE
Remove remaining Python helpers and scripts from the repo

### PR DESCRIPTION
**Pull request by pmatilai**
These are far better maintained by the Python community, in a
repository of their own.

### CODE REVIEW

**Comment by pmatilai** [comment]
@hroncok @torsava @gordonmessmer @Conan-Kudo (apologies to those I'm sure I missed, feel free to tag more)

We've talked and talked and talked about this in way too many PR's: PR's related to Python and other "language SIG" material linger on and on because we don't know what to do with them and who's "authorative" on accepting a change and whatnot. Not to mention the changes themselves. So sometime last year I declared that we'll be pruning out the remaining language-specific bits out of rpm , and that Python being the perfect candidate to start with because there's a vibrant community that is handling this stuff and will be better off without people like me standing cluelessly in the way. Time to make it so. I've been hoping for some clear-cut point where we have no open PR's on this content, but we have a couple of PR's that have been lingering on for quite some time now (#1014, #1546), and we're closing in on that next release rapidly.

**Comment by Conan-Kudo** [comment]
I'm not happy about this because this is the only place where I can get all RPM distros to pull something in and start using it.

**Comment by hroncok** [comment]
If this is happening, let's move it to rpm-software-management/python-rpm-ecosystem (and we'd happily maintain it there).

**Comment by hroncok** [comment]
cc @s-t-e-v-e-n-k

**Comment by hroncok** [comment]
> I'm not happy about this because this is the only place where I can get all RPM distros to pull something in and start using it.

I get your point of view but I also get @pmatilai's. I guess there's no way to stop this from happening eventually and simply postponing it all the time brings us nowhere: Let's do our best to minimize the impact - by not maintaining this downstream only, but creating a distro-shared place under the @rpm-software-management GitHub org.

**Comment by torsava** [comment]
Indeed both choices are not perfect. However, the Python parts are getting rather complex. We even have a full blown test suite for them in Fedora that we would be able to finally upstream if there's a separate repo. So overall, :+1: from me.

**Comment by pmatilai** [comment]
Indeed it's not the perfect solution, it's an imperfect world unfortunately. But literally, being inside rpm is holding this stuff back (see the test-suite situation). Rpm is a slow and rigid beast whose releases occur differently from any particular language ecosystem, and imposing the structure of an ancient C project to Python and whatnot is doing disservice to everybody.

And yes, we need to add links and make noises to ensure people find the split-off material.

**Comment by pmatilai** [comment]
So, rpm-software-management/python-rpm-ecosystem it is?

I rather like that. Just noting that we should follow the same naming pattern for other languages that may follow, but this is a nice generic pattern.

**Comment by hroncok** [comment]
I was thinking python-rpm or rpm-python, but that that sounds like the bindings.
I was thinking python-rpm-macros or python-rpm-generators, but neither of them contains the other.
Hence, I though of python-rpm-ecosystem.

If we do this, I can import the files there with a rebased git history.

**Comment by pmatilai** [comment]
"ecosystem" is nice in that it doesn't limit it to macros/scripts/whatever and is pretty future-proof.

The only thing I'm mulling about is the order: another possibility could be "rpm-ecosystem-python" so assuming there will be multiple such projects they line up nicely next to each other in eg file lists. But then it has other downsides, and I certainly dont want this to get stuck on bikeshedding over the name :sweat_smile:

**Comment by pmatilai** [comment]
I'll leave this to cook over the weekend. If there are no drastic changes of overall opinion or so, I'll proceed with python-rpm-ecosystem on Monday.

**Comment by DemiMarie** [comment]
> "ecosystem" is nice in that it doesn't limit it to macros/scripts/whatever and is pretty future-proof.
> 
> The only thing I'm mulling about is the order: another possibility could be "rpm-ecosystem-python" so assuming there will be multiple such projects for different languages they line up nicely next to each other in eg file lists. But then it has other downsides, and I certainly dont want this to get stuck on bikeshedding over the name

I prefer this one for several reasons.  One of them is that if we decide to have an `rpm-ecosystem` repository and/or project, this name would fit much better.

**Comment by hroncok** [comment]
I have no strong preference for either rpm-ecosystem-python or rpm-python-ecosystem

**Comment by pmatilai** [comment]
>  we decide to have an rpm-ecosystem repository 

We have rpm-extras already, but that's clearly not going anywhere. Which likely suggests the approach there isn't right. Which reminds me, I think the initial idea was to build around rpm-extras, so this would be rpm-extras-python. Which is as good a name as any, *if* one doesn't mind the fact that rpm-extras itself seems to be a failed attempt.

**Comment by pmatilai** [comment]
We'll be living with these names for a long time, so bear a little more bikeshedding...

@ffesti came up with a better suggestion: "packaging" which I find worlds more descriptive than "ecosystem" or "extras".

The order of words remains a question: "python-rpm-packaging" or "rpm-packaging-python" - there are plenty of arguments for both. The former just groups with python packages, the former with rpm-stuff.

**Comment by dmnks** [comment]
Another idea: "rpm-build-python" etc.

**Comment by Conan-Kudo** [comment]
`rpm-python-packaging` maybe? It actually describes what it is and the rpm prefix indicates that it's about the rpm ecosystem...

**Comment by pmatilai** [comment]
Looking for some precedent...

In Fedora, *all* such packages are *lang*-prefixed, not rpm. In Debian, these things appear to be called "lang-debian". Note the order again. I'm not sure about Suse, but it's *not* rpm-prefixed.

I'd think that's a pretty strong hint that lang-prefix is what the "lang-people" (sorry! :sweat_smile:  ) predominantly want.

**Comment by pmatilai** [comment]
Okay, lang-rpm-packaging it is, end of bikeshed :sweat_smile: 
https://github.com/rpm-software-management/python-rpm-packaging created, @hroncok invited to admin it.

**Comment by hroncok** [comment]
I'll import stuff later this week.

**Comment by pmatilai** [comment]
@hroncok , any preference wrt this and the other related PR's - should we wait until you've imported things, or just go ahead and close to signal end of business? Either way is fine with me.

**Comment by hroncok** [comment]
Keep them open, let's close them when we reopen them for the new repo.

**Comment by hroncok** [comment]
> I'll import stuff later this week.

I didn't get to it due to this week being shorter (it's a public holiday today in CZ and I am taking a break), but it is on my TODO for the next week.

**Comment by hroncok** [comment]
```
git clone https://github.com/rpm-software-management/rpm.git python-rpm-packaging
cd python-rpm-packaging
git remote remove origin
git switch -c main
git filter-repo --path-glob 'scripts/*python*' --path-glob 'fileattrs/*python*' --path platform.in --path COPYING --path CREDITS --force
FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch -f  --prune-empty --tree-filter 'sed -i "/python/!d" platform.in || :; test -s platform.in || rm -f platform.in' -- --all
git remote add origin git@github.com:rpm-software-management/python-rpm-packaging.git
git push -u origin main
```

Looks good? I'll add a README and modify CREDITS accordingly later manually.

**Comment by pmatilai** [comment]
> I didn't get to it due to this week being shorter (it's a public holiday today in CZ and I am taking a break)

No worries, I was away Thu-Mon as well. 

The platform.in thing looks a bit weird but it'll of course get merged into other macro content eventually.

**Comment by hroncok** [comment]
Yes, I plan to rename platform.in and explain in the README what it is for.

**Comment by pmatilai** [comment]
Rebased + squashed...

Are we good to go with this?

**Comment by hroncok** [comment]
I guess we are. I want to get the README adapted there but that is not a blocker for removal from here.

However, let's document the transition in the changelog?

**Comment by pmatilai** [comment]
Oh, right. Now that the repo exists we can actually point to it in the commit message. Good point.

This of course belongs to release notes as well, I'll handle that separately.

**Comment by pmatilai** [comment]
Also in the release notes now:
https://github.com/rpm-software-management/rpm-web/commit/e35a85cd2e7cc981cff88f79c32b1c678515cbf1

**Comment by pmatilai** [comment]
Uh-oh, all manner of things getting forgotten... I'm hitting merge now to clear the road for other things. 

Is Fedora rawhide ready for landing this split? I'm not planning to do so anytime soon, just want to understand where things stand at the moment. Delaying this split to rpm 4.18 is still technically possible regardless of merge status if it seems too much to handle right now.

**Comment by hroncok** [comment]
Fedora rawhide does not use the removed files via the rpm package.

**Comment by mikhailnov** [comment]
We in ROSA rosa2021.1 in rpm 4.17 restored removed stuff with a patch (https://abf.io/import/rpm/blob/rosa2021.1/0024-Restore-python-helpers.patch), now in the new platform rosa2023.1 I am updating rpm from 4.17 to 4.18 and will try to use https://github.com/rpm-software-management/python-rpm-packaging , but I am a bit confused because it seems that nobody really uses them and there is even no Makefile or instruction how to install it (of course it is quite clear where to put different files, but still...).

**Comment by hroncok** [comment]
Is a huge mess. In Fedora, we want to transition into using that, but so far it has not been a priority :(

**Pull request merged**
