### PR TITLE
Implement automatic conversion of the database

### PR DESCRIPTION
**Pull request by mlschroe**

### CODE REVIEW

**Comment by mlschroe** [comment]
Oh wait, that doesn't work with erases. The rebuildb call must not renumber the packages.

**Comment by mlschroe** [comment]
Ok, fixed. I'm not happy about adding a new parameter to rpmdbRebuild(), but it seemed to be the easiest way to fix this.

**Comment by mlschroe** [comment]
That's also incorrect. It doesn't copy the "next package" counter, so adding new packages will overwrite old ones.

**Comment by mlschroe** [comment]
There's now a workaround for this. Instead of adding a new dbiSetNextInstance call I've opted to change the put functions to make sure that the next instance counter will be higher than the stored package.

For ndb this change is trivial. The sqlite backend doesn't need changing.

For lmdb/db3 things are a bit more complicated, as reading the old counter is an extra operation. So I do it only if the RPMDB_FLAG_CONVERT bit is set in the database.

I'm not really happy about this, maybe someone else has a better idea.

**Comment by Conan-Kudo** [comment]
@mlschroe Could you please rebase on current master? Perhaps that will fix the failing Semaphore CI run (I don't see anything that obviously indicates why we're getting this failure now...).

**Comment by mlschroe** [comment]
It fails because of
```
macro.c: In function 'doFoo':
macro.c:1211:2: error: 'sprintf' argument 3 may overlap destination object 'buf' [-Werror=restrict]
 1211 |  sprintf(b, "file%s.file", buf);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
macro.c:1074:11: note: destination object referenced by 'restrict'-qualified argument 1 was declared here
 1074 |     char *buf = NULL;
      |           ^~~
cc1: all warnings being treated as errors
```
I think this needs to fixed in rpm master first.

**Comment by pmatilai** [comment]
The ability to automatically convert is kinda cool, but it's not safe to just go ahead and convert anytime we spot a difference - think of eg chroot manipulation. My plan was always to just leave any database conversion down to an explicit --rebuilddb operation, and maybe add a hint about that to the existing warning message.

There's basically just one case where you want it automatically changed: when a distro changes its default, but depending on the upgrade path and tooling, it might be a chroot, or it could be the main db, and we just don't know enough. My suggestion would be a one-shot flag to explicitly request rebuild (including but not limited to conversion) at next opportunity, eg a simple `touch /var/lib/rpm/.rebuilddb` which we then remove at completion. That flag can be dropped in by distro tooling or even package %posttrans scriptlet or such.

Something like the first commit will be needed in any case though, the existing logic gets bdb_ro vs bdb mixed up in not so nice way :)

**Comment by pmatilai** [comment]
Oh and BTW, the code failing with gcc 10 got nuked in commit da94ee8195da2bc841e2a4606f2948d46a1109bb so rebase will get rid of the unrelated CI failure.

**Comment by Conan-Kudo** [comment]
@pmatilai My reading of this is that it only attempts a conversion if it can't _write_ in the target database format. So it seems to be narrowly scoped enough to not cause hell, while avoiding the nastiness of trying to do a database conversion on the fly.

**Comment by pmatilai** [comment]
Yes it only converts in that case, but it'll still wreak havoc in the chroot case where converting might render the chroot unusable from the inside with no warning. That's why I think there always needs to be an explicit request to perform conversion - there's simply no way rpm can know when it's desireable or not.

**Comment by Conan-Kudo** [comment]
Hmm, that's fair, and actually pretty much the reverse case of the problem I'm going to have now with openSUSE environments built on Fedora. 😅

**Comment by pmatilai** [comment]
As per above, rpm simply does not know enough about the surrounding world to be able to decide when it's safe to automatically convert a database, that will always need an explicit action by something/someone external. The general purpose detection logic improvement in the first commit has been merged so I think it's time to close this.

**Pull request closed without merging**
