### PR TITLE
Fall back to /tmp if TMPDIR is bogus

### PR DESCRIPTION
**Pull request by DemiMarie**
This allows the testsuite to run in a Podman container.

### CODE REVIEW

**Comment by pmatilai** [comment]
I'd be more interested in understanding what makes $TMPDIR bogus in this case.

**Comment by DemiMarie** [comment]
> I'd be more interested in understanding what makes $TMPDIR bogus in this case.

I suspect that it is a fakechroot bug, but I have not yet been able to find a workaround other than this.

**Comment by dmnks** [comment]
I routinely do a `make check` in Podman containers and never encountered this issue. Is there some specific set-up (of the testsuite) that you're referring to?

**Comment by DemiMarie** [comment]
> I routinely do a `make check` in Podman containers and never encountered this issue. Is there some specific set-up (of the testsuite) that you're referring to?

The container image itself is practically empty ― everything is bind-mounted from the host.  To be fair, it is possible that the container image that I am using is buggy, or that I am misusing podman.  Additionally, I have my source directory bind-mounted at `/source` and my build directory bind-mounted at `/build`.

**Comment by pmatilai** [comment]
@DemiMarie - interesting. I suppose you have some kind of script to set that all up - care to share?

Thing is, that sounds almost like a ticket out of this fakechroot trap we're in and would love to replace it with something more robust, but haven't found the time to get it done.

**Comment by dmnks** [comment]
FWIW, the way I use Podman here is pretty much the same - I just bind-mount my git checkout into the container and do the building and testing (including running the testsuite) from there. I do have a fancy [script](https://github.com/dmnks/dotfiles/blob/master/utils/bin/codebox) for making the management of such throwaway development containers a breeze, but that's completely optional :)

**Comment by pmatilai** [comment]
@dmnks - but you have an actual OS image in Podman, right? AIUI @DemiMarie has an essentially empty image where even the OS is populated with bind-mounts from the host, which is basically how we use fakechroot.

**Comment by dmnks** [comment]
Correct; it's a Fedora-based image, similar to our [ci/Dockerfile](https://github.com/rpm-software-management/rpm/blob/master/ci/Dockerfile).

You're right - Re-reading her comment, it does seem she's using an empty image, after all. Something like toolbox, in fact.

I wonder, though - what difference would that make (i.e. bind-mounting everything versus just the sources), with regards to how the testsuite behaves?

**Comment by pmatilai** [comment]
Ack. In fact depending on the host is far from ideal either, because then we need to worry about all manner of strange details in which hosts may vary, this case may well be one of those (I've seen my share of fakechroot weirdling behavior due to external symlinks etc). So having the test-suite run in a known version of a known distro, in a container, would be far better in many ways. Fedora is as good as any for that image, but we'd probably want an image that does *not* include rpm it, so we could put our development version as the system rpm there. But this is getting a little outside the scope here :sweat_smile:

**Comment by DemiMarie** [comment]
> @DemiMarie - interesting. I suppose you have some kind of script to set that all up - care to share?

I do!  Two of them in fact.  One uses podman and another uses bwrap.  I also have the Containerfile I use.  I don’t mind sharing them, but be warned that they have not been cleaned up and probably have bugs.  They will almost certainly require tweaking for use on anyone else’s system.

> Thing is, that sounds almost like a ticket out of this fakechroot trap we're in and would love to replace it with something more robust, but haven't found the time to get it done.

Yes and no.  Having to bring an entire distro along just to run the tests seems like mega-bloat to me.  That said, if the tests are that tightly coupled to the host environment, it might be the best option

**Comment by dmnks** [comment]
Containers aside, I'm still now sure why the `TMPDIR` variable would be set to anything other than a directory?

**Comment by pmatilai** [comment]
Yup, this sounds like papering over some issue in either local setup or something else, and I don't think we should do that.

**Comment by pmatilai** [comment]
So... I think it's better to just honestly fail if the setup is borken, rather than try build fallbacks into silly shell scripts.

**Pull request closed without merging**
