### PR TITLE
add back --target as global option

### PR DESCRIPTION
**Pull request by proyvind**
As specifying target will load & set macro definitions according to
target specified, it's still useful to provide it anywhere where ie.
--eval may be used, as by specifying --target first, it'll change the
target specific macros to load which is perfectly sane and useful for
checking macro specific definitions

Regarding 'rpmbuild --target=arch --eval' is useless as platform specific macro definitions isn't loaded before only *after* --eval, making it unfit for the purpose, while also otherwise being different in how loaded etc...

### CODE REVIEW

**Comment by proyvind** [comment]
I've removed the redundant --target from rpmspec now, but I'm uncertain about what you mean by the one specific to rpmbuild as it's identical and redundant as well.

As it therefore has the exact same behaviour as the global --target, the only difference seems to be that it's part of the --help options specific to rpmbuild, which states the following:
      --target=CPU-VENDOR-OS     override target platform

Then for the global --target option, listed below "Common options for all rpm modes and executables:":
      --target=CPU-VENDOR-OS     Specify target platform

So that's pretty much the only differences between the two I find, for which I personally think the latter global one as the more sensible (especially for rpmbuild where "override target platform" is rather ambigious..

**Comment by proyvind** [comment]
I dropped the redundant --target from rpmbuild as well, leaving for you to see fit whether merge that one or not. ;)

RE: "add back", I seem to have made false assumptions related to global --target having been in place @rpm5.org since forever, so I mistakenly figured that it preceded the 4.4.2 fork.
Obviously not.. ;)

**Comment by pmatilai** [comment]
Like I noted in my first comment, the --target in rpmbuild is different (it takes a comma-separated list) and can't be replaced this way.

**Comment by pmatilai** [comment]
Actually, never mind... dropped the rpmbuild part and squashed the other two into one, merged. 
Thanks for the patch.

**Pull request closed without merging**
