### PR TITLE
Use MIME types instead of magic strings for RPMTAG_FILECLASS

### PR DESCRIPTION
**Pull request by pmatilai**
File magic strings are unreliable and largely unusable for anything but human consumption, MIME types are far more meaningful for classifying file types. Populate RPMTAG_FILECLASS (or rather, CLASSDICT) with MIME type instead, and add types for all files and not just our strange hardcoded list. Remove now redundant cruft.
    
Fixes: #1096

Note that this is only an RFC as a basis of discussion. I know we want to include MIME data, but I'm not sure we can just replace the cruft that is currently going into RPMTAG_CLASSDICT. OTOH I'd really rather not duplicate all that to another tag set just to preserve cruft that almost nobody uses (AFAIK), such a patch would have very different line-count. 

Oh and this on top of #1098 and #1095 which are pre-requisite for doing this.

Thoughts?

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
I'm not sure it's a good idea to replace file magic entirely with MIME, as MIME tends to get identifiers a lot less frequently than file magic identifiers. And there's a _large_ world of dependency generators that rely on file magic filters, and that's something I'm not sure I want to break unless we're doing a new major version.

**Comment by pmatilai** [comment]
This doesn't affect dependency generators *at all*. This only replaces the gunk that goes into RPMTAG_CLASSDICT in packages.

**Comment by Conan-Kudo** [comment]
@pmatilai Hmm, I guess I misread this. It seemed like you wanted to transition everything away from file magic to MIME. If this is just scoped to the internal classification of content in RPM, I don't have as much of an objection. It would wind up being a file format change, though, since we're changing what kind of values to expect there.

**Comment by pmatilai** [comment]
This isn't "internal" classification either, because its very public in the headers. Hence the request for discussion.

The thing is, the existing RPMTAG_CLASSDICT content is intolerable goo. So in my view, we have two options:
1) stop creating that fileclass data, andd new tags and stuff for MIME instead
2) hijack it for MIME use

The problem with 1) is that we need to carry a lot of baggage for a little-used feature, the problem with 2) is that there *are* users (rpmlint at least) and if we just hijack it, you don't really know what data to expect there.

**Comment by pmatilai** [comment]
While looking at this, I rediscovered (oh the things you write and forget) makeClass() in lib/tagexts.c.
Which makes me think the answer is probably 1), ie leave the *CLASS* tags alone but stop populating the header with them, and add new MIME tags instead.

**Comment by pmatilai** [comment]
"Plan 1" now implemented for comparison in #1114.

**Comment by pmatilai** [comment]
Okay I suppose its become clear this is not the way to go, closing.

**Pull request closed without merging**
