### PR TITLE
Add macros to generate --enable-/disable- arguments

### PR DESCRIPTION
**Pull request by steelman**
Signed-off-by: Łukasz Stelmach <l.stelmach@samsung.com>

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Not that I see anything particularly wrong with this, but, umm, why do you want this?

**Comment by steelman** [comment]
To generate arguments for configure scripts. Take a look a few lines above at %{with}/%{without} macros. My macros do exactly the same but for --enable-/--disable-.

**Comment by Conan-Kudo** [comment]
The with/without macros don't quite work the same way, as they don't assume autotools underneath. Your enable/disable macros do.

**Comment by steelman** [comment]
Mmm... You are right, of course. It's been some time, since I've created the patch and apparently I have forgotten the details. 

Anyway there are many configure-like scripts that accept --enable-/--disable-/--with-/--without- options, not necessarily generated with autotools. I have found these macros very useful in my work and want to share them. However, for the patch to be complete there should be a pair of macros that generate --with-/--without- options. Unfortunately %{with}/%{without} are not available. How would you name the macros and would you accept them together with enable/disable?

**Comment by Conan-Kudo** [comment]
I'd defer to @pmatilai and @ffesti on this, but from my point of view, I'd just name them something like `cfg_enable`, `cfg_disable`, `cfg_with`, `cfg_without`...

**Comment by steelman** [comment]
I've renamed the macros. Below is a table describing their usage.

usage                  | %{with_foo} is definned | with_foo} is undefined
---------------------- | ----------------------- | ----------------------
%{cfg_enable  foo}     | --enable-foo            | --disable-foo         
%{cfg_disable foo}     | --disable-foo           | --enable-foo          
%{cfg_with    foo}     | --with-foo              | --without-foo         
%{cfg_without foo}     | --without-foo           | --with-foo            
%{cfg_with    foo baz} | --with-foo=baz          | --without-foo         
%{cfg_without foo baz} | --without-foo           | --with-foo=baz

**Comment by ffesti** [comment]
I think the problem here is that these macros do use the same name for both the bcond variable and the configure switch. I'd rather think that the interesting cases are where you need to have some high level bcond switch may be even resulting in multiple copnfigure switches of different names.
Using the same name is especially weird for the disable and without cases. I really cannot see the use case where you would have to pass --with-foo just to have foo disabled in the configure script. I can imagine disabling other features while enabling foo.

**Comment by steelman** [comment]
> I think the problem here is that these macros do use the same name for both the bcond variable and the configure switch.

You are right. Gentoo has [`use_enable`](https://gitweb.gentoo.org/proj/portage.git/tree/bin/ebuild.sh?id=033e7b68cc5495ab43498a73940be23b919aa5cf#n254) and [`use_with`](https://gitweb.gentoo.org/proj/portage.git/tree/bin/ebuild.sh?id=033e7b68cc5495ab43498a73940be23b919aa5cf#n236) , which are more or less prototypes of these macros, can accept two parameters which make them more flexible.

I see your point. I will rework the macros to act more like their Gentoo counterparts.

**Comment by ffesti** [comment]
I wonder if they should be named more similar to bcond_with.

**Comment by steelman** [comment]
Look above and you will find that naming was and still is my concern.

**Comment by ffesti** [comment]
OK, this has not made progress for nearly a year. While there may be some use in further thinking about this the current patch does just not cut it. I am closing this for now.
Feel free to continue the discussion on the mailing list or in a new, improved PR.

**Pull request closed without merging**
