### PR TITLE
Added a high-level wrapper.

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by KOLANICH** [comment]
@pmatilai @Conan-Kudo  @ignatenkobrain

**Comment by ffesti** [comment]
I really like the idea of offering some easier to use API and using an context manager for that. But there are several aspects of this implementation that don't quite feel right to me.

At first I wonder if we can find a better name for the class. This actually wraps (binary) packages. Not sure if `Package` is too generic but it is much closer to the truth.

Abbreviating `archive` with `arch` is super confusing as `arch` is used everywhere else as synonym of `architecture`.

The fd used should really be stay hidden inside the class. Using it else where will only lead to tears and broken bones.

Not sure if `iterFiles` is really needed or if it is better to point to directly using the .archive attribute in the doc string. Or may be I am missing something here.

**Comment by Conan-Kudo** [comment]
We should also consider _what_ the high level interface should offer. From my perspective, it should (at the minimum) provide ways to:

* Work with macros and spec files
* Read RPM files
* Orchestrate building RPMs
* Do simple package management actions

But to do this well, we need a design of how this would look...

**Comment by ffesti** [comment]
> We should also consider _what_ the high level interface should offer.

Well, that's not what this PR is about. This "only" is about making it easier to open an rpm package from disk and reading the payload. We don't really plan to offer a new API for all other functionality.

**Comment by ffesti** [comment]
OK, but there is an argument to be made that this should also work for just opening an rpm package without looking at the payload and instead just accessing the header. Which makes me wonder if we really need this to be context manager.

**Comment by dmnks** [comment]
We discussed this as a candidate for an `examples/` directory which we could add. I need to think about this a little more, so just assigning to myself for now, to keep it on my radar.

**Comment by KOLANICH** [comment]
Where can I read the logs of the IRC discussion?

**Comment by dmnks** [comment]
It was on a company-internal IRC server, so no public logs, unfortunately.

**Comment by KOLANICH** [comment]
Understood. Could you elaborate, please, why into `examples` and not into the main package?

**Comment by dmnks** [comment]
Sure! We do like the idea of having such a high-level API (wrapper), but in its current form at least, this one is perhaps too specialized, and we'd rather have something more generic, like a `Package` class that would expose things like a `files` or `headers` iterator/dictionary and possibly some context managers too, similar to what you did here. But that would require a lot of work to come up with such a generic API and get it right, so instead (for now) we entertained the idea of introducing an `examples` directory where this would fit well. There's probably more stuff that we could put in there, too.

**Comment by KOLANICH** [comment]
Thanks.

**Comment by pmatilai** [comment]
The idea of adding examples is good, but its better tracked as a [ticket ](#2075 )than an open PR doing something else.

**Pull request closed without merging**
