### PR TITLE
tests: add tests for rich dependencies

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This PR supersedes #164 in an attempt to get some unit tests in for rich dependencies.

Per the original PR, this is the coverage so far:
- [x] (X and Y)
- [x] (X or Y)
- [x] (X if Y)
- [x] (X if Y else Z)
- [x] (X and (Y or Z))
- [x] (X and (Y if Z))
- [ ] (X or (Y and Z))
- [ ] (X or (Y if Z))
- [ ] (X if (Y and Z))
- [ ] (X if (Y or Z))

The `with`/`without` tests were previously merged already.

### CODE REVIEW

**Comment by pmatilai** [comment]
So what's the deal here? Summary says WIP, but otherwise this reads like a PR to get what's there merged. If it's the latter I certainly agree, gradually adding is far better than having no tests at all.

**Comment by Conan-Kudo** [comment]
@pmatilai A couple of the tests are failing because they test the wrong way. I haven't had a chance to fix them. I may not get to... @ignatenkobrain do you think you can finish this?

**Comment by pmatilai** [comment]
Why not just kick the tests that dont work so we can merge the things that do? There's always time for more tests later.

**Comment by Conan-Kudo** [comment]
@pmatilai I can do that.

**Comment by Conan-Kudo** [comment]
@pmatilai I dropped the broken tests.

**Comment by pmatilai** [comment]
Cleaned up some trailing whitespace and applied manually (commit 2e835509a62b7806e010292f354a3fa6e9830dc3).

Thanks!

**Pull request closed without merging**
