### PR TITLE
Drop support for undocumented keyid based import over the net

### PR DESCRIPTION
**Pull request by pmatilai**
This is insecure in so many ways I'm not going to bother trying to list
them all. It's an undocumented "feature" left over from more innocent
times, time to give it the axe.

### CODE REVIEW

**Comment by DemiMarie** [comment]
Thanks!

**Review by Conan-Kudo — APPROVED** [review]
Fine with me!

**Review by DemiMarie — APPROVED** [review]
Looks good to me!  I would actually consider this a security fix, though others might disagree.

**Comment by pmatilai** [comment]
Yeah it's at least bordering on being a security fix.

**Pull request merged**
