### PR TITLE
Prevent NULL deref in rpmfsGetStates()

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by pmatilai** [comment]
If you're hitting this, the actual bug is someplace else. Some of these deeper internals kinda intentionally lack the NULL-testing that the public APIs have, because they're "can't happen" situations where we'd rather have a backtrace from a crash than unknown bug eating somebodys filesystem for breakfast :sweat_smile:

If this is just for consistency with what most of rpm does then okay (rpmfs is certainly inconsistent within itself, one place has an assert and another checks for NULL and others dont...)

**Comment by DemiMarie** [comment]
Perhaps put an assertion there?

**Comment by pmatilai** [comment]
If anything we should remove the asserts that are in there, not add more...

**Comment by pmatilai** [comment]
Ok. Thanks for the patch.

**Pull request merged**
