### PR TITLE
Convert few simple generators for a parametric ones + fix for parametric generators

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by pmatilai** [comment]
Mm. 

We don't want to convert everything to parametric macros just because we *can*, because they're just harder to debug and otherwise work on for the casual observer. Only convert those were it actually makes a difference: those that affect large number of files per package. Of these, debuginfo certainly qualifies but the rest don't.

**Comment by ignatenkobrain** [comment]
@pmatilai if debuginfo qualifies, why metainfo one would not? They are essentially doing very same simple thing.

Another point to WHY to do it is to speed up generators. The desktop one is very simple and can save bunch of fork()s, so why not to replace it?

**Comment by pmatilai** [comment]
debuginfo deals with any number of files *per package*, whereas there generally is just one metainfo/desktop file in a single package. A single fork+exec in a context of a build is lost in the noise, but when you deals in the dozens it starts to add up.

**Comment by pmatilai** [comment]
Oh and FWIW, the double-buildroot bugfix merged separately via #1165.

**Comment by ignatenkobrain** [comment]
Thanks for merging that part. Anyway, those generators are very simple and I think having them as parametric ones make sense. Related to this, I have not seen your opinion on moving these things to a rpm-extras and start actually releasing those things and inform distributions. WDYT?

**Comment by pmatilai** [comment]
> Related to this, I have not seen your opinion on moving these things to a rpm-extras and start actually releasing those things and inform distributions. WDYT?

To put it in words of Finnish F1-champions: "Yes."

Sorry, couldn't resist :rofl: 

Seriously though, debuginfo certainly belongs to rpm itself as rpm is what generates them to begin with. Metainfo and desktop are both quite ubiquitous and used across language domains, so dunno, maybe. If/when rpm-extras is properly integrated etc there wouldn't be any big difference where things live, but atm...

**Comment by pmatilai** [comment]
Having now looked at these a bit more carefully... while there's no particular *need* to convert these (except maybe for debuginfo), I suppose these do serve as fine examples of what you can do what you can do with parametric generators (eg just how many silly grep's you can save etc :grinning: ) which is valuable in its own right.

I assume you have manually tested all these to produce same results as before? The test-suite does not cover any of them.

**Comment by ignatenkobrain** [comment]
> I assume you have manually tested all these to produce same results as before? The test-suite does not cover any of them.

I have tested it on my system, yes. With quite a few examples.

Just one things which I noticed when I was looking into this again... Any reason you did not use %{basename} for the redhat-rpm-config patch? I mean, I could use the same lua code here in one place.

**Comment by pmatilai** [comment]
> I have tested it on my system, yes. With quite a few examples.

Ack, good.
 
> Just one things which I noticed when I was looking into this again... Any reason you did not use %{basename} for the redhat-rpm-config patch? I mean, I could use the same lua code here in one place.

Mostly just pain of knowing too much, ie how many crazy hoops `rpm.expand("%{basename:%{1}}")` will jump through to achieve the mighty goal of string split at '/' :smile: Might even make a small difference in the kernel case, here it's entirely inconsequential.

**Comment by pmatilai** [comment]
Meh, GH's "fix conflicts" creates this strange merge commit that we don't want. Thought I'd fix it as its kinda my fault the conflict exists, but this only makes it worse... Care to do a rebase to clean it up? Thanks, and sorry about the mess.

**Comment by ignatenkobrain** [comment]
I'll rebase and clean it up :)

**Comment by pmatilai** [comment]
Thanks for the patches!

**Pull request merged**
