### PR TITLE
Refactor aux file reading (%files -f manifest etc) to a common helper

### PR DESCRIPTION
**Pull request by pmatilai**
Support for -f is not limited to %files, so it makes sense to have a common helper to do it. Inspired by the third such case to be added in #874 .

### CODE REVIEW

**Comment by pmatilai** [comment]
Added a missing and clearly necessary testcase for scriptlet -f. Doing so promptly pointed out that the refactored code was removing comments from scriptlets where the original was not, which is fixed now.

**Comment by pmatilai** [comment]
Argh, accidentally closed when cleaning up the branch pile.

**Comment by mlschroe** [comment]
The `ALLOW_EMPTY` logic seems to be broken:

- it is set if `_empty_manifest_terminate_build` is set, i.e. it's FORBID_EMPTY
- it uses RPMLOG_ERR if the flag is set
- it sets nlines to -1 if there are no lines and the flag is *not* set

**Comment by pmatilai** [comment]
Ugh, oops. The logic was probably right in some intermediate version but... thanks for spotting, should be fixed now.

Note that "sets nlines to -1 if there are no lines and the flag is not set" is as intended: the flag is not set, so empty is not allowed, and hence no lines is an error.

**Comment by pmatilai** [comment]
Since there are no further comments...

**Pull request merged**
