### PR TITLE
te: Don't reload header for JUSTDB transactions

### PR DESCRIPTION
**Pull request by cgwalters**
I'm working on some custom rpm-ostree code to "install" rpms by
unpacking them with libarchive (since this can be a lot safer than
invoking librpm - my process has total control over writes), then just
using librpm to update the database via _JUSTDB.

However, it appears that for some reason that if the transaction is
not _TEST, we attempt to reload the header from the original package
here.  I don't have the original package, just the header, since they
get unpacked into OSTree commits (with the header as ostree commit
metadata).

Now, I don't understand why we re-parse the RPM - what's wrong with
the original header we loaded?, but it fixes the problem for me to
also skip with _JUSTDB, and should be a very low risk change.

### CODE REVIEW

**Comment by pmatilai** [comment]
Rpm needs to reload the header because to conserve memory, it doesn't preserve the original at all.

**Comment by cgwalters** [comment]
Ideally, we just let `mmap()` handle that.  That's what OSTree does for metadata by default.  It'd probably work for packed RPMs as well...except in practice we byteswap in `regionSwab()` so require a writable mapping =/  For OSTree, GVariant handles a lot of this automatically for interior data, for "exterior" integers we just byteswap on access.

Anyways, one option I looked at would be for OSTree to store *everything* from the original RPM (lead, signature, header), then attempt to re-synthesize it from the ostree commit when RPM asks for it.  

Downsides:
  - A pipe-to-self is just ugly and inefficient
  - I think I'd have to parse the RPM myself to accurately extract the start of the cpio stream

Positives:
 - We'd also store the original gpg sigs

I guess regardless, it'd be nice if RPM supported (somehow) a mode where the calling application could optionally provide just a `Header` reference, not a full fd to an RPM.

**Comment by cgwalters** [comment]
I ended up storing lead/sig/header in the ostree commit, then checking it out as a tempfile and passing it back to librpm.  So we can close this.

Long term, I think what I really want is to make `rpmdbOpen` and `rpmdbAdd` public.  Then I can stay out of the business of writing to the db and dealing with berkeleydb, but know I have total control over everything else.

**Comment by pmatilai** [comment]
rpmdbOpen() and rpmdbAdd() are internal-only for a reason, for example they bypass all sorts of things like transaction lock. However in rpm >= 4.12 there is rpmtsImportHeader() which is essentially rpmdbAdd() wrapped with all the necessary stuff.

**Comment by cgwalters** [comment]
Note I don't care about transaction locking - everything rpm-ostree does is always atomic.  We create a new (hardlinked) tree, then a new rpmdb from scratch every time.

**Pull request closed without merging**
