### PR TITLE
Check return value of uname()

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Everyone knows that it can fail...

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Honestly, I didn't check 2nd patch carefully.. But according to my knowledge about operators precedence in C, it should just work.

**Comment by ignatenkobrain** [comment]
cc @proyvind

**Comment by ignatenkobrain** [comment]
Apparently, this is still not enough to make RPM work without uname() =(
```
#0  0x00007f291a3e1386 in strlen () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f291c60e2de in rstrdup (str=str@entry=0x1 <error: Cannot access memory at address 0x1>) at rpmmalloc.c:73
        size = <optimized out>
        newstr = <optimized out>
#2  0x00007f291c86cf7e in rpmSetMachine (arch=0x1 <error: Cannot access memory at address 0x1>, arch@entry=0x0, os=0x1 <error: Cannot access memory at address 0x1>, os@entry=0x0, 
    ctx=0x7f291ca9b8a0 <_globalCtx.9666>) at rpmrc.c:1400
        host_cpu = 0x1 <error: Cannot access memory at address 0x1>
        host_os = 0x1 <error: Cannot access memory at address 0x1>
#3  0x00007f291c86d2ad in rpmRebuildTargetVars (target=target@entry=0x7ffeb4b6e248, canontarget=0x0, ctx=0x7f291ca9b8a0 <_globalCtx.9666>) at rpmrc.c:1467
        ca = 0x0
        co = 0x0
        ct = 0x0
        x = <optimized out>
#4  0x00007f291c86e40c in rpmReadConfigFiles (file=0x0, target=<optimized out>, target@entry=0x0) at rpmrc.c:1617
        rc = -1
        ctx = 0x7f291ca9b8a0 <_globalCtx.9666>
#5  0x00007f291c85add1 in rpmcliConfigured () at poptALL.c:68
No locals.
#6  0x00007f291c85b2fa in rpmcliInit (argc=3, argv=<optimized out>, optionsTable=<optimized out>) at poptALL.c:316
        optCon = 0x5593f9de8030
        rc = -1
        ctx = <optimized out>
        execPath = <optimized out>
#7  0x00005593f9adc3fd in main (argc=3, argv=<optimized out>) at rpmqv.c:91
        ts = 0x0
        bigMode = MODE_UNKNOWN
        optCon = <optimized out>
        ec = 0
        i = <optimized out>
```

**Comment by cgwalters** [comment]
Under what conditions?  An aggressive seccomp policy?

**Comment by ignatenkobrain** [comment]
@cgwalters just strace with failure injection: `strace -e uname -e fault=uname rpm -qa`

**Comment by pmatilai** [comment]
It's not the uname() failure itself but what's left uninitialized because of it. On an x86_64 this is enough to get 'rpm -qa' working (without any other patches):

```
--- a/lib/rpmrc.c
+++ b/lib/rpmrc.c
@@ -1018,7 +1018,7 @@ static void defaultMachine(rpmrcCtx ctx, const char ** arch, const char ** os)
            break;
        }
        rc = uname(&un);
-       if (rc < 0) return;
+       if (rc < 0) goto exit;
 
 #if !defined(__linux__)
        if (rstreq(un.sysname, "AIX")) {
@@ -1286,6 +1286,7 @@ static void defaultMachine(rpmrcCtx ctx, const char ** arch, const char ** os)
        break;
     }
 
+exit:
     if (arch) *arch = un.machine;
     if (os) *os = un.sysname;
 }

```

**Comment by ffesti** [comment]
The man page says it can only fail if the buffer provided is broken. So I really don't see the point of all this. Closing.

**Pull request closed without merging**
