### PR TITLE
Fix don't use 'rpm2archive foo.rpm | tar -x' 

### LINKED ISSUE #2208: Fix rpm2archive to behave like rpm2cpio (by default)
rpm2cpio outputs to stdout, which makes it natural and efficient to use for piping: 'rpm2cpio foo.rpm|cpio -idv'. rpm2archive however behaves very differently by silently creating a .tgz in the directory of the rpm received as argument. This breaks the rule of least surprise really, especially given the long-standing behavior of rpm2cpio.

This causes head-scratching from users (me included), inefficient piping because you then need to use clumsy 'cat foo.rpm|rpm2archive|tar x' instead of 'rpm2archive foo.rpm|tar x', and it means it doesn't feel like the (almost) drop-in replacement of rpm2cpio it should be. Assuming libarchive supports cpio, we could make rpm2archive output that when called as rpm2cpio which would free us to drop rpm2cpio.c.

EDIT: initial description went too far in rpm2cpio replacement

### PR DESCRIPTION
**Pull request by yangchenguang94**
fix #2208 
image

### CODE REVIEW

**Comment by dmnks** [comment]
This doesn't actually address #2208. It only enables the omission of `-`, and that only works if you also supply another argument (`-n` in the above examples), otherwise rpm2archive fails. Also, a man page update would be in order if we change such behavior.

What we need is to *always* print to stdout, not a file. But even then, I'm not sure how to keep backward compatibility in case somebody is used to the current behavior (see my comment in the issue).

Thanks for the effort nevertheless. If you plan to do a proper fix (with the above in mind), please open a new PR, I'll close this one now to keep our backlog tidy.

**Comment by yangchenguang94** [comment]
> This doesn't actually address #2208. It only enables the omission of `-`, and that only works if you also supply another argument (`-n` in the above examples), otherwise rpm2archive fails. Also, a man page update would be in order if we change such behavior.
> 
> What we need is to _always_ print to stdout, not a file. But even then, I'm not sure how to keep backward compatibility in case somebody is used to the current behavior (see my comment in the issue).
> 
> Thanks for the effort nevertheless. If you plan to do a proper fix (with the above in mind), please open a new PR, I'll close this one now to keep our backlog tidy.


Sorry, I didn't understand your point of view. The modification is to add the expected usage method on the basis of the original one and keep it compatible. Now it is planned to abandon the original method or not deal with other parameter types.For example:

`rpm2archive CUnit-help-2.1.3-22.uel20.noarch.rpm | tar -xz`

I am willing to submit a new PR for this problem. Thank you for your reply

**Comment by dmnks** [comment]
OK, turns out I was wrong saying:

> What we need is to _always_ print to stdout, not a file.

The patch you proposed indeed does exactly that, I just got confused, apologies for that.

Also, while omitting `-` works with rpm2cpio, it's not in fact documented, so we might as well not bother with that in rpm2archive and keep it as it is, i.e. requiring either `-n` or `-`, in accordance with the man/usage page.

That leaves us with the following:
* Indent the else block to make it more readable (this can be done as a second commit to keep the original diff obvious)
* Update the man page to reflect this change

Other than that, the patch looks fine, after all. I'll reopen the PR, please update it with the above suggestions when you get a chance.

**Comment by pmatilai** [comment]
> Indent the else block to make it more readable (this can be done as a second commit to keep the original diff obvious) 

The indentation change belongs to the same commit: the code logic changes fundamentally and trying to avoid indentation changes only makes that logic harder to follow.

**Comment by yangchenguang94** [comment]
> OK, turns out I was wrong saying:
> 
> > What we need is to _always_ print to stdout, not a file.
> 
> The patch you proposed indeed does exactly that, I just got confused, apologies for that.
> 
> Also, while omitting `-` works with rpm2cpio, it's not in fact documented, so we might as well not bother with that in rpm2archive and keep it as it is, i.e. requiring either `-n` or `-`, in accordance with the man/usage page.
> 
> That leaves us with the following:
> 
> * Indent the else block to make it more readable (this can be done as a second commit to keep the original diff obvious)
> * Update the man page to reflect this change
> 
> Other than that, the patch looks fine, after all. I'll reopen the PR, please update it with the above suggestions when you get a chance.



> OK, turns out I was wrong saying:
> 
> > What we need is to _always_ print to stdout, not a file.
> 
> The patch you proposed indeed does exactly that, I just got confused, apologies for that.
> 
> Also, while omitting `-` works with rpm2cpio, it's not in fact documented, so we might as well not bother with that in rpm2archive and keep it as it is, i.e. requiring either `-n` or `-`, in accordance with the man/usage page.
> 
> That leaves us with the following:
> 
> * Indent the else block to make it more readable (this can be done as a second commit to keep the original diff obvious)
> * Update the man page to reflect this change
> 
> Other than that, the patch looks fine, after all. I'll reopen the PR, please update it with the above suggestions when you get a chance.

Of course, I would like to add a manual page. The previous indent confused me

**Comment by dmnks** [comment]
> The indentation change belongs to the same commit: the code logic changes fundamentally and trying to avoid indentation changes only makes that logic harder to follow and review.

OK, it's not a refactoring change after all and also, one can always instruct git to ignore whitespace changes when viewing diffs, so yup, let's do it as one commit.

**Comment by dmnks** [comment]
> The previous indent confused me

See the above comments

**Comment by dmnks** [comment]
I tweaked your patch a little (removed some extra nesting and adjusted the man page a bit more) and submitted it as a separate PR #2285. Closing this one in lieu of that one. Thanks again!

**Pull request closed without merging**
