### PR TITLE
Update dnf options in Dockerfire for readability.

### PR DESCRIPTION
**Pull request by junaruga**
It looks better, isn't it?

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
if it would still work... ;)

```
Error response from daemon: Unknown instruction: DELTARPM=0
```

**Comment by junaruga** [comment]
Humm, just moment.

**Comment by junaruga** [comment]
Here document does not work ;)
At least, it can be supported from Docker 2.0.
Ref: `https://github.com/moby/moby/issues/1554#issuecomment-196544146`

```
RUN cat <<EOF >> /etc/dnf/dnf.conf
deltarpm=0
install_weak_deps=0
tsflags=nodocs
EOF
```

Brackets also does not work ;)

```
RUN (
  echo deltarpm=0
  echo install_weak_deps=0
  echo tsflags=nodocs
) >> /etc/dnf/dnf.conf
```

Sadly, finally only escape long line. ;)

**Comment by ignatenkobrain** [comment]
not really better, so closing =)

**Pull request closed without merging**
