### PR TITLE
Default to sqlite backend and remove support for BDB

### PR DESCRIPTION
**Pull request by pmatilai**
We all want to get rid of BDB, but in order to do that we have to pick a new default.

Sqlite has a proven track record over multiple decades in terms of compatibility and longevity, and is the "nobody ever got fired for..." choice in this space really. It's also developer friendly as the database is easy to inspect and a *lot* of people are familiar with it and it's API.

Ndb has its own benefits such as independence from external libraries for those who care about that, but the above is what matter more to me: even if the entire rpm community gets run over by a truck, there will still be plenty of people deeply familiar with sqlite around.

With the default changed, removing BDB itself now is a simple act. I wont be shedding a single tear over it, but it certainly is an end of an era.

### CODE REVIEW

**Comment by pmatilai** [comment]
> removing BDB itself now is a simple act

...or it *should* be. I had it all done locally but must've messed up something with git. Sigh.

**Review by Conan-Kudo — APPROVED** [review]
You beat me to it! BDB has served us well since the beginning, now it's time to say farewell...

**Comment by Conan-Kudo** [comment]
@pmatilai Squash your fixup commit into the other one, and I think it's good to go.

**Comment by pmatilai** [comment]
With the way this is going, I suspect there's one or two more BDB references lurking about somewhere :sweat_smile:

**Comment by pmatilai** [comment]
Two more BDB references, plus updated the configure script default for sqlite too.

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
@pmatilai Actually, shouldn't there be a SQLite requires in the rpm.pc file?

**Comment by pmatilai** [comment]
It's not a requirement, it's just the default. There should be a Libs.private entry for it though (but that missing is not really related to this PR)

**Comment by Conan-Kudo** [comment]
Since SQLite provides a pkgconfig file, it would use `Requires.private` instead, but I guess it can be handled outside of this.

**Comment by pmatilai** [comment]
Meh, yeah - it'd be a conditional requires just like eg zstd is. I pushed an intermediate version but lets deal with that elsewhere, this isn't getting convoluted enough as it is.

**Comment by Conan-Kudo** [comment]
@pmatilai I'm good with that. 👍🏾

**Comment by pmatilai** [comment]
:fireworks: :tada:

**Comment by Conan-Kudo** [comment]
🥳 🎆 🎉 🍾

**Pull request merged**
