### PR TITLE
Rpm 4.18.0 beta1 release

### PR DESCRIPTION
**Pull request by pmatilai**
I initially thought we'd accelerate the release cycle this time around and jump straight to rc from the alpha as there's nothing to put into the beta. But as I started putting this together it became quite clear there's easily enough fixes and even minor new features to warrant sticking to the original plan, which of course has the benefit of more reliable release cycle as well.

### CODE REVIEW

**Comment by nwalfield** [comment]
@pmatilai : I think the non-default Sequoia backend is not part of this.  What are the criteria for getting into 4.18?  I looked at the [roadmap](http://rpm.org/roadmap.html) and the internal OpenPGP parser is scheduled for removal in 4.19, but that is orthogonal, I think, to adding an alternate, non-default, backend.

**Comment by pmatilai** [comment]
4.18 is largely a done deal by now, this is just minor tweaks here and there. Remember the Sequoia backend involves axing a bunch of legacy APIs, which we can't do in 4.18 because we're committed to preserving the library soname there.

As it is, I don't see the internal parser getting *removed* in 4.19 yet, just deprecated.

**Comment by nwalfield** [comment]
> Remember the Sequoia backend involves axing a bunch of legacy APIs, which we can't do in 4.18 because we're committed to preserving the library soname there.

The Sequoia backend was written to be ABI compatible with the current ABI.  AFAIK, the only thing that changed was we added a few accessors so that rpm didn't have to look in the structs.

**Comment by nwalfield** [comment]
In other words: if the ABI changed, I'm pretty certain that is a bug that we should fix.  What do you think changed?

**Comment by nwalfield** [comment]
I can add those, if that is acceptable and the only issue.

**Comment by pmatilai** [comment]
Oh. I was under the impression (from some earlier discussion in a ticket) that these were particularly annoying to implement or something, and we removed them to clear the way for Sequoia. If I misunderstood and they'd be easy to add, then it would indeed be nice to have it in 4.18 already. But not this beta anyway, that'd have to be in an rc released which would be sometime in August. Besides those we'd need to pull in/backport the added APIs, but that's not a blocker. If you're interested in adding those, please open a new ticket to track Sequoia in 4.18, this isn't really the place for that discussion :sweat_smile:

**Pull request merged**
