### PR TITLE
Multi-db /var/lib/rpm and /var/lib/appstore isolation skeleton

### PR DESCRIPTION
**Pull request by xiangzhai**
# RPM Next
[RPM Next](https://github.com/AOSC-Dev/rpm#rpm-next) Multi-db /var/lib/rpm and /var/lib/appstore isolation skeleton implementation.

## Background
One day [Cjacker](https://github.com/cjacker) had an idea: there are OS layer (/var/lib/rpm) and AppStore layer (/var/lib/appstore) physical isolated. so rpm -ivh/-e only install/erase Apps into/from AppStore layer, OS is totally READ-ONLY. when installing Apps, check dependency in OS layer at first, if unsatisfied depend, then switch to AppStore layer for checking dependency again, if still unsatisfied depend, add dependency problem, otherwise installed Apps successfully.

## NOT container
It is NOT [xdg-app](https://github.com/alexlarsson/xdg-app) nor [limba](https://github.com/ximion/limba), but multi-db isolation try to forbid 3rd-party App pollute the core components of operating system.

## Goal
* keep rpm original command unbroken;                                              
* keep librpm original API unbroken;                                               
* just like Mac ***make install*** is still able to pollute OS layer.

Regards,
Leslie Zhai

### CODE REVIEW

**Comment by Arthur2e5** [comment]
Well, I think we should purge all README changes…

**Comment by xiangzhai** [comment]
> For now the App Store is simply located at /var/lib/appstore. Perhaps Apple will be unhappy with this.

+1

> Hey xiangzhai, db6 is released under AGPL. Nobody knows why Oracle did that but you might want to keep using db5.

Berkeley DB is really difficult to use, there are [sophisticated Wrapper](https://github.com/rpm-software-management/rpm/tree/master/lib/backend) and [Controller Interface](https://github.com/rpm-software-management/rpm/blob/master/lib/rpmdb.c) for rpm usage.

I prefer to use SQLite3, so I totally rewrote the pkgcache generation [APT-RPM](http://apt-rpm.org/scm/?p=apt.git;a=summary), it is quite simple to use SQLite table to store Package information about ***Requires*** and ***Provides*** for Building Dependency Tree ;-)

```
CREATE TABLE `Package` (
	`Name`	TEXT NOT NULL UNIQUE,
	`Version`	TEXT NOT NULL,
	`Release`	TEXT NOT NULL,
	`Arch`	TEXT NOT NULL,
	`IGroup`	TEXT NOT NULL,
	`Uri`	TEXT NOT NULL,
	`Requires`	TEXT,
	`Provides`	TEXT,
	`Md5`	TEXT,
	`Status`	INTEGER NOT NULL DEFAULT 0
);
```

**Comment by ffesti** [comment]
We'll twice a year someone comes up with some sort of dual/multiple rpmdb proposal. None of them so far got beyond answering the first main questions:

What's the use case? Would that actually work? Isn't this really the right solution to this problem?

Which typically go into some more detailed questions like:

If the system is readonly what about updates?
If the system is not read only what happens if updates are not compatible/in sync with the secondary database?

If you want to protect you system packages there are probably easier ways to do - depending what you are actually trying to defend against. Rogue admins? Badly build packages? Broken dependencies?

May be implementing repository pinning on the depsolver level (yum/dnf) is much more helpful for this. Or pinning the system packages - either with an rpm plugin or an yum/dnf plugin - or by adding a system meta package requiring the exact versions of all system packages.

Depending of what you exactly what to do these option are much easier to get implemented.

**Comment by xiangzhai** [comment]
> What's the use case? Would that actually work? Isn't this really the right solution to this problem?
For the Mac-alike close system, it provides System Update Daemon and rpm command without librpm. so no YUM/DNF available ;P

> If the system is readonly what about updates?

There is System Update Daemon use original RPM API to update /var/lib/rpm

> If the system is not read only what happens if updates are not compatible/in sync with the secondary database?

Just like Mac, when system update broken the dependency in the /var/lib/isoftapp, System Update Daemon will mark the broken APPs.

**Comment by ffesti** [comment]
I really can't see this changes going in upstream. Beside the duplication of a lot of code, duplication of the API there are lots of unresolved - probably even unnoticed - issues. Including but not limited to:

 * Support in dependency solvers
 * UI
 * Update requiring changes in both DBs
 * Obsoletes matching packages from both DBs
There are also serious doubts whether the added complexity really lowers the overall risks.

**Pull request closed without merging**
