### PR TITLE
Drop the experimental LMDB backend

### PR DESCRIPTION
**Pull request by pmatilai**
In the three years that LMDB support has been in the tree, and four
since upstream promised 1.0.0 in a couple of months, there have been
no upstream changes towards eliminating the key size limitations that
we need. And in the meanwhile it has become clearer that LMDB is not
the promised land it seemed on the outset, instead it has issues
like requiring the database size to be pre-determined (#902).

Drop support for LMDB, there's active development going on in the area
of database backends and we cannot afford to drag along an experimental
backend that is blocked on upstream design limitations and shows no signs
of moving forward. We can always bring it back if the upstream situation
changes.

### CODE REVIEW

**Comment by ffesti** [comment]
Looks like `lib/backend/lmdb.c` needs to be removed from `po/POTFILES.in`

**Comment by ignatenkobrain** [comment]
+1 on decision, did not check code though.

**Comment by ffesti** [comment]
Also +1 on the decision. I wonder if it is worth announcing it a bit more widely (rpm-list) in case some people(tm) are actually using it.

**Comment by pmatilai** [comment]
POTFILES.in fixed.

And yeah it deserves a clear mention in release notes and other announcements.

**Comment by pmatilai** [comment]
...and gone.

**Comment by Conan-Kudo** [comment]
@pmatilai Thanks for doing that! 👍

**Pull request merged**
