### PR TITLE
Filter Lua deprecation warnings based on the originating rpm version

### PR DESCRIPTION
**Pull request by pmatilai**
Issuing deprecation warnings on packages built long time ago is just antisocial behavior when the user is powerless to do anything about it.

When running scripts, pass the builder rpm version to Lua through the registry, and filter out the warnings when the package was built with an rpm version where these functions were not yet deprecated.
Usage through rpmlua and macros always gets warnings: those are things that can technically be fixed by the user.

The first commit is prerequisite refactoring to make this possible.

Thoughts? This could be considered the beginnings of poor mans symbol versioning for rpm embedded Lua.
Tests would need to be added of course.

### CODE REVIEW

**Comment by pmatilai** [comment]
I said this someplace else too, but: the thing is, I don't think we can actually proceed with the removal of these functions as originally planned. This stuff is used by very few packages but those very few happen to be corner stones of distros, and if we just remove the functions we make eg all current Fedora and RHEL versions uninstallable. That's just not acceptable really.

**Comment by ffesti** [comment]
if we don't actually remove the functions this is fine. We just need to issue the warnings in the last RPM version before removing them.

**Comment by pmatilai** [comment]
No, the point is that we need to warn on *all new usages* of these functions. Otherwise, we'll be in the same situation ten years from now and still can't remove those functions.

**Comment by ffesti** [comment]
OK, I could have worded that better. Yes, we need to issue a warning for all new usages. We will need to issue a warning to all usages the release before we actually remove the functions - with the hope that old usage has died out til then.

**Comment by pmatilai** [comment]
Right, that I can agree with: we need to turn the warnings back to the always warning mode before actually removing them, probably more than one release in advance.

**Comment by pmatilai** [comment]
Oh and to elaborate on the "poor mans symbol versioning" comment: what we could and probably should do is literally prevent the use of these functions in v6 packages. We now have (the beginnings of) means to track that.

**Comment by pmatilai** [comment]
Tests added, this is basically the MVP version that would be targeted at 4.20 backporting.
I'll file a separate ticket on disabling these for v6 entirely.

**Comment by alimirjamali** [comment]
> the point is that we need to warn on _all new usages_ of these functions to scare people away from using them.

Unfortunately this is working too good at scaring people. End-users could not fully understand if this is a package maintainer issue, an RPM bug, a DNF bug, a Fedora bug or their own fault. Very essential packages  [such as libgcc](https://src.fedoraproject.org/rpms/gcc/blob/rawhide/f/gcc.spec#_2429) are still  using posix.fork, .execute, etc. Here (Qubes OS), some users are scared to upgrade to Fedora 41 templates and prefer to stick with Fedora 40 while it is supported.

Maybe instead of [this line](https://github.com/rpm-software-management/rpm/pull/3270/files#diff-08a5b8f8eace58db333cc92adc4c18a0f875c2f953101c6152b632287510430cR1384), we could have something like:
```c
    "warning: %s(): .fork(), .exec(), .wait() and .redirect2null() are deprecated, package maintainer should use rpm.spawn() or rpm.execute() instead\n", func);
```

**Pull request merged**
