### PR TITLE
Pythoneggs cleanups

### PR DESCRIPTION
**Pull request by soig**
This clean up pythonegg and make it usable.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@soig Could you please check to see if these would apply to #35? I've done some refactoring there and I'd be happy to take in any changes authored by you to my pull request. I've also added compatibility for your `pythoneggs(X)(M)` format in Mageia there. I will happily accept PRs and patches to my branch: https://github.com/Conan-Kudo/rpm/tree/pydepgen (which will automatically be added to #35).

**Comment by soig** [comment]
On 17 January 2016 at 20:11, Neal Gompa (ニール・ゴンパ) <notifications@github.com>
wrote:

> @soig <https://github.com/soig> Could you please check to see if these
> would apply to #35
> <https://github.com/rpm-software-management/rpm/pull/35>? I've done some
> refactoring there and I'd be happy to take in any changes authored by you
> to my pull request. I've also added compatibility for your
> pythoneggs(X)(M) format in Mageia there. I will happily accept PRs and
> patches to my branch: https://github.com/Conan-Kudo/rpm/tree/pydepgen
> (which will automatically be added to #35
> <https://github.com/rpm-software-management/rpm/pull/35>).
>
​I would do the reverse: first committing obvious changes then committing
those who needs discussion​

**Comment by Conan-Kudo** [comment]
@soig I've reviewed your patches and merged them into mine and created a new PR. #50 has them combined.

The only patch not merged in is the patch for enabling the new dependency generator by default. I believe merging in the changes would be good, but having the dependency generator enabled by default would require more discussion.

**Comment by ffesti** [comment]
Added the fixes. Making the new dependency generator the default is probably going to be up to the distributions. May be we change the default later on.

**Pull request closed without merging**
