### PR TITLE
configure.ac: add linux-gnux32 variant to triplet handling

### PR DESCRIPTION
**Pull request by kanavin**
x32 is a 64 bit x86 ABI with 32 bit pointers.

### CODE REVIEW

**Comment by pmatilai** [comment]
We don't support x32 architecture elsewhere so it seems pointless to add it here. If the plan is to add support for it, then those should preferably come as one PR so we can see where its going on the whole. So far we've been reluctant to add x32 as there hasn't been any users for it at all. Is some distro planning to actually support it now?

**Comment by kanavin** [comment]
Yocto has supported x32 for a long time and still does. We do include runtime tests for rpm/dnf on that target as well:
https://autobuilder.yoctoproject.org/typhoon/#/builders/57/builds/5587/steps/14/logs/stdio
```
RESULTS - dnf.DnfBasicTest.test_dnf_help: PASSED (1.71s)
RESULTS - dnf.DnfBasicTest.test_dnf_history: PASSED (0.78s)
RESULTS - dnf.DnfBasicTest.test_dnf_info: PASSED (0.73s)
RESULTS - dnf.DnfBasicTest.test_dnf_search: PASSED (0.74s)
RESULTS - dnf.DnfBasicTest.test_dnf_version: PASSED (0.67s)
RESULTS - dnf.DnfRepoTest.test_dnf_exclude: PASSED (6.70s)
RESULTS - dnf.DnfRepoTest.test_dnf_install: PASSED (1.23s)
RESULTS - dnf.DnfRepoTest.test_dnf_install_dependency: PASSED (1.61s)
RESULTS - dnf.DnfRepoTest.test_dnf_install_from_disk: PASSED (2.85s)
RESULTS - dnf.DnfRepoTest.test_dnf_install_from_http: PASSED (1.99s)
RESULTS - dnf.DnfRepoTest.test_dnf_installroot: PASSED (10.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_makecache: PASSED (0.81s)
RESULTS - dnf.DnfRepoTest.test_dnf_reinstall: PASSED (0.89s)
RESULTS - dnf.DnfRepoTest.test_dnf_repoinfo: PASSED (0.72s)
...
RESULTS - rpm.RpmBasicTest.test_rpm_help: PASSED (0.12s)
RESULTS - rpm.RpmBasicTest.test_rpm_query: PASSED (0.25s)
RESULTS - rpm.RpmBasicTest.test_rpm_query_nonroot: PASSED (1.19s)
RESULTS - rpm.RpmInstallRemoveTest.test_check_rpm_install_removal_log_file_size: PASSED (5.26s)
RESULTS - rpm.RpmInstallRemoveTest.test_rpm_install: PASSED (0.50s)
RESULTS - rpm.RpmInstallRemoveTest.test_rpm_remove: PASSED (0.23s)
```

**Comment by kanavin** [comment]
This is a regression fix for 4.17.1, not a new feature - at least for us.

**Comment by pmatilai** [comment]
I don't see how 4.17.1 would affect anything there, unless of course it's some autofoo version difference. I also don't see how it would work without additional patches anywhere because x32 isn't listed in `installplatform` or `rpmrc`.

**Comment by pmatilai** [comment]
What I'm trying to say here is that since we appear to have a distro supporting x32, and since that would seem to require more patches than this on here, just bring 'em on.

**Comment by kanavin** [comment]
Without this patch, 4.17.1 breaks thusly (and 4.17 does not):
```
 | configure: error: unrecognized GNU build triplet linux-gnux32
```

But there are no other x32-specific patches. If you want to see on-target config files we use, let me know which ones.

**Comment by Conan-Kudo** [comment]
There should be at least an x32 ABI patch for elfdeps, otherwise this is just broken. #1038 includes support for it, for example.

**Comment by kanavin** [comment]
It does work for installing packages. But yes, we do not test building packages on targets.

**Comment by Conan-Kudo** [comment]
We're also missing an architecture class for x32 packages, and rpmfc needs to know how to classify x32 ABI packages.

**Comment by pmatilai** [comment]
> It does work for installing packages. But yes, we do not test building packages on targets.

People have different perceptions of "works", but I'm moderately surprised that it would work by any standard without futher patches. Which architecture packages are you feeding it, and how are you building them? Output of `rpm --showrc | head -20` from a x32 system would be interesting.

**Comment by kanavin** [comment]
> > It does work for installing packages. But yes, we do not test building packages on targets.
> 
> People have different perceptions of "works", but I'm moderately surprised that it would work by any standard without futher patches. Which architecture packages are you feeding it, and how are you building them? Output of `rpm --showrc | head -20` from a x32 system would be interesting.

It's basically an x86_64 system that has been extended to accept x86_x32 packages, and with root filesystem composed entirely from the latter:

```
ARCHITECTURE AND OS:
build arch            : qemux86_64
compatible build archs: qemux86_64 noarch
build os              : Linux
compatible build os's : linux
install arch          : qemux86_64
install os            : Linux
compatible archs      : qemux86_64 all any noarch x86_64_x32
compatible os's       : linux
```

```
root@qemux86-64:~# cat /etc/rpmrc
arch_compat: qemux86_64: all any noarch x86_64_x32 qemux86_64
buildarch_compat: qemux86_64: noarch
```

And yes it's Yocto :) which means we build binaries outside of rpm, and use rpm only to package them and then indirectly via dnf to form a root filesystem from those packages (yes, we patch rpm to short circuit the build, and I know it's a 'rpm crime').

**Comment by kanavin** [comment]
Here's a sample autogenerated .spec and resulting packaging log from the build host (which is a regular x86_64 or aarch64 machine).
[attr.spec.txt](https://github.com/rpm-software-management/rpm/files/9308904/attr.spec.txt)
[log.do_package_write_rpm.txt](https://github.com/rpm-software-management/rpm/files/9308905/log.do_package_write_rpm.txt)

**Comment by Conan-Kudo** [comment]
Yeah, so it works because you have a custom arch defined: `x86_64_32`. We don't have that. Ideally we'd have an `x86_64-x32` arch for exactly this purpose.

**Comment by kanavin** [comment]
> Yeah, so it works because you have a custom arch defined: `x86_64_32`. We don't have that. Ideally we'd have an `x86_64-x32` arch for exactly this purpose.

Let's try a different angle: should rpm agree to be (cross) compiled for a target that it doesn't know about? The patch could perhaps be reworked, so that rpm doesn't reject triples that don't match a hardcoded list.

**Comment by pmatilai** [comment]
It's not so much the change itself, it's the lack of rationale needed to understand why this is needed all of a sudden and why it looks like an incomplete "support x32" patch. So okay you have a custom `rpmrc`, that explains how it works at all. That's what I was trying to dig out above.

And now we've learned that this is to address a build regression in 4.17.1, which makes it something entirely different. I didn't realize we had any changes to this area in that release, but looking closer this check is explicitly added in 1cdb72ae48b7ba689c5c79118f4f0c1b4ffe6b7c and then cherry-picked into 4.17.1. And with that information, the picture starts to form. Just explain the matter properly in the commit message and I've no problem merging it.

Tagging @dmnks as we'll probably need a .1 regression release for 4.17.1 anyway and this matter needs to be considered there too.

**Comment by Conan-Kudo** [comment]
> > Yeah, so it works because you have a custom arch defined: `x86_64_32`. We don't have that. Ideally we'd have an `x86_64-x32` arch for exactly this purpose.
> 
> Let's try a different angle: should rpm agree to be (cross) compiled for a target that it doesn't know about? The patch could perhaps be reworked, so that rpm doesn't reject triples that don't match a hardcoded list.

The answer is no: it should always know the targets, because that data is important for creating a correct RPM with the correct architecture information.

**Comment by dmnks** [comment]
> > Let's try a different angle: should rpm agree to be (cross) compiled for a target that it doesn't know about? The patch could perhaps be reworked, so that rpm doesn't reject triples that don't match a hardcoded list.
> 
> The answer is no: it should always know the targets, because that data is important for creating a correct RPM with the correct architecture information.

Yet, we used to support compilation for targets we otherwise don't know about until not too long ago (4.17.1). Apparently, some folks (Yocto in this case) have successfully done this until we broke it for no apparent reason with commit 1cdb72ae48b7ba689c5c79118f4f0c1b4ffe6b7c.

Installing and creating RPMs are two different things and it seems like there's no reason why we couldn't allow the former without the latter, although in that case, we should somehow prevent the build process from creating `rpmbuild`, shouldn't we?

Either way, I don't think it makes sense to specifically whitelist `linux-gnux32`. Instead, we should either completely revert 1cdb72ae48b7ba689c5c79118f4f0c1b4ffe6b7c or just "own it" and let these edge cases be dealt with by patching `configure.ac` in their environment.

**Comment by kanavin** [comment]
I've rewritten the commit message (but left the content of the commit unchanged). If you'd rather do a revert of the original regression, let me know.

**Comment by dmnks** [comment]
Thanks for the effort, but we decided to revert the original patch altogether from the 4.17.x line, after all. The upcoming regression update 4.17.1.1 will include this revert, tracked in #2168. I'll close this one now.

**Comment by kanavin** [comment]
Thanks, but it's likely we'll skip 4.17.1.1, and go straight to 4.18.0. How is the situation going to be addressed there? Is it going to be reverted in both branches?

**Comment by dmnks** [comment]
OK, we've ended up merging your PR into master so 4.18.0 will carry it.

The revert will only be done in 4.17.1.1 as that's a maintenance line that's supposed to be kept minimal and conservative, but the end result will be the same for your use case.

Thanks again!

**Pull request closed without merging**
