### PR TITLE
Add several new optional URL tags

### PR DESCRIPTION
**Pull request by stanislav-brabec**
There are tools that help to prepare new spec or just visualize the RPM  contents. There are areas, where RPM does not yet provide the info, and developers often use spec file comments to store the vital data. These are especially:
- The referrer of Source files (the download URL).
- The repository URL.
- And user space tools would like to display the URL for the translation  contribution.

Here is a set of three new optional tags. All of them accept arrays, so more URLs can be specified.

Mailing list references:
[[Rpm-maint] [PATCH 0/4] Add several new optional URL tags](http://lists.rpm.org/pipermail/rpm-maint/2022-April/020366.html)
[[Rpm-maint] [PATCH 1/4] Add TranslationURL tag](http://lists.rpm.org/pipermail/rpm-maint/2022-April/020367.html)
[[Rpm-maint] [PATCH 2/4] Realign output of rpm --info](http://lists.rpm.org/pipermail/rpm-maint/2022-April/020368.html)
[[Rpm-maint] [PATCH 3/4] Add RepoURL tag](http://lists.rpm.org/pipermail/rpm-maint/2022-April/020369.html)
[[Rpm-maint] [PATCH 4/4] Add DownloadURL tag](http://lists.rpm.org/pipermail/rpm-maint/2022-April/020365.html)

### CODE REVIEW

**Comment by pmatilai** [comment]
Adding tags is cheap, the problem is motivating people to actually fill them. We already have a RepoURL equivalent in VCS, but very few packages are actually using it. Of > 22K packages in Fedora, 109 have it...

**Comment by Conan-Kudo** [comment]
> Adding tags is cheap, the problem is motivating people to actually fill them. We already have a RepoURL equivalent in VCS, but very few packages are actually using it. Of > 22K packages in Fedora, 109 have it...

We don't use it because we don't know what to do with it. People are confused on whether it should be upstream code (substituting for Source) or downstream packaging code.

**Comment by pmatilai** [comment]
> We don't use it because we don't know what to do with it. 

Right, that's the other problem with these informational tags. What does RepoURL refer to? Is it the repository where this package is to be found, upstream source code, distro repo or what? I assumed upstream code, but that's also assuming a whole bunch of other things. Ditto for download - is it for the package, upstream, source...? 

At the very least the these need to be documented in [docs/manual/tags.md](https://github.com/rpm-software-management/rpm/blob/master/docs/manual/tags.md) to be considered for merging (plus test-suite failure fixed). I'm not vehemently opposed to adding such tags, just quite reluctant because I've seen so many well-inteded informational tags added and ending up landfill in the rpmscape.

**Comment by pmatilai** [comment]
> People are confused on whether it should be upstream code (substituting for Source) or downstream packaging code. Unlike Debian's Vcs-* tags, the VCS tag has no specification.

I almost said "but it's at least documented now", only the documentation is totally vague too ("Package source code VCS location") :laughing: On purpose I might say, because nobody knows what it means. I remember also being reluctant to add that tag because of that.

**Comment by stanislav-brabec** [comment]
All your comments are valid. Before writing a proposed documentation, I would like to discuss it here.

**RepoURL** should contain upstream VCS repository URL. And actually, I think that it should contain an URL that could be read without credentials (if possible), i. e. https:// in case of GitHub, and not git@ URL. It is intended to be picked by a third party robots capable to perform a version update.

If the VCS tag means exactly the same as my proposed RepoURL, I would withdraw this addition proposal. I'll check the documentation. If VCS tag means a reference to the repository with the spec file and other package source files, the difference should be documented.

Actually, openSUSE Build Service already contains thing named services, and the OBS services can directly use this tag. See [openSUSE:Build Service Concept SourceService](https://en.opensuse.org/openSUSE:Build_Service_Concept_SourceService).

It could be array, as Source could be array as well. Note: I am not sure, whether optional tags could use RepoURL0: RepoURL1:, or only RepoURL: URL0 URL1 is allowed. If the first one is possible, the code needs change.

**TranslationURL** should contain top directory of the particular translation project. It is indented for RPM visualizers. It  It should refer to a user-friendly translation front end, not to the source repository, not to the translation VCS. It could also refer to a page with instructions, how to participate in the project translation. If there is no such translation project or page, `TranslationURL` should not be used.

The tag could contain an array, as there are projects that have more translation domains, but the translation server has no covering URL. The example is The GIMP.

**DownloadURL** should refer to the top directory of the download section, so an easy robot could find the latest version available there.

**Comment by ffesti** [comment]
To me it looks like the RepoURL and VCS are basically the same. We really need to improve the docs on the VCS tag (and probably a lot others).

I am a bit torn on making the tags string arrays. On a technical basis this is the right thing to do and we do have too many tags that should probably be arrays but are not. Otoh querying arrays is a pain if you are not predefined short hands (like `rpm -qi`). So for things that are meant for human consumption putting multiple links in the same string may be a better option - even if it hurts my software engineer's heart.

For descriptions in the tags page, we need to come up with something more concise - preferably with just one (half) sentence. Putting the word "upstream" in there is probably going a long way to clear up possible confusion.

**Comment by pmatilai** [comment]
> For descriptions in the tags page, we need to come up with something more concise - preferably with just one (half) sentence. 

I'm not sure I agree with that. The reason the existing documentation is terse is just that I wrote them all up in a single go with the intent of expanding later, not that they should be that way.

**Comment by ffesti** [comment]
#2064 tries to clarify the VCS tag. It also may give a better example on the level of detail such documentation can be. Panu is ofc  right that they don't need to be super sort. We should not leave important information out just just to save screen space.

**Comment by ffesti** [comment]
OK, turns out normal tags in the spec file do not really support array data types. So I guess switching them to normal strings is  the way to go. Renaming them to TranslationURLs and DownloadURLs might be a way to signal that they contain more than one URL but I am fine with the current name also.
RepoURL is now redundant. The other two tags need to be added to `tests/rpmgeneral.at` make the test suite pass and to `docs/manual/tags.md`.
I agree with the overall purpose of the tags. The description of the TranslationURL can surely be shorter in the documentation can surely be shorter than here.

**Comment by pmatilai** [comment]
RPMTAG_TRANSLATIONURL and RPMTAG_UPSTREAMRELEASES added via #2083 now. Thanks for the patch.

**Pull request closed without merging**
