### PR TITLE
Implement a native C++ macro API + use it to replace manual macro locking

### PR DESCRIPTION
**Pull request by pmatilai**
This started with the innocent intention of making a couple of C++ string expand variants available, but then I got carried away... 

There are no added tests because this is all covered by existing functionality testing - the last commit effectively adds a test for the expand variant accepting a vector.

### CODE REVIEW

**Comment by pmatilai** [comment]
Got carried away enough that I forgot to explain a key benefit:
This gives the caller the ability to control locking, so if you need to do 1000 expands in a loop you no longer need to go through lock+unlock cycles for each as it is with the C versions. Gaining those benefits of course requires changing callers to the new API, I've only converted a couple of calls here for examples and to provide tests for the string/vector variants.

**Comment by pmatilai** [comment]
> The macro class needs a bit more doc strings.

I don't disagree, but we don't traditionally have much in the way of docs for internal APIs. What do you want to see documented, the locking scheme? 

>  It is kinda weird that it is basically just a lock around the macro context. Not that there is anything wrong with that - it's just weird

This is basically how you want a locked resource to be handled in C++. It's a different paradigm from what we've had, sure. The various fooAcquire() things were a kind of emulation of this though.

**Comment by ffesti** [comment]
May be just add a two line comments before or just in the class declaration stating that this si for getting a lock on a macro context and use it to do macro stuff with it.

**Comment by pmatilai** [comment]
Added a bunch of notes on the overall design + notes on API differences where they exist.
Also added native expand_numeric() variants which I had somehow missed in the first round.

**Comment by ffesti** [comment]
This looks do to me now. May be @dmnks can have a look and second opinion before merging.

**Comment by dmnks** [comment]
The first commit seems to have forgotten to update the `doExpandMacros()` call in `rpmExpandMacros()` where it still passes a C string (despite the function expecting a C++ string reference instead). The call is later refactored in a followup commit in this PR but maybe it should still be fixed for bisectability.

**Review by dmnks — APPROVED** [review]
Other than the note above, looks good to me.

**Comment by pmatilai** [comment]
Oh, thanks for spotting, I'll fix it up.

**Comment by dmnks** [comment]
> The call is later refactored in a followup commit

Ehm, I take that back, it's not fixed in the latest commit either, it still passes on a C string :sweat_smile:

**Comment by pmatilai** [comment]
Right, I initially thought it was something else.

This isn't a problem at all, C++ will merrily construct temporary string objects in a case like this. The other direction wont work though :sweat_smile:

**Comment by dmnks** [comment]
Ack, I wondered if that was the case, thanks :smile:

**Pull request merged**
