### PR TITLE
Properly escape %__gpg_sign_cmd

### PR DESCRIPTION
**Pull request by DemiMarie**
%__gpg_sign_cmd needs to be able to cope with strange characters in e.g.
%_gpg_name.  Use the builtin shescape macro to make this
straightforward.  Also rip out the old (and commented-out)
%__gpg_verify_cmd.

### CODE REVIEW

**Comment by pmatilai** [comment]
Uff, no.

Most of that stuff is rpm controlled, otherwise doesn't need escaping, and are required to be present so conditionals have no place in there. Ie it adds a whole lotta crud for no benefit whatsoever. %_gpg_name *maybe*, but convincing me would require a legit example of where the escape would be needed.

**Comment by DemiMarie** [comment]
> Uff, no.
> 
> Most of that stuff is rpm controlled, otherwise doesn't need escaping, and are required to be present so conditionals have no place in there. Ie it adds a whole lotta crud for no benefit whatsoever. %_gpg_name _maybe_, but convincing me would require a legit example of where the escape would be needed.

`%_gpg_name` can be basically anything; it’s arbitrary freeform text.  A person might have `` ` `` or `$` in their name for all I know, and RPM needs to handle that properly.  It also may not be set when using the RPM libraries.  `%__signature_filename` can also be just about anything, though it must end in `.sig`.  For instance, currently RPM fails to sign a file with a space in its name:

```
tests/data/RPMS/hello-2.0-1.i686 .rpm:
gpg: can't open '.rpm.sig': No such file or directory
gpg: signing failed: No such file or directory
error: gpg exec failed (2)
```

That leaves `__plaintext_filename` and `_gpg_digest_algo`.  For consistency, I decided to quote them as well.  Your point about the conditionals stands.

**Comment by pmatilai** [comment]
Well I guess nobody puts spaces into rpm filenames. Quoting the filenames is okay, but doing it for digest_algo is just silly, at that rate we could just wrap the entire macros.in in %{shescape}.

**Comment by pmatilai** [comment]
Okay, thanks for the patch!

**Pull request merged**
