### PR TITLE
Add new plugin slots for pre/post chroot events

### PR DESCRIPTION
**Pull request by pmatilai**
These pre/post hooks get called before and after every chroot() call rpm makes. The initial inspiration came from the now removed experimental non-privileged chroot support with unshare() but this is probably an interesting boundary for various other purposes too.

### CODE REVIEW

**Comment by ffesti** [comment]
Looks good and pretty straight forward. May be should get a test case.

It might also be a good idea to point out that these are called even when running without --root. Technically we omit the chroot call in this case but the hoooks are ofc executed no matter what (as they should be)

**Comment by pmatilai** [comment]
> Looks good and pretty straight forward. May be should get a test case.

Yep. I actually have a test-case written in the form of "plugin development" test, but it needs some cmake infra bits first. But, this PR isn't in any particular hurry.

> It might also be a good idea to point out in the docs that these are called even when running without --root. Technically we omit the chroot call in this case but the hooks are ofc executed no matter what (as they should be)

Um, no they don't. rpmChrootIn() and rpmChrootOut() do always get called but they return with a no-op from the first condition.

**Comment by pmatilai** [comment]
And now with a testcase.

**Comment by pmatilai** [comment]
The more I sleep on this, the less convinced I become that this is a good idea. Quite the contrary actually.

That instinct is rarely wrong, so I'm canceling this PR. If at some point an actual use-case presents itself, we can always re-evaluate.

**Pull request closed without merging**
