### PR TITLE
DWARF-5 support in debugedit

### PR DESCRIPTION
**Pull request by pmatilai**
Resubmitting patches posted on rpm-maint: http://lists.rpm.org/pipermail/rpm-maint/2021-February/016462.html

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
How do I test this "in the real world"? The code looks fine (insomuch as debugedit code usually does...)...

**Comment by pmatilai** [comment]
AIUI this has been real-world tested in rawhide for a few weeks now...

**Comment by pmatilai** [comment]
So... some of this has been reviewed in #1332 months ago and the rest has been battle-tested in rawhide for several weeks now, I don't think this PR will get any better by "letting it breath" here some more :sweat_smile:

**Comment by pmatilai** [comment]
Thanks for the patches @jankratochvil and Mark!

**Comment by jankratochvil** [comment]
The patchset regressed against my version as it no longer tests rpmbuild compatibility with LLVM product as required by paying customers of Red Hat company.

**Comment by rpm-maint** [comment]
On Mon, 2021-02-15 at 20:58 -0800, Neal Gompa (ニール・ゴンパ) wrote:
> How do I test this "in the real world"? 

See also the new testcases, which are really just like the old
testcases. Before the patch running debugedit on a binary compiled with
-gdwarf-5 would not work, or not correctly, missing some sources and/or
not rewriting base/dest paths. Now it does.

When using gcc 11 (pre-release) you get to test it immediately when
using -g. Because gcc 11 defaults to DWARF5. That is why the testsuite
now also has some explicit -gdwarf-4 testcases. So the code is tested
using either DWARF4 or DWARF5, independent of what the used compiler
defaults to.

Cheers,

Mark

**Comment by rpm-maint** [comment]
On Mon, 2021-02-15 at 23:07 -0800, Panu Matilainen wrote:
> AIUI this has been real-world tested in rawhide for a few weeks
> now...

Yes, it has, but admittedly a slightly different patch set, because
that is using rpm 4.16.1.2
https://src.fedoraproject.org/rpms/rpm/tree/f34
https://code.wildebeest.org/git/user/mjw/rpm/log/?h=gcc-dwarf5-4.16.1.2

**Comment by rpm-maint** [comment]
Hi Jan,

On Tue, 2021-02-16 at 00:16 -0800, Jan Kratochvil wrote:
> The patchset regressed against my version as it no longer tests
> rpmbuild compatibility with LLVM product as required by paying
> customers of Red Hat company.

Unfortunately they did because I rewrote the tests so they didn't
require the llvm-toolset tools to run and made them independent of the
version of DWARF emitted by the compiler so that they work using either
older or newer gcc and binutils versions installed on the system.

Untested, but you can probably improve on that experience by changing
the gcc invocations inside the RPM_DEBUGEDIT_SETUP m4 macro (which is
just a shell script snippet) to use ${CC} instead. That should pick up
the CC setup by configure. That might also help people trying to build
and test rpm in a cross-compiler situation.

Cheers,

Mark

**Comment by jankratochvil** [comment]
Could you rather point what was incomplete on the previous testcases than to screw it up? You removed the only part that matters.

**Comment by rpm-maint** [comment]
Hi Jan,

On Tue, 2021-02-16 at 01:37 -0800, Jan Kratochvil wrote:
> Could you rather point what was incomplete on the previous testcases
> than to screw it up? You removed the only part that matters.

I didn't screw up. I simply didn't use that part. But wrote some new
testcases based on the existing tests, just with explicit -gdwarf-4 and
-gdwarf-5 settings instead of tweaking the compiler used or needing new
tools in the tests. The reason I didn't use the testcases you wrote was
simply because they depended on llvm tooling being present and you said
you didn't care about making them work with gcc. I just happened to be
interested in testing with gcc, so I had to write some new testcases to
make sure the new functionality worked as expected.

**Comment by jankratochvil** [comment]
> The reason I didn't use the testcases you wrote was simply because they depended on llvm tooling being present and you said you didn't care about making them work with gcc.

gcc did not support the needed functionality the time when I was implementing it. I sure do not care at all about gcc (like the rest of the world) but that was not the reason why I did not include the testcases for gcc. Running the tests with both gcc and clang would be a trivial extension of my testcases instead of dropping them all and replacing them by your incomplete ones.

**Pull request merged**
