### PR TITLE
[RFC] Make "%patchlist -f patches" work.

### PR DESCRIPTION
**Pull request by vathpela**
This adds a -f argument to %patchlist, similar to that for %files.

There is no limit to how many patchlist files you specify, and doing so
does not restrict the use of an inline patch list.  Patches get added
from the leftmost list to rightmost, and any patches listed below get
added after that.

v2 (ef44ff1): fixed EXTRA_DIST for the .spec file
v3 (cf7c952): reworked addFilesFromList() to be more like readFilesManifest()

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Wouldn't this also make sense for `%sourcelist` too?

**Comment by vathpela** [comment]
> Wouldn't this also make sense for `%sourcelist` too?

Yeah - and if you look at the code, it does it for both, I just didn't mention one in the commit message.

**Comment by Conan-Kudo** [comment]
@vathpela Could you adjust the commit message to indicate that both get this enhancement?

**Comment by pmatilai** [comment]
Nothing against adding -f support, but this adds third variant of essentially the same code that is in readFilesManifest() and addFileToTag(), with its own pecularities (at least missing %__file_name macro handling), when we're trying instead to eliminate these redundancies across the board. 
I'd also rather see the file contents appended to the same array that parseLines() originally produces to have just one place where addSource() is called for this, similarly to what readFilesManifest() does. The file reading logic from readFilesManifest() could probably be fairly easily be split into a separate helper shared between all these variants (similar to parseLines()), but I do understand if you're not interested in such a refactor job.

I also wonder if it's ever sane to have an empty patches/source file. In case of %files it's permitted mostly due to historical reasons IIRC, but this is probably different.

**Comment by pmatilai** [comment]
The file reading part refactored to a (more) generic helper in PR #886

**Comment by pmatilai** [comment]
The discussion already moved into  #1043 so we may as well close this one.
Thanks for the initial patch though!

**Pull request closed without merging**
