### PR TITLE
Add popt to Requires.

### PR DESCRIPTION
**Pull request by kloczek**
Fixed https://github.com/rpm-software-management/rpm/issues/939

### CODE REVIEW

**Comment by kloczek** [comment]
This is PR against master but probably the same should be done for other active branches.
Should I create separated PRs?

**Comment by Conan-Kudo** [comment]
@kloczek Nah, @pmatilai will take care of it.

**Comment by pmatilai** [comment]
This effectively sets our popt version requirement to >= 1.16 from the current >= 1.13.
It's not necessarily a bad thing (1.16 wasn't exactly released yesterday), but such a thing needs to be a conscious decision and documented appropriately in the commit message and INSTALL.

**Comment by pmatilai** [comment]
To elaborate a bit, the reason this bumps popt version dependency to 1.16 is that older versions did not *have* the pkgconfig file, and so cannot satisfy the dependency. The rpm.pc was added long before popt added its own, which is the main reason it's not there now.

Expressing that dependency after 20+ years of existence is not an urgent issue and is not enough of a reason in itself to bump the version dependency. There are other features there that we could use, but none of them seem important enough to justify the dependency version bump alone.

**Comment by kloczek** [comment]
IIRC on rpm5.org last time I saw popt 0.17 which had way more freshen translations (and more translations) and all .po files converted to UTF-8 + few minor code cleanups.
Looks like rpm5.org domain disappeared :/
If that tree still is somewhere it would be good to merge all those changes.
I should have somewhere some tar.gz with 0.17 (will try to find it later).

**Comment by Conan-Kudo** [comment]
@pmatilai I think it's fine for us to raise to popt-1.16. The only distributions currently supported that have versions older than that are EL6 and EL7. Even SLE 12 has popt-1.16. On the Debian/Ubuntu side, they've had it for quite a long time, going back to Ubuntu 12.04.

**Comment by pmatilai** [comment]
Yes, the version is not a problem in itself, 1.16 is pretty long in the tooth already, it's just that I can't bring myself to justify bumping that requirement for nothing. So I think this goes on hold until there's some more concrete reason for bumping the requirement, such as using a new API from popt.

**Comment by pmatilai** [comment]
Okay, we got a brand new popt out there for a while now, might as well get this over with. It's not like anybody is really dependent on popt older than 1.16. Since there's now a conflict, and the delay is really our fault, handling this by myself via #1524.

Thanks for the patch!

**Pull request closed without merging**
