### PR TITLE
Add a --salvagedb option to the rpmdb tool

### PR DESCRIPTION
**Pull request by mlschroe**
This can be used to recover as much data as possibly from a terminally broken database. It is currently only supported for the 'ndb' database.

This method is currently hidden from the API by using a macro to select salvage mode. If it should be more exposed, we can add a rpmtsSalvageDB() method.

### CODE REVIEW

**Comment by pmatilai** [comment]
I'm not all that familiar with ndb internals: how is this different to the regular --rebuilddb just skipping any headers it finds invalid? Or to turn the question around: is there a reason why this could/should not be used on all --rebuilddb operations (on ndb)?

**Comment by mlschroe** [comment]
No, there's a (very) small chance that it picks up entries that have been deleted. It's like the .recover command of the sqlite cli:

Like the ".dump" command, ".recover" attempts to convert the entire contents of a database file to text. The difference is that instead of reading data using the normal SQL database interface, ".recover" attempts to reassemble the database based on data extracted directly from as many database pages as possible. If the database is corrupt, ".recover" is usually able to recover data from all uncorrupted parts of the database, whereas ".dump" stops when the first sign of corruption is encountered.

BerkeleyDB has a db_recover utility for this. My initial plan was to also create a ndb_recover tool, but then I realized it was way easier to integrate it into the rpmdb command.

**Comment by pmatilai** [comment]
Right, I'm by no means opposed to this, and integrating with rpmdb is certainly the way to go, rather than strange external tools. Was just curious about the concrete difference.

Can you update the commit message to elaborate a bit on how it works and possible side-effects, at least that part about deleted entries reappearing? GH pull request discussion might get lost but commit messages are forever...

**Comment by mlschroe** [comment]
Oh, I'm sorry. I forgot about that commit message change you requested.

**Pull request merged**
