### PR TITLE
Mktree tweaks, volume I

### PR DESCRIPTION
**Pull request by dmnks**
Please see the commit messages for details.

### CODE REVIEW

**Comment by dmnks** [comment]
Hmm, maybe just storing the image in `~/.local/share/...` would make things simpler than traversing git worktrees. We only need one per system, after all.

Also, we might as well just use the user-specific DNF cachedir in `/var/tmp/dnf*`.

I'll fix this. Converting to draft in the meantime.

**Comment by dmnks** [comment]
... except that would leave all kinds of data around the filesystem, which is not nice. We want to keep all test-related data contained within the RPM checkout if possible. Also, we'd have to come up with some kind directory name to put under `~/.local/share/` (`containers` is already taken by podman, heh) and so on.

I need to sleep on this, but may just end up going with the current approach :laughing:

**Comment by dmnks** [comment]
OK, slept on it, let's go with the original approach, i.e. commit 1c94ddb065e2e9625e0d8ab0f1efde6a4042459c. It's better to just keep things tidy.

**Comment by pmatilai** [comment]
(merged before you change your mind again :smile: )

**Pull request merged**
