### PR TITLE
Trying to upstream debian patches: Do not use bashism for gettext

### PR DESCRIPTION
**Pull request by KOLANICH**
There are no translations anyway...

https://salsa.debian.org/pkg-rpm-team/rpm/raw/master/debian/patches/bashism.patch

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
It'd probably be better to use a POSIX sh-compatible way to use gettext instead of straight up dropping internationalization capability.

**Comment by KOLANICH** [comment]
Even though the commit message looks like this (it have been inherited from the patch file) I don't see this patch removing any calls. I can guess that the most of the patch got missing (already merged?) but the text haven't been changed.

**Comment by Conan-Kudo** [comment]
@KOLANICH I'd rather have the link to the Debian patch file removed from the commit message. It's not particularly important...

**Comment by KOLANICH** [comment]
>it'll be a dead link if this is merged.

There is a backup on WebArchive now. We all know that if we see a dead link we should check WebArchive for it :)

**Comment by Conan-Kudo** [comment]
@KOLANICH That's really not the point. And webarchive systems do not necessarily have this indexed.

The correct thing to do here would be to change the commit to have relevant information:

```
$ git commit --amend --author="Michal Čihař <nijel@debian.org>" --date="Tue, 30 Dec 2014 11:55:15 +0100"
```

With the following commit message:
```
Do not use bashism for gettext (DebBug:772404)

There are no translations anyway...
```

**Comment by pmatilai** [comment]
Yup, commit messages must be self-contained. Providing external links for additional background data such as originating bug report is fine, but not sufficient.

**Comment by Conan-Kudo** [comment]
@KOLANICH I'd rather you use the Debian bug reference than the patch URL. We _have_ the patch, after all.

**Comment by pmatilai** [comment]
Yes, the patch URL is uninteresting and irrelevant, a link to the *bug* would be relevant. Also the "original message" and quotation just makes it unnecessarily strange. Just do as @Conan-Kudo requested in https://github.com/rpm-software-management/rpm/pull/984#issuecomment-570160992, thanks.

**Comment by pmatilai** [comment]
Merged via #1006 . Thanks for the effort of bringing this upstream.

**Comment by KOLANICH** [comment]
Thanks for merging it :)

**Pull request closed without merging**
