### PR TITLE
Replace fakechroot with proper container technology

### PR DESCRIPTION
**Pull request by dmnks**
Use [Bubblewrap](https://github.com/containers/bubblewrap) to isolate the test-suite from the host and/or individual tests from each other. The containers run on top of an OS filesystem tree (image) with the local RPM checkout built and installed. [OverlayFS](https://docs.kernel.org/filesystems/overlayfs.html) is used to create lightweight snapshots for the tests.

The tree creation method (*mktree* script) is made pluggable so that e.g. the native package manager in the host OS can be used. In this PR, we provide three backends: one for Fedora that uses DNF, one for Podman that uses the bundled Dockerfile, and one that reuses the root filesystem (for use in disposable containers and VMs). Contributions adding backends for other Linux distributions are welcome.

### CODE REVIEW

**Comment by pmatilai** [comment]
Hmm, `make check` gives me

```
mount: /home/pmatilai/repos/brpm/tests/mktree.check/merged: special device sandbox does not exist.
       dmesg(1) may have more information after failed mount system call.
mount: /home/pmatilai/repos/brpm/tests/mktree.check/merged: mount point not mounted or bad option.
       dmesg(1) may have more information after failed mount system call.
bwrap: Only the last --chdir option will take effect
bwrap: execvp ./rpmtests: No such file or directory
umount: /home/pmatilai/repos/brpm/tests/mktree.check/merged: not mounted.
make[3]: *** [tests/CMakeFiles/check.dir/build.make:70: tests/CMakeFiles/check] Error 32
```

tests/README.md needs an update in any case, but doubly so if there's some manual setup needed now.

**Comment by dmnks** [comment]
Oops, forgot to uncomment the OS setup script in `mktree.native`. Fixed now.

And yup, I'm going to update README as well, it's one of the items on my little TODO list before claiming this PR ready :smile:

**Comment by dmnks** [comment]
No manual setup will be needed, though. If a native script isn't available for your platform (currently anything else than Fedora), the usual podman fallback will kick in (i.e. former `make ci`).

I'm also going to add back `make ci` even if you're running natively so that one can just see how CI would behave if they were to push the PR.

**Comment by dmnks** [comment]
@pmatilai BTW, before you try 'make check` again, please run `make tree-clean` first (or just `rm -rf tests/mktree.output`), there's currently a bug in how this is handled :smile: To be fixed today.

**Comment by pmatilai** [comment]
I'm getting a couple of unexpected test failures (didn't look at details yet) but basics seem to work fine.

**Comment by dmnks** [comment]
Could you please paste the log output of those? (`rpmtests.dir/N/rpmtests.log`)

**Comment by pmatilai** [comment]
At least 5 depends on CMAKE_INSTALL_PREFIX, it'll fail if it's /usr because the test now finds way more content than the just-built rpm. It's a badly written test, blame me :smile:

**Comment by dmnks** [comment]
Ugh, yup, I did test for different prefixes at the beginning but then just settled on the default and never got to trying out a different out :smile: So yup, we either fix the tests or add some kind of check / disclaimer to tests/README.md.

I bet the remaining test that fails is 437. I'm seeing that too now (so far I tested this in a F37 VM only, now finally tried on F38 :smile: ) I'll look at it. The error is:
```
gdb-add-index: Failed to find a useable GDB binary
```

**Comment by pmatilai** [comment]
437 and 439 fail even with default prefix. For 437 it's indeed the gdb index thing, 439 is more mysterious:

> stderr:
make: /usr/lib64/ccache/cc: No such file or directory
make: *** [<builtin>: hello] Error 127
error: Bad exit status from /usr/local/var/tmp/rpm-tmp.zsvYoW (%build)
rpm2cpio: /srv/rpmtests.dir/439/merged/build/RPMS/*/hello-g3-debuginfo-1.0-1.*.rpm: No such file or directory
cpio: premature end of archive

That's not the only thing compiling something, so wtf does some ccache thing matter here but not in the other cases?

**Comment by dmnks** [comment]
Hmm that's strange, indeed. `ccache` isn't even installed in the OS tree so it's strange that it's being poked in that test...

**Comment by pmatilai** [comment]
FWIW, `make shell` is a very nice addition :+1: (although I can imagine it got added because you needed it, not because it was "nice" :smile: )

**Comment by dmnks** [comment]
Both :smile:

**Comment by dmnks** [comment]
`make env` can also be useful as it gives you a shell on your host, with the same container mounted at `$RPMTEST` so you can inspect or modify stuff in it with your host tooling. Including DNF of course.

**Comment by pmatilai** [comment]
Heh, apparently the gdb-add-index failure is due to missing `which` command in the container so its attempt to locate the gdb that *is* there fails :laughing:

**Comment by dmnks** [comment]
Ohh, nice find, thanks :smile: Adding this to the TODO list above.

**Comment by pmatilai** [comment]
Yup, adding `which` to the dnf install cures 437. But sadly not 439. I'll look at that next...

**Comment by pmatilai** [comment]
Another minor item for the todo-list: add cmake dependencies to get the container automatically rebuilt when the mktree stuff is updated.

**Comment by dmnks** [comment]
Oh yup, thanks, that's one of those little "bugs" still to be fixed :smile:

**Comment by cgwalters** [comment]
It's worth noting that rpm-ostree has been isolating individual scripts (e.g. `%post`) with bwrap for a long time now.  That's distinct from the test suite only usage here, but just FYI.

**Comment by dmnks** [comment]
> It's worth noting that rpm-ostree has been isolating individual scripts (e.g. `%post`) with bwrap for a long time now. That's distinct from the test suite only usage here, but just FYI.

Interesting, thanks!

**Comment by pmatilai** [comment]
The ccache oddity comes from hello-g3.spec relying on `%__cc` macro, which cmake `find_program` has figured to be `/usr/lib64/ccache/cc`. That doesn't make sense and is an unrelated bug (I'll file a ticket) but easy to work around for now by adding `--define "__cc gcc" \` to the rpmbuild command in test 439.

**Comment by dmnks** [comment]
Thanks for investigating. The leakage is strange, though, as `rpmbuild` is run in the container.

**Comment by pmatilai** [comment]
The issue is that the macros file is generated on the host at the time `cmake` is initially run, so all manner of crap can leak through that path.

**Comment by dmnks** [comment]
Ohh right :smile: Indeed. Let me think about it then.

**Comment by pmatilai** [comment]
Don't waste your time on this now, %__cc shouldn't be set to that kind of value to begin with so it's a different bug.

**Comment by dmnks** [comment]
Also, are we OK with the replacement of `AT_CHECK` and `AT_CLEANUP` with the new `RPMTEST_CHECK` and `RPMTEST_CLEANUP` across the test suite?

Currently, that's what I opted for, but it's also possible to just redefine those original macros. The caveat with the latter is that there *could* possibly be undefined behavior in Autotest, see (the `m4_rename` section):
https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Redefined-M4-Macros.html

**Comment by pmatilai** [comment]
> Also, are we OK with the replacement of AT_CHECK and AT_CLEANUP with the new RPMTEST_CHECK and RPMTEST_CLEANUP across the test suite?

Oh absolutely. My first thought on seeing that was "why didn't we do that from the start?"

**Comment by pmatilai** [comment]
#2561 fixes the prefix related failures so you can mark those done.

**Comment by pmatilai** [comment]
#2563 should eliminate the need for those sysusers fixups.

**Comment by dmnks** [comment]
Rebased onto the latest fixups.

**Comment by pmatilai** [comment]
BTW, track the "nice to have" stuff elsewhere. This is a flagday change for the test-suite and as such, we want to get it over and done with ASAP and block any PR's that add tests in the meanwhile. Anything that isn't strictly needed can wait until the dust is settled.

**Comment by dmnks** [comment]
Fair point, I'll move that stuff out.

**Comment by pmatilai** [comment]
#2567 should remove the need for the "prevent __cc leak" patch.

**Comment by dmnks** [comment]
OK, I'll try it out later and if it helps, we can revert it I guess.

**Comment by dmnks** [comment]
Just FTR, I have a [simplified](https://github.com/dmnks/rpm/tree/iss1580-wip-simpler) version of this branch prepared and now [rebasing](https://github.com/dmnks/rpm/tree/iss1580-wip-v2) it. I'll push it here when it's ready.

**Comment by dmnks** [comment]
OK, pushed a semi-final version of this branch. Please note the CI will now fail since there's no podman/docker backend yet. That's in progress now :grin:

**Comment by pmatilai** [comment]
Test-suite passes locally :+1: 

That final "Replace fakechroot with bwrap" commit could use a little more elaborate commit message though. Like a brief description of how the setup this creates :smile:

**Comment by dmnks** [comment]
> That final "Replace fakechroot with bwrap" commit could use a little more elaborate commit message though. Like a brief description of the setup this creates smile

Yup, on the todo list above :laughing:

**Comment by pmatilai** [comment]
Oh yup. Semi-final, not final :smile:

**Review by pmatilai — APPROVED** [review]
I don't claim to have understood, or even tried, everything this does. It's remarkably neat and tidy for such big change though. Good job :+1: 

Feel free to hit merge once CI passes.

**Comment by Conan-Kudo** [comment]
What do we do if we want to run the test suite on non-Linux? Like macOS?

**Comment by dmnks** [comment]
Bubblewrap (bwrap) is used here to create fast, ephemeral per-test containers (*snapshots*) of the root filesystem. This replaces the former use of fakechroot. The whole test suite (the `rpmtests` script) assumes that the RPM build to be tested is installed into the root filesystem.

That means, in most scenarios, you'd want the test suite to run in a container with RPM installed and ready to use. That's what the `mktree` script does - it creates such an OS tree (i.e. image) and runs a container on top with `rpmtests`.

Now, the `mktree` script can have multiple implementations (*backends*). For example, one can use the host package manager to build the OS tree (e.g. DNF on Fedora) while another one can utilize `podman`. Both examples have their pros and cons (which is why backends are supported) but I won't go into the details now.

So to run the test suite, your platform needs to have bwrap ported and a suitable mktree backend to build the image.

The latter can be easily accomplished almost anywhere since in the worst case, the backend can always download a prebuilt OS tree tarball, or even copy (reflink) the necessary libraries and binaries from the host system into place (much like what we did with fakechroot).

The former (bwrap), however, is currently a strict requirement. That said, I was actually thinking of moving the bwrap logic into the mktree backends and have them define the per-test isolation method, instead of it being hardwired into the test suite. That way, one could write a "legacy" backend that basically does exactly what fakechroot did.

BTW, is fakechroot ported to MacOS? Or does Darwin have any containerization support?

**Comment by Conan-Kudo** [comment]
Darwin has `chroot()` like all POSIX systems. I'm not sure if `fakechroot` works on Darwin, but [`fakeroot`](https://salsa.debian.org/clint/fakeroot) is supposed to work on macOS and is [available via homebrew](https://formulae.brew.sh/formula/fakeroot).

Darwin also has the sandbox API (which Apple has also called "Seatbelt"). The best reference of this is [the one from Chromium](https://www.chromium.org/developers/design-documents/sandbox/osx-sandboxing-design/).

**Comment by dmnks** [comment]
Since I already started describing the new architecture, here's a perhaps simpler outline of how it works now (`mktree` is wired into the `make`):

1) `mktree build`
  * builds a base OS tree
  * builds RPM natively and make installs it into the base OS tree
2) `mktree check`
  * runs `rpmtests` in a container (on top of the OS tree), e.g. with bwrap or podman (depending on the backend used)
    * test1
      * `run rpm ...` (runs "natively" in the container, shouldn't make destructive changes)
    * test2
      * `runroot rpm ...` (runs in a per-test bwrap container, this enables destructive changes)
      * `ls $RPMTEST`
    * ...

**Comment by dmnks** [comment]
> Darwin has `chroot()` like all POSIX systems. I'm not sure if `fakechroot` works on Darwin, but [`fakeroot`](https://salsa.debian.org/clint/fakeroot) is supposed to work on macOS and is [available via homebrew](https://formulae.brew.sh/formula/fakeroot).
> 
> Darwin also has the sandbox API (which Apple has also called "Seatbelt"). The best reference of this is [the one from Chromium](https://www.chromium.org/developers/design-documents/sandbox/osx-sandboxing-design/).

Thanks. That alone is a good reason to perhaps really decouple the sandboxing technology from the test suite (and let the mktree backends responsible for providing it). I'll think about it.

How did you run the test suite on MacOS until now (or did you)?

**Comment by Conan-Kudo** [comment]
I have a virtual machine with macOS that I do destructive things in. Occasionally that includes running the test suite, but even just making a build environment for RPM in macOS manually (and avoiding homebrew) is pretty messy, so I do all that work in a dedicated virtual machine.

**Comment by dmnks** [comment]
Oh, so you do have a fakechroot build (in that VM) that works fine with the test suite, correct?

I mean, it's not a huge program with a lot of dependencies anyway (and `chroot()`, which AFAIK is used underneath, is a POSIX function, as you said), so it's probably easier to port than a full container/namespace tool.

**Comment by dmnks** [comment]
> Oh, so you do have a fakechroot build (in that VM) that works fine with the test suite, correct?

Nah, disregard that, you just confirmed that in your reply:

> but [fakeroot](https://salsa.debian.org/clint/fakeroot) is supposed to work on macOS and is [available via homebrew](https://formulae.brew.sh/formula/fakeroot).

**Comment by dmnks** [comment]
Anyway, the timing of your question was just right as I had been contemplating just about the same thing, i.e. whether to decouple the test suite *completely* from the sandboxing method used or make bwrap hardwired. (It's also one of the reasons this PR is *still* not merged, sigh.)

This is a useful data point since it basically confirms that it's probably worth adding that, especially since it's a pretty small  and easy patch on top of this branch.

Our no. 1 goal here is to get rid of fakechroot. In order to do that, though, we had to refactor and decouple the test suite from it, and so making that separation complete kinda makes sense.

**Comment by dmnks** [comment]
> At that point, adding a legacy backend using fakechroot (or just chroot perhaps) would be a possibility and while I won't make any promises, I _might_ look at that later.

Hmm, I totally forgot that `chroot` alone wouldn't suffice, the system would also need to have something like overlayfs and that's only available on Linux AFAIK.

Overlayfs is used here to create CoW snapshots of the root filesystem, as obviously making an actual copy for each test is too expensive and slow. The old test suite works around this by cherry picking the core files and directories to symlink into the per-test tree and lets fakechroot do its trickery where it resolves those symlinks outside of the jail while making it appear like a regular `chroot`. This kind of trickery is one of the reasons we want to get rid of fakechroot as it's unpredictable and has weird side effects.

So it turns out the new test suite will only support Linux systems for the time being. However, since it's made extensible, one can write a backend for non-Linux systems that uses a CoW technology native to the given platform.

Adding a backend using fakechroot + symlinks (i.e. the old approach) would be possible, too, but I don't think we want to go in that direction since removing fakechroot is the main motivation for this PR (and the associated #1580).

**Comment by DemiMarie** [comment]
@dmnks There is a FUSE implementation of OverlayFS that also supports the BSDs.

**Comment by pmatilai** [comment]
> Anyway, the timing of your question was just right as I had been contemplating just about the same thing, i.e. whether to decouple the test suite completely from the sandboxing method used or make bwrap hardwired. (It's also one of the reasons this PR is still not merged, sigh.)

Do NOT worry about such things now.

We need this groundwork in rpm now. It can always be improved later on.

**Comment by pmatilai** [comment]
> What do we do if we want to run the test suite on non-Linux? Like macOS?

You can send patches once this has been merged :wink:

Fakechroot is being replaced because it's a brittle hack that is severely hindering our ability to test rpm everywhere, including the primary platform Linux. This is about adopting better technology to be able to fully test rpm on it's primary target platform, other platforms are quite frankly little more than curiosities. For which we accept patches though.

**Comment by dmnks** [comment]
Alright, let's get this done now.

The commits should now be fairly self-contained and I also removed some bits in the final version of this PR that were just premature generalization on my part (e.g. [this comment](https://github.com/rpm-software-management/rpm/pull/2559#issuecomment-1633719443)). The resulting changeset is as minimal as feasible.

**Comment by pmatilai** [comment]
Yay! 🥳

**Pull request merged**
