### PR TITLE
Deprecate numberless %patch meaning patch number zero

### PR DESCRIPTION
**Pull request by pmatilai**
Details in commit messages, but these are simply bad syntaxes for applying patches, and having to support them prevents other developments in this area. Both `%patch` and in particular, `%patchN` are widely used so these need a longish deprecation period, but it needs to start somewhere.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
So we're saying we want people to use `%patch -P N` instead of `%patchN`?

**Comment by pmatilai** [comment]
Like the code says, "use %patch N (or %patch -P N)"

`%patch N [...]` is the saner variant, because there always needs to be at least one patch number specified so the number is a required argument, options are ... just options. Unfortunately `-P N` is the more compatible variant, due to the wacko semantics removed in the first commit.

It's fun. Digging up Fedora specs turns up for example this: `%patch -p1 -P 0 1 2 3 4`. Which ends up applying all three four patches, but one of them through the -P option and three as arguments. Makes a whole lot of sense, not :D

**Comment by Conan-Kudo** [comment]
Hah!

Well, at least @mlschroe seems to have used it correctly: https://code.opensuse.org/package/rpm/blob/e7c45583a5ded0cc97980fc022b39d67722071db/f/rpm.spec#_238-264

**Comment by Conan-Kudo** [comment]
I'm going to have to figure out how to redo `%patch` for debbuild though...

**Comment by pmatilai** [comment]
Yeah that Suse rpm.spec is a work of art :smile: 

Note that this is all about making `%patch` sane, finally. So in the end this should all be far easier to handle in debbuild too.

**Comment by pmatilai** [comment]
After sleeping over it, deprecating `%patchN` is still premature. We need to have working `%patch N` deployed first at some scale to be able to recommend the variant we want. So this is now just about making numberless `%patch` reasonable.

**Pull request merged**
