### PR TITLE
add support for premacros.d, complementing --predefine

### PR DESCRIPTION
**Pull request by proyvind**

### CODE REVIEW

**Comment by n3npq** [comment]
Pre-macros (and --predefine) aren't the right implementations: either an RPM invocation can read its own configuration or it can't.

Playing semantic games with goose-loosen CLI options adds complexity for no gain: all that is happening under the hood is that some macros are read before others. There is always a way to order macro configuration to Do The Right Thing without premacros (or --predefine).

**Comment by Conan-Kudo** [comment]
I have to say that I agree with @n3npq on this. I don't even use `--predefine` as it is, because it's a bit strange.

**Comment by ignatenkobrain** [comment]
Yeah, it feels weird.

**Comment by proyvind** [comment]
--predefine is the only functionality in place that offers same functionality of rpmrc now to perform configuration of rpm before rest of rpm macros being loaded, thus providing ie. the ability to help on finally deprecating rpmrc by ie. such as buildarchtranslate etc. from rpmrr which decides on for which platform the platform specific macros should be loaded by.

This was implemented in the past by myself @rpm5.org, in combination with libcpuinfo for replacing the messy arch detection in rpmrc.c, with compatible archs being determined by cpuinfo(feature) probe dependencies, with the platform definitions loaded from a cpuinfo.yaml using libsyck (which also required to be predefined in order to determine the arch definitions loading arch specific macro files by.

I'm in the process of porting it to rpm.org, with new improvements on TODO list such as switching from libsyck to libyaml, with a new rpmyaml class to serialize rpm header data to/from yaml etc.

rpmrc.c is a rotten mess which work on deprecating has been going on for a bit too long (@rpm5.org the rpmrc file support was already completely deprecated/dropped years ago), this PR is part of series of upcoming PRs working toward the goal of depreating rpmrc without dropping functionality relied on.
predefine is the only way of loading configuration at same time before rest of macro configuration, which is why this PR is needed and obviously the need I have for it.

**Comment by Conan-Kudo** [comment]
@proyvind We already load platform macros pretty early. They're in the search order right after the generic macros, so why not leverage that for dynamically loading platforms? Why do we need pre-macros when we can just define another set of macros to load at the beginning of the search order (if needed)?

Even if we we were to accept the premise of premacros, there's not an option in the search path to support overrides by RPMCANONVENDOR path ones, like there are for the regular macro search path.

**Comment by n3npq** [comment]
There's another approach to conditionalize macro definitions from configuration by permitting existence tests in the first field.

Most of the usage cases that have been reported to me are based on arch/os/platform, and the selection is being done by putting (some value) of arch in path to select 1-of-N possible configurations.

A macro configuration file looks something like:
`%foo bar`

If, say, there was a namespaced macro '%_arch_x86_64' defined as a side effect of reading /etc/rpm/platform, then the above could be conditionalized to be defined on x86_64 only by abusing the %{?...} syntax:
`%{?_arch_x86_64:foo} bar`

I.e. define '%foo bar' only if the macro _arch_x86_64 is defined.

I'm not sure its worth the effort, partly because everyone is going to want a value rather than an existence test.

**Comment by n3npq** [comment]
There's surely prettier syntax that can be achieved, or alternative syntaxes similar to what make does with conditional sections. E.g.
    `%{!?_arch_x86_64:#}    %foo bar`

**Comment by pmatilai** [comment]
NAK, lets not add new hacks to replace old ones. If macros need loading early then maybe they belong to the beginning of macrofiles list.

Just FWIW, I'd quite merrily accept a patch that rips out the i386/i486/i586-and-half/yack detection from rpmrc.c (and adjusts the rest to assume i686), the x86 sub-architectures are hardly relevant in this era.

**Pull request closed without merging**
