### PR TITLE
Add %{expr:...} macro for parsing expressions

### PR DESCRIPTION
**Pull request by pmatilai**
Supports the same expressions as spec %if conditions, only this returns the result as a string instead of a boolean.

This obviously *screams* to be wired into macro conditional syntax, but that's left as an exercise for later.

### CODE REVIEW

**Comment by pmatilai** [comment]
Forgot to update POTFILES.in. Thank you distcheck for catching it early...

**Comment by pavlinamv** [comment]
Functionality is OK, but error messages can be improved. I tried macros:
%{expr:0 || b} %{expr:4 &|| 0} %{expr:6 + 9 - o -=iu}
in a spec file and error messages were:
   error: types must match
   error: syntax error while parsing &&
   error: types must match

**Comment by pmatilai** [comment]
The error messages are simply the same as you get from spec %if conditionals, there are no messages added / changed in this PR. That's not to say the messages couldn't maybe be improved, but any change needs to account for the fact that they're shared between two quite different contexts.

There was an actual bug wrt errors in that expression errors did not raise a macro-level error. Fixed now.

**Comment by pmatilai** [comment]
Oh and BTW, the reason for doing this *just now* is that it might be kinda necessary for resolving #804 in the macro space instead of placing all the calculations on the C side. Of course technically Lua could be used for those same calculations but we I don't want to make Lua a hard dependency.

The other reason of course is the macro conditional syntax stuff.

**Comment by pavlinamv** [comment]
> The error messages are simply the same as you get from spec %if conditionals, there are no messages added / changed in this PR. That's not to say the messages couldn't maybe be improved, but any change needs to account for the fact that they're shared between two quite different contexts.

Not  entirely. If there is a problem in spec %if conditional, then two error messages are emitted e.g.:

```
error: syntax error while parsing ==
error: /data/SPECS/iftest.spec:22: bad %if condition:  =
```

But if the same wrong conditional is used after _%{expr_ (e.g. %{expr:=}) only the first error message is emitted:

```
error: syntax error while parsing ==
```

> There was an actual bug wrt errors in that expression errors did not raise a macro-level error. Fixed now.

Yes this is corrected now.

**Comment by pmatilai** [comment]
And now with improved expression error messages in both specs and macros.

**Comment by pavlinamv** [comment]
It is definitely better.

I tried a multiline expression:
```
rpm --eval '%{expr: 0 || 0 ||
	0 || 0 |o| 0}'
```

and **'^'** does not point to the expected position:

```
+error: syntax error while parsing ||:  0 || 0 ||
+	0 || 0 |o| 0
+error:                                                    ^
```

**Comment by pmatilai** [comment]
Yes, I'm sure you can construct arbitrary cases where it's not going to point to the right place.
Making the expression error reports *perfect* is not in the scope of this PR, so either I rip the marker support out or we leave it the way it is.

**Comment by pavlinamv** [comment]
Yes, but usually it is better to know the limitations of the current solution before it is merged.
I prefer to rip the marker support. But you can choose whether rip it or not.

**Comment by pmatilai** [comment]
At the risk of setting precedent that makes users expect friendly error messages from rpm, I'll keep it. It's just a cosmetical thing in any case and can be removed without other risk or harm if it turns out to be overly problematic.

**Pull request merged**
