### PR TITLE
scripts/pythondistdeps: Print Provides-Extra entries for Python packa…

### PR DESCRIPTION
**Pull request by gordonmessmer**
…ges.

For discussion's sake: should pythondistdeps.py print the "extras" in its Provides output, so that we can properly Require those features in dependent packages?

For example:

```
$ find /home/gordon/molecule-root | python3 pythondistdeps.py -P
(python3.7dist(molecule) == 3.0a5.dev15+gec8c85e9.d20191124)
python3.7dist(molecule::docker)
python3.7dist(molecule::docs)
python3.7dist(molecule::test)
python3.7dist(molecule::windows)
```

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
How did you come up with the notation?

**Comment by Conan-Kudo** [comment]
Also, we have a chunk of unused logic for Extras in here... Do we want to do something with it?

**Comment by hroncok** [comment]
The main problem here is how do we provide those things? There is no way to conditionally provide something, unfortunately :(

**Comment by ignatenkobrain** [comment]
You probably should look what rust packages are doing :)

**Comment by gordonmessmer** [comment]
> How did you come up with the notation?

"runtime(x::y)" is already used by perl packages (though not describing exactly the same thing), so I know that rpm will accept it.  That also means it's mostly consistent with an established notation.  As far as I know, the double-colon will never appear naturally, so it also seems unambiguous.

None of which is to say that it's desirable, exactly.  It just seemed like a good place to start discussion.

**Comment by gordonmessmer** [comment]
> Also, we have a chunk of unused logic for Extras in here... Do we want to do something with it?

I'm uncertain.  It looks like that was started as a means of packaging the optional components in separate rpm packages.  If that is completed, then it would be necessary to relocate the code in this patch so that the sub-packages "provide" the correct tag.

For now, though, I'd like to discuss whether or not we can include the optional components in the "provide" metadata.  If we add this data, then we can also process the python package expression of dependencies on extras.  Right now, that information gets ignored.

**Comment by gordonmessmer** [comment]
> There is no way to conditionally provide something, unfortunately

I may be mistaken, of course, but it looks like the extras reflect what was built and installed.  What would need to be conditional at the point when we're examining the buildroot to determine what's there?

**Comment by gordonmessmer** [comment]
> You probably should look what rust packages are doing :)

I'd be happy to.  Do you have a pointer to where I should start?

**Comment by gordonmessmer** [comment]
I've pushed a modified change that uses a slash separator, like the rust generator does.  It also adds the version to extras:

```
$ find /home/gordon/git/molecule-root | python3 pythondistdeps.py -P
(python3.7dist(molecule) == 3.0a5.dev15+gec8c85e9.d20191124)
(python3.7dist(molecule/docker) == 3.0a5.dev15+gec8c85e9.d20191124)
(python3.7dist(molecule/docs) == 3.0a5.dev15+gec8c85e9.d20191124)
(python3.7dist(molecule/test) == 3.0a5.dev15+gec8c85e9.d20191124)
(python3.7dist(molecule/windows) == 3.0a5.dev15+gec8c85e9.d20191124)
```

**Comment by ignatenkobrain** [comment]
> I'd be happy to. Do you have a pointer to where I should start?

Sure, https://pagure.io/fedora-rust/rust2rpm.

1. We parse package name for generators

```
%__cargo_provides  %{_bindir}/cargo-inspector --provides --features=%{__cargo_feature_from_name -n %{name}}
%__cargo_requires  %{_bindir}/cargo-inspector --requires --features=%{__cargo_feature_from_name -n %{name}}
```

2. Dependency generator can generate Requires/Provides just for specific feature (extras in Python)

---

We just changed all our packages to be this scheme, I think for python it might not be desired, so we might want to create macro `%_python_all_extras_in_main` or something similar which would generate all extras provides/requires from the main package. And if you change it to 0, then it would do same as Rust one does.

---

```
❯ for x in '' '+default' '+indexmap'; echo -e "---\ntoml$x\n\nPROVIDES:"; sudo dnf -q repoquery --provides rust-toml{$x}-devel; echo "REQUIRES:"; sudo dnf -q repoquery --requires rust-toml{$x}-devel; end
---
toml

PROVIDES:
crate(toml) = 0.5.6
rust-toml-devel = 0.5.6-1.fc32
REQUIRES:
(crate(serde/default) >= 1.0.97 with crate(serde/default) < 2.0.0)
cargo
---
toml+default

PROVIDES:
crate(toml/default) = 0.5.6
rust-toml+default-devel = 0.5.6-1.fc32
REQUIRES:
cargo
crate(toml) = 0.5.6
---
toml+indexmap

PROVIDES:
crate(toml/indexmap) = 0.5.6
rust-toml+indexmap-devel = 0.5.6-1.fc32
REQUIRES:
(crate(indexmap/default) >= 1.0.0 with crate(indexmap/default) < 2.0.0)
cargo
crate(toml) = 0.5.6
```

**Comment by hroncok** [comment]
I got an idea last night about how to handle this. I need to put it in writing and realize if it is indeed a working idea or not. Will open a ticket.

**Comment by hroncok** [comment]
https://github.com/rpm-software-management/rpm/issues/1061

**Comment by pmatilai** [comment]
Long time, no activity. Is this still being worked on?

**Comment by hroncok** [comment]
We have it ready in Fedora: https://fedoraproject.org/wiki/Changes/PythonExtras

We want to backport it here but we have been swamped with many other things.

cc @torsava

**Comment by torsava** [comment]
> We have it ready in Fedora: https://fedoraproject.org/wiki/Changes/PythonExtras
> 
> We want to backport it here but we have been swamped with many other things.
> 
> cc @torsava

I've opened a PR to upstream our Fedora full-blown handling of Extras: https://github.com/rpm-software-management/rpm/pull/1546

@gordonmessmer Please take a look, I think it implements what this PR does and more.

**Pull request closed without merging**
