### PR TITLE
Move the internal OpenPGP implementation to its own file.

### LINKED ISSUE #2000: Detangle the internal PGP implementation from common code
According to https://github.com/rpm-software-management/rpm/issues/1978#issuecomment-1080606598, a possible way forward is for RPM to have a second PGP backend, possibly based on Sequoia.  For this to be done, we need to detangle the internal implementation from the common code.

### PR DESCRIPTION
**Pull request by nwalfield**
Split the internal OpenPGP implementation into the bits that are
needed by a new OpenPGP backend like Sequoia, and the bits that are
not needed by another OpenPGP backend.

Move most of the functionality in rpmio/rpmpgp.c into
rpmio/rpmpgp_internal.c.

Leave pgpValStr, and pgpIdentItem, which are used for printing and
needn't be reimplemented by other backends, and pgpReadPkts, which is
just a thin wrapper around pgpParsePkts, and which uses an internal
rpm function that a new backend shouldn't have to worry about
emulating or even calling.

Move the symbol tables, which are used by pgpValStr, pgpIdentItem, and
the internal OpenPGP implementation to rpmio/rpmpgp.h.  These are
common to all implementations.

Fixes #2000.

### CODE REVIEW

**Comment by pmatilai** [comment]
I thought we already did this, but guess not :sweat_smile: Thanks.

**Comment by pmatilai** [comment]
Doh, the above comment was intended for a different PR.

No matter, I would've merged this anyway. Only, I intended to mention that this is tantalizingly close to being able to move those two silly functions to librpm-side and hide them from the public API, but of course we can't do that while the internal OpenPGP parser uses them.

**Comment by nwalfield** [comment]
> I intended to mention that this is tantalizingly close to being able to move those two silly functions to librpm-side and hide them from the public API, but of course we can't do that while the internal OpenPGP parser uses them.

I don't completely follow.  Can you please clarify which functions you mean?

**Comment by pmatilai** [comment]
pgpValStr and pgpIdentItem is what I was talking about, but looking closer maybe pgpReadPkts and pgpParsePkts too, in some form at least. Mostly just thinking out loud though, not something I expect you to do.

**Pull request merged**
