### PR TITLE
Remove "support" for loading keyring from filesystem

### PR DESCRIPTION
**Pull request by pmatilai**
This is basically an abandoned and forgotten development path from
11 years ago that arguably should've been removed long ago, and one
that has potential security implications and doesn't play well with
existing API users who rely on gpg-pubkey headers being in the rpmdb
(RhBug:1393586)

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This is still actively used by the Yocto folks, especially Wind River, who patches DNF to get rpm to do this when `gpgkey=` isn't specified while `gpgcheck=1` is set.

**Comment by Conan-Kudo** [comment]
(cc: @mhatle @kanavin)

**Comment by mhatle** [comment]
Yes this is actively used by the Yocto Project.  It allows us to have a single location in the system that contains all of the software keys, and can be updated dynamically by authorized systems/components.  Having to load keys (manually) into the rpm database, makes it very difficult to support devices that can't be serviced and have no console.  Instead we can remove old keys and install new keys [passing appropriate selinux/ima/etc security methods] by updating files.

It also allows developers to open up devices for user control by installing secondary keys for user-packages to 'unlock' an otherwise locked device.

**Comment by jwessel** [comment]
Ideally we don't want to have to carry a revert to gain the functionality back for the Yocto Project.  Is there something else that can be done here other than to remove the code, such as an option with with in the configuration to allow it to continue to function as it does today?

**Comment by cgwalters** [comment]
Also worth noting https://github.com/rpm-software-management/libdnf/issues/43
(libdnf auto-injects `/etc/pki/rpm-gpg`)

**Comment by cgwalters** [comment]
(Except I think that code is still not used by dnf because it dates to the PackageKit C vs yum Python days?)

**Comment by pmatilai** [comment]
Oh. We're not removing something that's in active use, I simply had no idea people actually use that, I've never heard so much as a single word of anybody using it until now.

Closing and back to drawing board, but clearly proposing removal was an effective way to gain information. Thanks for the feedback.

**Pull request closed without merging**
