### PR TITLE
Support individual patch application in %autopatch

### PR DESCRIPTION
**Pull request by pmatilai**
There are cases where "apply 'em all" doesn't cut it, and passing
-m and -M is cumbersome for individual patches. Add support for
applying individual patches by passing their numbers as arguments,
update documentation.

### CODE REVIEW

**Comment by hroncok** [comment]
So, no ranges after all?

I think the documentation would benefit form some examples. I'll write some down.

**Comment by hroncok** [comment]
```
%autopatch                -- applies all patches defined in the spec file, in the definition order
%autopatch -m 100         -- applies all patches numbered 100 or higher, in the definition order
%autopatch -M 99          -- applies all patches numbered 99 or lower, in the definition order
%autopatch -m 200 -M 299  -- applies all patches numbered 2xx, in the definition order
%autopatch 1              -- applies patch number 1
%autopatch 4 5 2 3 6      -- applies specified patches in the order of the arguments
```

Also, I've noticed the commit message should probably say `%autopatch`, not `%autosetup` (unless `%autosetup` also supports the arguments).

**Comment by pmatilai** [comment]
Doh, should say "%autopatch" of course, not setup. That's what you get for writing commit messages in a hurry. Will fix, thanks for spotting. Further docs and examples in particular probably belong to manual/autosetup.md rather than the macro file.

And yeah I was getting stuck with the ranges so thought we can always add them later.

**Comment by pmatilai** [comment]
Docs added, polished the autosetup page a little while at it.

**Comment by pmatilai** [comment]
No further comments in two weeks, I guess we're sufficiently done here...

**Comment by hroncok** [comment]
> No further comments in two weeks, I guess we're sufficiently done here...

Well, it was 1 day since you posted the recent update, not 2 weeks.

**Comment by pmatilai** [comment]
Sure but that was just for the docs. I'm in a bit of a hurry to wrap things up for a beta before my vacation...

**Pull request merged**
