### PR TITLE
A saner way for marco argument escaping

### PR DESCRIPTION
**Pull request by mlschroe**
This adds a ME_NOEXPAND macro flag that turns off body expansion.

This is much simpler than the weird % character doubling. It's also a bit faster
because there's less calls to expandMacro().

### CODE REVIEW

**Comment by mlschroe** [comment]
Another good name would be `ME_LITERAL`.

We also may want to expose this by adding a rpmPushMacroLiteral() function so that this can be used in other places where we don't want expansion to happen. E.g. everywhere where we have calculated a file name or path and want to set a macro for it.

**Comment by pmatilai** [comment]
> We also may want to expose this by adding a rpmPushMacroLiteral() function 

Lets use a more generic name that takes a flags arguments so it's extensible in the future (for example a readonly/protected kind of behavior would come in handy occasionally). Another approach that wouldn't require a new API is prefixing the name with a special character, eg ":foo" to declare a literal (IIRC rpm5 used a dot prefix to denote readonly)

**Comment by pmatilai** [comment]
FWIW, tested a bit with the macro generator thing - even after all this noexpand stuff, the %{basename:%{1}} testcase still ends up eating %'s in due to the re-expansion in doFoo().

**Comment by pmatilai** [comment]
Anyway, looks fine to me on the outset. I'll have a closer look next week.

**Comment by pmatilai** [comment]
This leaves __file_name and __file_lineno expansion inconsistent. Please move that commit last, and update the __file_name/lineno manipulation in build/ to use literals too. Other than that I guess this is good to go.

**Comment by mlschroe** [comment]
Ok, done. I also used RPMMACRO_LITERAL at some other places where it made sense.

I tried to add it to the buildroot macro (re-)definition, but with buildroot it is pretty hopeless. rpm's rpmGenPath always expands all arguments, which leads to the buildroot getting expanded over and over again.

**Comment by mlschroe** [comment]
(Oh, and I renamed ME_NOEXPAND to ME_LITERAL for consistency)

**Comment by pmatilai** [comment]
> I tried to add it to the buildroot macro (re-)definition, but with buildroot it is pretty hopeless. rpm's rpmGenPath always expands all arguments, which leads to the buildroot getting expanded over and over again.

Yup, it's %'s all the way down... :turtle: 
Perhaps we'll get there yet.

**Pull request merged**
