### PR TITLE
[RFC] Add support for sorting the plus ('+') higher than base version

### PR DESCRIPTION
**Pull request by martinezjavier**
This commit adds supports for sorting the plus ('+') character higher than
base version. It's similar to what commit c7e711bba58 ("Add support for
sorting caret ('^') higher than base version") did for the caret character.

A plus character is used for example by the Linux kernel build system to
denote that is the base version plus some changes on top of it.

Currently for example rpmvercmp("5.3.0", "5.3.0+") will return 0 even when
the two versions are not the same.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This was attempted originally as #88 and was rejected, which is why we switched to `^`.

**Comment by martinezjavier** [comment]
@Conan-kudo I see, I’ve mentioned #88 in issue #925 that explains the more general issue of rpmvercmp() taking as equal versions that are really different. And also elaborated a little bit why I needed the + character to be taken into account.

This is just a fix for a particular case of the more general problem.

**Comment by ffesti** [comment]
As mentioned above this got rejected already and things have not changed since. We just can't change the way version comparison works as thousands of packages rely on it and any change will break lots of them. Tilde and caret could only be added as they were not allowed previously.
See http://lists.rpm.org/pipermail/rpm-ecosystem/2016-September/000411.html for more details.

**Comment by martinezjavier** [comment]
@ffesti that's OK.

For the GRUB blscfg module we diverged from the RPM sorting algorithm and added support for the plus character, since debug kernels contains that as a suffix and the expectation is that the debug and non-debug kernels are not the same.

**Pull request closed without merging**
