### PR TITLE
macros: drop python macro

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Those belong to python, not RPM.

Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by n3npq** [comment]
The whole idea that absolute paths need to be provided as macros to be expanded in spec files has been unnecessary since POSIX was invented and widely deployed.

When was the last time you felt the need to write a shell script that used absolute paths for common system programs? The entire reason for supplying macros with absolute paths was to simplify *MY* life developing RPM on Solaris last century with GNUish utilities in /usr/local/bin and BSDish utilities in /usr/bin. With POSIX utilities everywhere, PATH should be used, because, well, that is what one does in uglix.

As for OpenMandiva, part of switching from python2 to python3 is to ensure that the executable called "python" Does The Right Thing.

**Comment by pmatilai** [comment]
The fundamental problem is that the Python 3 transition has mutilated the once simple Python landscape into something barely recognizable. Rpm cannot possibly know what the "default python" is when such a thing no longer exists - /usr/bin/python could point to anything at all or not even exist, and certainly Python 2 and 3 are not freely interchangeable.

I see roughly three alternatives here: 
a) simply declare python 3 as the new default from rpm POV and start defaulting to it everywhere
b) drop the notion of "default python" and split these macros into two versioned ones
c) just kick this stuff out entirely and let distros sort out their own particular messes

**Comment by hroncok** [comment]
What does "default python" even mean and why does RPM need to care?

**Comment by pmatilai** [comment]
> What does "default python" even mean and why does RPM need to care?

Exactly. Nobody knows wtf %__python is supposed to mean these days. Yet rpm should somehow know what to with it.

**Comment by hroncok** [comment]
I think that %__python should be configurable anything (that meets a certain API, so 
%python_sitearch etc. can work). However I don't think it needs a default.

**Comment by pmatilai** [comment]
So you're suggesting we remove just the %__python macro, (or define as an error), but leave the python_foo helpers around?

That'd account for option d) basically.

**Comment by hroncok** [comment]
Yes, but add error handling to python_foo helpers (e.g. if I set %__python to /usr/bin/false or a not existing file).

**Comment by Conan-Kudo** [comment]
Red Hat's indecision aside, pretty much everyone else knows how they're going to have "default Python". And don't we have a `@__PYTHON@` substitution anyway? It gets filled in with whatever is detected for the interpreter.

If you want to be fancy, just make it if `@__PYTHON@` isn't detected at build time, set it to `/bin/false` or something. Though I think this is overkill...

**Comment by hroncok** [comment]
This is very helpful for spec reuse. You can use python_helpres anywhere in the spec, but at one place, just define %__python as needed (e.g. /usr/bin/python on RHEL7, /usr/bin/python3 on Fedora, %{__python3} on RHEL8, /usr/bin/pypy in your custom repo...).

**Comment by Conan-Kudo** [comment]
@hroncok That doesn't preclude the default Python being set. I (ab)use this fact for Pagure packaging in Fedora already.

And keep in mind that in exactly 1 year and 2 months, `/usr/bin/python` will mean _only_ Python 3 anyway.

This is much ado about nothing.

**Comment by pmatilai** [comment]
I tend to agree with @Conan-Kudo there: Python 2 is being phased out with increasing force, and once it's gone it'd be just stupid for %__python to be anything else than Python 3. So the forward-looking solution is a), and all the others are "make it somebody elses problem" in one way or the other.

**Comment by pmatilai** [comment]
...however there is the point that maybe this really *should* be somebody else's problem, and the python 2 -> 3 transition is probably the best chance we're ever going to get for making that so...

**Comment by Conan-Kudo** [comment]
It is already the distributor's problem, since they have to build rpm and tell it what the Python interpreter is.

**Comment by pmatilai** [comment]
The most compelling argument for dropping is that such macros should've never been added to rpm in the first place, ditto for similar perl etc macros. They belong to the corresponding language(s), as has been done with all the newer languages appearing on the scene.

**Comment by Conan-Kudo** [comment]
However, unlike most newer languages, the ones we have macros for in here are also ones where rpm includes code for in its source tree.

Since we have Python bindings, I'd rather have us keep those macros in here...

**Comment by pmatilai** [comment]
After discussing this at length with @ffesti, these Python macros and helpers dropped in commit ba85c95963f9b62f237c0442f6b5aca3e355fa83, along with Perl and PHP helpers, see commit message for rationale.

Thanks for initiating the avalanche @ignatenkobrain  :wink:

**Pull request closed without merging**
