### PR TITLE
Security fixes for the OpenPGP parser

### PR DESCRIPTION
**Pull request by DemiMarie**
See individual commit messages for details.

### CODE REVIEW

**Comment by pmatilai** [comment]
>  Do not allow extra packets to follow a signature
>
> It substantially increases RPM’s attack surface, and there are no legitimate reasons for such packets to be present.  None of the packages in either the Fedora 25 or Fedora 32 repositories have them.

Please point me to the section in RFC-4880 which this is based on.

**Comment by DemiMarie** [comment]
> > Do not allow extra packets to follow a signature
> >
> > It substantially increases RPM’s attack surface, and there are no legitimate reasons for such packets to be present.  None of the packages in either the Fedora 25 or Fedora 32 repositories have them.
> 
> Please point me to the section in RFC-4880 which this is based on.

§11.4 Detached Signatures

**Comment by pmatilai** [comment]
Um, what?

I'm asking where in the RFC it is said that no packets can follow a signature packet?

**Comment by pmatilai** [comment]
Oh never mind, insufficient caffeine level... says right there, "simply a Signature packet".

**Comment by DemiMarie** [comment]
@pmatilai would splitting out the commits into separate PRs help?

**Comment by pmatilai** [comment]
It's a bit late by now, but of course it would've helped. I've said many many times that these kind of mega PR's have close to zero chance of being accepted because they're not meaningfully reviewable on GH.

PR's can be more than one commit but the commits need to be *closely* related in the sense that all of them must go in at once or not at all. Sprinkling anything unrelated into it will quite effectively stop a review from progressing. War worse is multiple mega PR's overlapping and containing different versions of commits etc.

**Comment by DemiMarie** [comment]
> It's a bit late by now, but of course it would've helped. I've said many many times that these kind of mega PR's have close to zero chance of being accepted because they're not meaningfully reviewable on GH.
> 
> PR's can be more than one commit but the commits need to be _closely_ related in the sense that all of them must go in at once or not at all. Sprinkling anything unrelated into it will quite effectively stop a review from progressing. Far worse is multiple mega PR's overlapping and containing different versions of commits etc.

Thanks!  Would you mind if I made a PR adding this to CONTRIBUTING.md?  That might have avoided quite a bit of confusion.

**Comment by DemiMarie** [comment]
Is it okay if an earlier commit can go in without a later commit in the same PR, or should those be separate PRs?

**Comment by DemiMarie** [comment]
Closing as this PR is not reviewable.  I will file separate PRs.

**Pull request closed without merging**
