### PR TITLE
 Added option to rpmbuild to check the build dependencies (-bd,-td,-rd) #876 

### PR DESCRIPTION
**Pull request by ffesti**
Fix for #876 and added man page entries.

Should be squashed while merging.

Resolves: #876

### CODE REVIEW

**Comment by pmatilai** [comment]
Testcase is still missing. We really should not add new functionality without at least *some* test for it. We already have some buildrequires tests in there, just extend on those. Also squash the commits and write a proper commit message with it, eg why we need it and how it relates to dynamic build requires.

**Comment by pmatilai** [comment]
It's not silly to test when they behave differently. It's all such silly details that get easily broken if not tested.

**Comment by ffesti** [comment]
Here you go!

**Comment by pmatilai** [comment]
Thanks.

**Pull request merged**
