### PR TITLE
Serialize manipulation of global lists in rpmdb.c

### PR DESCRIPTION
**Pull request by DemiMarie**
rpmdb.c contains three global linked lists, but currently does not
include synchronization to protect against concurrent access to them.
This results in hard-to-debug crashes when third-party code uses the
rpmdb (even read-only) from multiple threads, such as by verifying
signatures against the RPM default keyring.  An example is
https://github.com/QubesOS/qubes-rpm-oxide/pull/15 which took nearly a
year to track down.

Fix this problem by adding the necessary synchronization.  Since
rpmAtExit() traverses all three lists, it is necessary for rpmAtExit()
to take the locks itself, rather than having the functions it calls do
so.  Therefore, functions that free an rpmdb, rpmdbIndexIterator, or
rpmdbMatchIterator now have an internal version.  The internal version
takes a second argument, which indicates whether locks should be
aquired.  The standard functions pass 1, but rpmatExit() passes 0, since
it has already aquired the locks.

### CODE REVIEW

**Comment by pmatilai** [comment]
This looks too complicated and brittle for too little benefit, I'd rather conclude rpmdb, like most of rpm, just not being thread-safe. We probably don't need this tracking anymore now that BDB is gone, and even if we did it should be sufficient to have one big lock around the tracking.

**Comment by pmatilai** [comment]
The other thing is that almost certainly rpmiiRock and rpmmiRock shouldn't have been global in the first place, db iterators can only exist within an open db handle so they can be hooked on the db handle instead.

**Comment by pmatilai** [comment]
Oh and as for the use-case of verifying signatures: the rpmdb is not involved in that, except for initial loading of the keys. As it usually happens implicitly, multiple threads can run into each other. A better way is to explicitly load the keys before going threaded, either by calling rpmtsGetKeyring() with autoload (after which you can do an explicit rpmtsCloseDb()), or manually populating a keyring from whatever source you like, doesn't have to be the rpmdb at all.

**Comment by DemiMarie** [comment]
> This looks too complicated and brittle for too little benefit, I'd rather conclude rpmdb, like most of rpm, just not being thread-safe.

For now, perhaps, but I would like this to change, at least if the libc implementation allows using malloc() in a multithreaded child process after fork().

> We probably don't need this tracking anymore now that BDB is gone, and even if we did it should be sufficient to have one big lock around the tracking.

What would be involved in ripping it out?  I considered the big lock approach but I could not figure out a way to not deadlock without using recursive mutexes, and those cannot be initialized statically with `PTHREAD_MUTEX_INITIALIZER`.

> A better way is to explicitly load the keys before going threaded, either by calling rpmtsGetKeyring()

Thanks for the advice regarding existing RPM versions.  I would prefer for _new_ RPM versions to be more thread-safe, though.

**Comment by pmatilai** [comment]
The big lock approach should work if rpmmiRock and rpmiiRock are moved into the rpmdb handle which is where they belong, because then there's only one static item left. That they're standalone looks like a historical moment of not thinking through caught in time and then copied, and multiple instances of the same making it look "more right". Note that of course this assumes you don't pass a handle opened in one thread to another (which generally is the extent that rpm allows threads), which I guess is exactly what you're doing. So while that would make sense, it probably wont help your use-case without also explicitly pre-loading the keyring. 

Ripping the whole works involves figuring out the related signal mess and its related API + semantics and all, which is a hairy mess (and also broken currently it seems)

**Comment by pmatilai** [comment]
> What would be involved in ripping it out?

Something like [that](#1946 ).

**Comment by pmatilai** [comment]
Solved differently in #1946 but thanks for providing the motivation to get around to that :sweat_smile:

**Pull request closed without merging**
