### PR TITLE
mjw: debugedit: Add some testcases and handle .debug_macro (gcc -g3)

### PR DESCRIPTION
**Pull request by pmatilai**
Forwarded from rpm-maint http://lists.rpm.org/pipermail/rpm-maint/2019-June/010344.html:

Hi,

debugedit wouldn't properly handle gcc -g3 which generates .debug_macro
sections. The sections would contain references to .debug_str which
debugedit rewrites. But it would not update the references in .debug_macro
which would upset various tools.  For example gdb:
https://bugzilla.redhat.com/show_bug.cgi?id=1535174

Michael Schroeder had a patch for that, but that didn't handle relocations
(which happen in e.g. linux kernel modules). So I added support for that.
(patch four).

debugedit didn't have any specific tests. It was only tested as part of
the whole rpmbuild debuginfo pipeline. So I first added a bunch of test
cases (the first two patches). That helped make sure my debugedit relocation
code refactoring was working as expected (the third patches).

It also found an small issue (under valgrind) with the .debug_line
rewriting code (the last patch).

[PATCH 1/5] Add some color to the tests if available and the terminal
[PATCH 2/5] Add some debugedit tests.
[PATCH 3/5] debugedit: Refactor reading/writing of relocated values.
[PATCH 4/5] Handle .debug_macro in debugedit.
[PATCH 5/5] debugedit: Make sure .debug_line old/new idx start equal.

Cheers,

Mark

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
I'm not expert in debugedit stuff, but from the first glance changes look good.

**Comment by Conan-Kudo** [comment]
The code looks okay to me, and it seems to pass the tests, including the new ones he wrote. 👍

**Comment by pmatilai** [comment]
Pushed an additional commit to remove 1998 cruft from the added test spec.

**Comment by pmatilai** [comment]
Yeah I'm don't consider myself qualified to review the debugedit stuff either, so I'll just trust Mark and his testcases :slightly_smiling_face:

**Comment by pmatilai** [comment]
...argh, I thought GH rebase + merge would clear up that fixup commit I added but alas, no :(

**Pull request merged**
