### PR TITLE
More flexible build phases

### PR DESCRIPTION
**Pull request by thp**
Here is a set of patches that we use in the [Mer Project](http://merproject.org/) for speeding up building of RPMs during development (incremental in-tree builds and specifying the phases to run from e.g. Qt Creator).

I'm a bit unsure about adding `--skip-clean` and `--skip-prep`, as those phases might also be skipped by `--noclean` (which already exists) and `--noprep` (which is added by this patchset). @lbt might know.

### CODE REVIEW

**Comment by cgwalters** [comment]
Looks reasonable offhand - can you link to any existing docs at least briefly describing the workflow of how a developer would use this?  Is this called from a Qt Creator plugin?

**Comment by lkardos** [comment]
* Yes, there is no reason to have `--noclean, --noprep` and also `--skip-clean, --skip-prep`.
* Build stage enablers seem to be very similar to `--short-circuit` but no unsatisfiable dependency is created. Is this only one reason why you don't use `--short-circuit` or do your build stage enablers have any other advantages? 
* The build-in-place patch creates macro `_build_in_place`. Do you expect that rpm scriptlets will read this macro or do you use that macro only like a global variable? 

Description of your use case for this could be useful. How do you create directory for `--build-in-place` or why do you need execute rpm build stages separately?

**Comment by thp** [comment]
Dropped the "rpmbuild: Add --skip-prep and --skip-clean flags" patch from the patchset, as `--noprep` and `--noclean` do the same thing.

**Comment by thp** [comment]
As far as I know, `_build_in_place` is only used as global variable there. Scriptlets shouldn't need to know (or care) whether they are built in-place or normally. For the remaining questions, @lbt will provide answers:

* Any existing docs at least briefly describing the workflow of how a developer would use this? Is this called from a Qt Creator plugin?
* Build stage enablers seem to be very similar to `--short-circuit` but no unsatisfiable dependency is created. Is this only one reason why you don't use `--short-circuit` or do your build stage enablers have any other advantages?

**Comment by lbt** [comment]
The basic idea behind this is to allow day-to-day developer work to use the .spec to drive builds. This makes packaging an incremental part of development and is intended to avoid any "I got it working, now to package it" pain.

Typically a developer has a checked-out src tree (with an rpm/ dir) and would like to just build and test the resulting binary. We try to make the hack-build-test-deploy cycle really fast, and take advantage of incremental builds that will increase developer's productivity while still being able to take advantage of RPM's features. We also support doing an rsync of the built system to the target which is why we sometimes don't need the rpms to be built.

The first thing we need is to avoid needing to duplicate the src tree in ~/rpmbuild/: hence "_build-in-place"
This redefines _buildsubdir and touches rpmbuild.c
Also note that build.c normally rm -rf's buildSubdir so that would be bad - hence setting it to NULL
It causes an exit from parsePrep.c before the normal cleanup phase too.
Yes, the macro is used as a global variable but at the time it felt like it may make sense in builds too which is why I decided to use that approach.

The short-circuit option doesn't provide the granularity - it may start later but it always runs all the phases from that point forward, which is too inflexible for our Qt Creator use case. The -do-<phase> option is extremely explicit .. it does that phase and that phase only (of course, multiple phases may be specified).

Our Qt Creator plugin (https://github.com/sailfish-sdk/sailfish-qtcreator) uses the "mb2" utility (https://github.com/sailfish-sdk/sdk-setup/blob/master/sdk-setup/src/mb2) in the build VM to orchestrate the RPM build phases and allow non-qmake as well as qmake builds to work correctly with Qt Creator's workflow.

**Comment by thp** [comment]
Any feedback from upstream regarding getting this merged or what should be changed?

**Comment by lkardos** [comment]
The short-circuit option doesn't run all the phases from the given point forward. 
* `rpmbuild -bp --short-circuit` runs just prep phase, same as `rpmbuild --doprep`
* `rpmbuild -bc --short-circuit` runs just build phase, same as `rpmbuild --dobuild`
* `rpmbuild -bi --short-circuit` runs just install phase, same as `rpmbuild --doinstall`
* `rpmbuild -bb --short-circuit --noclean` runs just package binary phase, same as `rpmbuild --dobinary` but no unsatisfiable dependency is created

I am not sure if we want to have two options for the same task. Maybe not creating unsatisfiable dependency with the short-circuit option will be enough, won't it? I have nothing against the rest of commits. @ffesti do you want to have a look at this PR too?

**Comment by thp** [comment]
So I'll update the pull request to remove the "--do*" steps. Anything else?

**Comment by thp** [comment]
Dropped the "--do*" commits from the pull request.

**Comment by kad** [comment]
Unjustifiable dependency was specifically introduced to indicate that package is built not in clean environment (potentially security risk). For installing packages created not in clean environment people would need to think twice and either use --nodeps or create fake empty package with Provides: that fake dependency.

**Comment by ffesti** [comment]
Added upstream. I also added some man page entries.

**Pull request closed without merging**
