### PR TITLE
Improvements for xz support

### PR DESCRIPTION
**Pull request by proyvind**
Here's a new pull request with xz threading settings being set through %_{binary,source}_payload.

### CODE REVIEW

**Comment by ffesti** [comment]
Ok, pushed all but the very last patch to master.

**Comment by rpm-maint** [comment]
On 19 November 2015 at 15:20, Florian Festi <notifications@github.com> wrote:
>
> Ok, pushed all but the very last patch to master.

Hum...
Should performance commits be backed by numbers before being merged?

**Comment by ffesti** [comment]
This needs to be rebased and cleaned up to go though a second round of review.

**Comment by proyvind** [comment]
Hm, there's several asserts in place throughout source code that would be bad to compile with -DNDEBUG as the desired and safe behaviour expected for assert is to abort if expession evaluated is false...

Of course one could replace the assert(3) with:
if(--mt_options.threads == 0)
    abort();

This way ensuring same behaviour regardless of, but this gives me a dirty feeling with me questioning whether there's some other standard functionality for graceful exit suitable and recommended for this to use in stead available in rpm.org?

**Comment by proyvind** [comment]
sorry for slooow response, but rebased now :)

**Comment by Conan-Kudo** [comment]
@ffesti @ignatenkobrain Anyone have a chance to re-review after the rebase?

**Comment by ffesti** [comment]
I'd squash the last 5 patches together and put them on to of the current HEAD if this is ok with you.

**Comment by proyvind** [comment]
Done, this should hopefully suffice. :)

**Comment by Conan-Kudo** [comment]
Looks good to me! 👍 

@ffesti What do you think?

**Comment by ffesti** [comment]
Thanks of the effort!

**Pull request merged**
