### PR TITLE
Enhance check-buildroot script

### PR DESCRIPTION
**Pull request by pvalena**
passed through shellcheck, and also sped-up via grep -r.

Testing & verification: https://gist.github.com/pvalena/2c92d68b708404e2a5571095771e2965

### CODE REVIEW

**Comment by pvalena** [comment]
Please note that you also save a lot of CPU :) and I think it's more resilient.

It works in rawhide, as well as on RHEL7 (mock).

**Comment by pmatilai** [comment]
"Enhance" is not a sufficient description of a change, and there appear to be multiple unrelated changes here: from quoting ensure handling of whitespace in paths, to cleaning up in case of errors, and reverting back to single process execution.

**Comment by pvalena** [comment]
Ack, let me get to that.

**Comment by pvalena** [comment]
You were right, I forgot to set multiple CPUs, and I also thought the disk would be the limitting factor. I've pushed some hardening changes at least - in several commits.

**Comment by ffesti** [comment]
Merged with slightly adjusted commit messages. Thanks for the patches and the additional work to get them in shape!

**Pull request closed without merging**
