### PR TITLE
Add LMDB backend for RPMDB to RPM (from @n3npq in #281)

### LINKED ISSUE #128: RFE: Offer LMDB as an alternative engine to BDB for rpmdb
I think most of us are keenly aware that Berkeley DB 5.x is dead. While Oracle has Berkeley DB 6.x, it is licensed AGPLv3, which seems to make some people rather skittish.

As a potential alternative, why not use [LMDB](https://symas.com/products/lightning-memory-mapped-database/)? Projects like OpenLDAP, CFEngine, Postfix, etc. have moved to LMDB or use it by default from BDB after BDB 6 arrived.

LMDB is available in Fedora, Mageia, and openSUSE already, so the dependency would already be available for us to use. It should also be easy to support having internal LMDB like OpenSUSE does now for BDB (the [LMDB sources](https://github.com/LMDB/lmdb) look like they're built in a rather simple manner, so embedding it shouldn't be terrible).

According to [the LMDB web page on projects using LMDB](https://symas.com/products/lightning-memory-mapped-database/involvement-in-other-projects/):

> Note, because it’s so easy to modify BerkeleyDB-based projects to use LMDB instead, the list of BerkeleyDB-based adaptations is growing quickly.

I'm not sure how true it is, but it seems to bear out with the number of previously BDB users now being LMDB users.

LMDB is licensed under the OpenLDAP license, which is a BSD-style license, so people who freaked out over BDB 6 shouldn't be freaking out over LMDB.

### LINKED ISSUE #281: Adding an LMDB backend to RPM
There have been years of vitriol about Berkeley DB and numerous suggested database replacements for RPM.

LMDB is perhaps the best choice because LMDB is most similar to Berkeley DB in API and design.

Attached is a patch to add an LMDB backend to RPM.

I will supply an updated lmdb.c implementation as certain plateau's are achieved.

The first plateau is the ability to iterate through all packages retrieving headers: DONE.

[rpm+lmdb-20170726.patch.gz](https://github.com/rpm-software-management/rpm/files/1176900/rpm.lmdb-20170726.patch.gz)

[lmdb.c-20170726.gz](https://github.com/rpm-software-management/rpm/files/1176907/lmdb.c-20170726.gz)

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This PR implements an LMDB-based rpmdb for RPM.

Closes #281 
Fixes #128

### CODE REVIEW

**Comment by n3npq** [comment]
The last patch to RPM_CHECK_LIB is appropriate for "opt-out" builds (i.e. --without-lmdb).

Leave "no" if willing to explicitly "opt-in" by passing --with-lmdb to configure.

For a serious test in CI, arrange for the macro %_db_backend lmdb to be set by default. Almost certainly you will also find that the lock.mdb file will need 0666 permissions when creating/using a database as non-root. The existing implementation will propagate that permission through --rebuilddb if set once when a database is created.

**Comment by robert-scheck** [comment]
Is it intended, that it's called `/data.mdb` rather `/Packages.mdb`?

**Comment by n3npq** [comment]
BDB and LMDB have always had the ability to have mutable databases (actually tables) in a single file. So actually there is a "Packages" (sub-)database/table in data.mdb.

Since 2 of 3 backend now have sub-databases in a single file, its likely time to do the same with BDB. I've never bothered to do that because people are used to using "ls -al" to see the relative size of files: with sub-databases you need to run db_stat or mob_stat to see what is using space.

**Comment by n3npq** [comment]
Here are lib/rpmdb.c and lib/backend/dbi.c replacements.

IIRC, rpmdb.c should now be unchanged. dbi.c needed some more anal retentive sanity checks.

[rpmdb.c.gz](https://github.com/rpm-software-management/rpm/files/1185904/rpmdb.c.gz)

[dbi.c.gz](https://github.com/rpm-software-management/rpm/files/1185905/dbi.c.gz)

**Comment by ignatenkobrain** [comment]
@n3npq why don't you send Pull Requests on your own. finding this attachments and converting them to real commits is painful and doesn't lead anywhere...

**Comment by n3npq** [comment]
See also comments at issue #281 about removing MDB_FIXEDMAP. Just delete the line that looks like
`eflags |= MDB_FIXEDMAP`

**Comment by n3npq** [comment]
At some point, "chmod 0666 lock.mdb" needs to be automated. ATM its unclear where that chmod should be planted likely in rpmdb.c, but perhaps as silent hack in lib/backend/lmdb.c). Dunno yet ...

**Comment by Conan-Kudo** [comment]
@n3npq @hyc @ignatenkobrain This should be fully rebased now.

**Comment by n3npq** [comment]
@ignatenkobrain : I don't send PR's because I don't have the time/energy/resources to wait months for review, updating the PR with zero feedback other than "Why don't you send PR's?". That's why.

**Comment by n3npq** [comment]
@Conan-Kudo : if using RPM_CHECK_LIB w internal, its a bit trickier than just adding a checkout.
So you likely want to remove "internal" as the 1st thing to try in "[yes,internal:external:none]"

FYI, removing "none" as in (yes,external) will fail to configure if not found (i.e. mandatory)

And in all cases you can add --with-lmdb=internal, or --without-lmedb, or --with-lmdb=no etc etc etc.

IRPM_CHECK_LIB is mostly intuitive once you get the hang of what is what

**Comment by mlschroe** [comment]
Please remove the part that patches ndb/glue.c from this commit.

**Comment by Conan-Kudo** [comment]
@mlschroe Fixed.

**Comment by pmatilai** [comment]
@n3npq : well this is a pleasant surprise. Thank you!

@Conan-Kudo : testing for Packages.mdb existence doesn't make LMDB create it. AFAICS the "data.mdb" name is hardwired in LMDB unless MDB_NOSUBDIR is used, and using that would introduce other unnecessary complications. I can fix that when committing.

Other than that, there seems to be some code duplication from db3.c that could be eliminated with a bit of refactoring and other more or less minor cleanups, but those can be dealt with later on as time permits.

**Comment by pmatilai** [comment]
Merged manually as of commit ed9de1992f5e1c23e8d8dbd61325a1e0070f2c72

Again, thank you @n3npq for the backend and @Conan-Kudo for the final tweaks!

**Comment by Conan-Kudo** [comment]
@pmatilai Thank you for reviewing it!

**Comment by n3npq** [comment]
Code duplication (and refactoring) are the least of the problems with the current RPM backend.

There is no concept of a "transaction" or "durability" in the current RPM backend.

And the existing INIT_CDB Berkeley DB model implemented has been tortured beyond belief or reason.

Anything that LMDB implements can easily be implemented with Berkeley DB (if used/implemented correctly). LMDB is mostly a pleasant simplification of a rather complex API.

**Comment by n3npq** [comment]
FWIW, "data.mdb" can be renamed to "Packages.mdb" in LMDB
 by adding a flag and passing the file path, not the directory path, when opening.

Not worth the effort (and adds confusion: "Packages" is the name of a database/table within "data.mdb" not the name of the file).

Note that Berkeley DB also permits sub-databases within a file. This was never implemented in RPM+BDB because using "ls -l" was deemed KISSier than requiring the use of db-utils.

*shrug*

**Pull request closed without merging**
