### PR TITLE
Generate requires for "pure" ELF DSO's regardless of executable bit

### PR DESCRIPTION
**Pull request by pmatilai**
ELF ET_DYN files can be shared libraries, executable files or both.
Requiring shared libraries that cannot actually be executed (or segfault
when you do so) is dumb, but rpm has traditionally required executable
bit to be set for requires to be generated.

Change the definition of "executable" to mean files that actually *can*
be executed, ie those with PT_INTERP, and only require executable bit
to be set for requires-dependencies generation on those. In other words,
pure shared libraries will have requires generated regardless of their
permission, but executable files can disable that by disabling the on-disk
executable bit.

### CODE REVIEW

**Comment by pmatilai** [comment]
This is RFC only as it's not clear we actually want this particular behavior, there might be better ways to achieve the goal of not having a system full of non-executable files with executable bit set.

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
I think this makes sense as an independent fix, because that makes our ability to generate dependencies more reliable.

**Comment by pmatilai** [comment]
Actually this needs dropping the "exeonly" flag from elf.attr too - will update...

**Comment by pmatilai** [comment]
Update includes:
- testcases added
- a bug in the original version where the (GNU)HASH stuff depended on executability still
- exeonly removed from elf.attr
- rebased

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
