### PR TITLE
fapolicyd: Make write() nonblocking

### PR DESCRIPTION
**Pull request by radosroka**
- switch to read only and non blocking mode for pipe
- add 1 minute loop to wait for pipe to reappear

Signed-off-by: Radovan Sroka <rsroka@redhat.com>

### CODE REVIEW

**Comment by pmatilai** [comment]
What's missing from the commit message is the all-important *why* part. Does this fix a bug (what happens etc) or what?

**Comment by dmnks** [comment]
FWIW, it seems like this is the respective BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2110787

**Review by pmatilai — CHANGES_REQUESTED** [review]
See my earlier comment, the actual reason for this change needs to be documented, not just what it does (we can see *that* from the patch itself)

**Comment by radosroka** [comment]
> What's missing from the commit message is the all-important _why_ part. Does this fix a bug (what happens etc) or what?

Sometimes during the system update/upgrade fapolicyd get restarted e.g. when systemd gets updated. That can lead to the situation where fapolicyd pipe has been removed and created again. In such cases rpm-plugin-fapolicyd gets stuck on write() to the pipe which does not exist anymore. After switching to non blocking file descriptor we can try to reopen the pipe if there is an error from write(). Assuming that a new pipe should appear when fapolicyd daemon starts again. If not then after 1 minute of waiting we expect fapolicyd daemon to be not active and we let the transaction continue.

**Comment by radosroka** [comment]
@pmatilai is it OK?

**Comment by pmatilai** [comment]
The message is okay now, thanks. Just wondering about it otherwise, while a minute is a whole lot shorter than eternity, stalling for a minute with no progress indication (AFAICS) in the middle of transaction can easily lead people thinking the thing just hung up and kill -9 (or reboot, or something).

**Comment by radosroka** [comment]
> The message is okay now, thanks. Just wondering about it otherwise, while a minute is a whole lot shorter than eternity, stalling for a minute with no progress indication (AFAICS) in the middle of transaction can easily lead people thinking the thing just hung up and kill -9 (or reboot, or something).

Would be 30 sec sufficient? Or you would like to print anything?

**Comment by pmatilai** [comment]
It's hard to say what the right time is. I'd add an RPMLOG_WARNING message  on losing connection to fapolicyd, stating how long it'll try to reconnect. People don't mind waiting so much if they know how long it'll take and what's going on. And then add another message if it gives up.

**Comment by radosroka** [comment]
> It's hard to say what the right time is. I'd add an RPMLOG_WARNING message on losing connection to fapolicyd, stating how long it'll try to reconnect. People don't mind waiting so much if they know how long it'll take and what's going on. And then add another message if it gives up.

I added warning messages as you suggested. I have not changed the 60s timeout which I consider to be adequate.

**Comment by dmnks** [comment]
Looks good to me now, I believe we can merge now, what do you say, Panu?

**Comment by pmatilai** [comment]
Yup, seems fine now. We've no means of testing this stuff so we can only assume the patch author has done so. Thanks for the patch!

**Comment by pmatilai** [comment]
Oh, and our CI seems rather terminally ill. Using the big red override button...

**Review by pmatilai — APPROVED** [review]

**Pull request merged**
