### PR TITLE
Move internal OpenPGP parser into a subdirectory

### PR DESCRIPTION
**Pull request by pmatilai**
This will let us split it out of the main rpm repository in the next steps.

Ie, first we declared it's trash, and now we're swiping it under the carpet.

### CODE REVIEW

**Comment by pmatilai** [comment]
To elaborate, the idea here is to split the new rpmpgp subdirectory into a separate repository that can be pulled into the build for the "internal pgp" support, but to eliminate it from the rpm repo and release tarballs. This resolves #2414 as far as I'm concerned.

@mlschroe , you indicated interest in maintaining the parser in #2414 - do you still think that way, and does this split look like you could work with? @nwalfield - just fyi.

**Comment by nwalfield** [comment]
If we add new functions to the API, as suggested recently [in this issue](https://github.com/rpm-software-management/rpm/issues/2689), then the internal implementation will need to be updated. This will require a versioning scheme for the API, I think, which would complicate maintenance. Alternatively, we say we don't support the internal API at all. What do you think?

**Comment by pmatilai** [comment]
Having more modules does indeed complicate things, but then we're already in a situation where we need to coordinate any API additions between rpm and rpm-sequoia. It just hasn't really come up yet because ATM we're just bumping the required rpm-sequoia version as we go, but at some point we'll probably need to allow for more freedom (for older versions and such).

I basically see this as another step on our way to drop support for the internal parser entirely, I have a hard time seeing the development on it "taking off" due to the split. And if I'm proven wrong on that, then I guess it shouldn't have trouble keeping up with the new APIs either.

**Comment by pmatilai** [comment]
Tweaked a little bit to make the legacy status more prominent in the naming.
Just another small step towards sawing this unwanted limb off :smile:

**Pull request merged**
