### PR TITLE
Invoke python-macro-helper with -Es python args

### PR DESCRIPTION
**Pull request by scop**
To limit environment and user home dir influence.

### CODE REVIEW

**Comment by scop** [comment]
> I don't think that passing -E is good

Could you elaborate on that a bit, especially when you think -s /is/
good? Without -s, code from user site packages is loaded, potentially
interfering with the commands. Without -E, PYTHONPATH from environment
can be used to do exactly the same.

(If python3 could be assumed, I would have used -I here. Which BTW is
what I did in https://bugzilla.redhat.com/show_bug.cgi?id=1506355)

**Comment by pmatilai** [comment]
@ignatenkobrain see above, why not -E? That looks to me too like a fairly obvious thing to use here.

**Comment by ignatenkobrain** [comment]
@pmatilai I had concern about this just because Python maintainers asked me to use only `-s` for DNF..

> ... I suggest to add -s flag to the shebang until platform-python thing is resolved. This will prevent troubles caused by dnf being affected by Python packages installed by "sudo pip" command and packages in per user area. PYTHONPATH will work for user plugins. Can I ask you to add -s flag to the shebang in F27 and rawhide? ...

I don't have anything really against -E

**Comment by pmatilai** [comment]
Okay so related to the platform-python weirdness. That's a Fedora invention and it's up to Fedora to patch around it if needed.

**Pull request merged**
