### PR TITLE
Fix compatible-release, versions with dot-star, semantically versioned deps, and python version

### PR DESCRIPTION
**Pull request by gordonmessmer**
This branch was intended to address issue #881 but I also handled #612 and some other fixes.  Please let me know if you'd prefer these commits in individual PRs.

### CODE REVIEW

**Comment by hroncok** [comment]
cc @encukou

**Comment by Conan-Kudo** [comment]
@gordonmessmer Can you squash 9f69722fa70c6a06bb15a090abfc89dba2d63e68 into 3e630d6809fa07b01be512564c110493e2c73200 and 4fbf59037b2da5403ff3d565e5a4e57dafa5eca9 into 8a13e8a46d972b14a0cb88c800b7e3ce4813d75f?

**Comment by gordonmessmer** [comment]
Squashed.

**Comment by encukou** [comment]
Thanks for the mention. I have nothing better to contribute now. I'm planning to submit a well-tested, strictly standard-based implementation, but It looks like I'll not get to complete it this year.
(Please don't read that as an attack! This change is better than the status quo, and perfect is the enemy of good.)

**Comment by Conan-Kudo** [comment]
@gordonmessmer One last thing, could you prefix your commit messages with `scripts/pythondistdeps: ` so that we know what this is for?

**Comment by gordonmessmer** [comment]
@encukou I have no illusion that this change is pretty.  :)

I will say that if you have time to write an outline of what you'd like to see, I can put some time into further improvements.  For example, I don't know what you have in mind when you say "strictly standard-based implementation"

**Comment by gordonmessmer** [comment]
I've written a set of conversion functions that are a little cleaner than these patches for the purpose of discussion, if you have time to look at it:

https://github.com/gordonmessmer/convert-440

**Comment by encukou** [comment]
> https://github.com/gordonmessmer/convert-440/blob/master/convert-pep440.py

Wow! That looks great!
I started writing something similar, but ran into a lack of tests – I can't hold all the details in my head alone.

> For example, I don't know what you have in mind when you say "strictly standard-based implementation"

Well, figure out how to map PEP 440 & 508 to RPM versioning/requires properly :)
(For the record, the PEPs are relevant because they are linked from https://www.pypa.io/en/latest/specifications/ – on its own, an Active/Informational PEP is not an agreed-to standard.)

For example, we're currently ignoring pre-releases. That's probably OK, but it should be a conscious/documented decision.

**Comment by gordonmessmer** [comment]
Thanks, @encukou 

If this PR looks good to you all, then let's merge and close it, and continue discussion in issues on the convert-440 project.  Miro has a couple open now.  If I get that code into a condition where we're happy with it, then I can add unit tests and then work on integrating it back into pythondistdeps.

**Comment by Conan-Kudo** [comment]
@pmatilai, @ffesti: can we get this merged?

**Comment by pmatilai** [comment]
> can we get this merged?

If you say so.

That said, the language specific dependency generators and brp-scripts would be the next targets for moving out of rpm to a better home, whatever that might be. I don't have anything like an actual plan for achieving that, just a vague idea.

**Comment by Conan-Kudo** [comment]
@pmatilai My main resistance to moving this out of rpm is that it makes it _very_ hard to get it to all the rpm distributions if it's not in the core. The introduction of the generator in rpm allowed it to spread from Mageia and Mandriva to Fedora, and now openSUSE.

**Comment by pmatilai** [comment]
I know, that's the general level problem that we need to sort out before we can proceed.

**Comment by hroncok** [comment]
`.*` is still broken with `!=`:


python-kubernetes:

python-10.0.1/requirements.txt
`websocket-client>=0.32.0,!=0.40.0,!=0.41.*,!=0.42.* `

`error: Illegal char '*' (0x2a) in: 0.42.*`


`.*` is still broken with `>=`:

python-fsleyes:

fsleyes-0.32.0/fsleyes.egg-info/requires.txt
`nibabel>=2.3.*`

`error: Illegal char '*' (0x2a) in: 2.3.*`


The code explicitly only work with `== ...*` but not other specs:

```python
elif spec[0] == '==' and spec[1].endswith('.*'):
```

**Pull request merged**
