### PR TITLE
Cleanups and improvements in tests/rpmpgppubkeyfingerprint.c

### PR DESCRIPTION
**Pull request by sshedi**

### CODE REVIEW

**Comment by sshedi** [comment]
@pmatilai thanks for all the inputs. I have tried addressing all of them.
Please let me know if I have missed anything.

@ffesti thanks you for reviewing my earlier PR.

**Comment by nwalfield** [comment]
I've taken a look at this MR, and it's basically churn.  Some of the changes are coding style, and some are opinionated, and some are weird, like having `#define LEN 102400 // 100 * 1024`.  If I have a vote, this is a nack from me.

**Comment by sshedi** [comment]
@nwalfield Thanks for reviewing.
> and some are weird, like having #define LEN 102400 // 100 * 1024
It would help me understand things better if you explain a bit on why it is weird.
My intent behind the change is, why calculate something on every run which can be used directly?

I'm completely okay if this doesn't get merged, people spent time to review my change and gave suggestions and I should respect that so I spent time on this and tried to do it right. It's upto the maintainers now, I have done my part.

**Comment by pmatilai** [comment]
Sorry but I agree with @nwalfield , this is just strange churn for churn's sake. Like advertising use of goto but then still using return for the cases that *could* use a central clean-up point. Even the changes that I could use because I suggested them are mixed with unrelated other changes, moving stuff around needlessly etc. Even the change to "rpm coding style" is anything but, the code is almost 100% that already.

A 118 line simple program that only ever executes as a part of the test-suite does not need much in the way of cleanup, really.

**Comment by sshedi** [comment]
No problem. Thanks for your time and inputs.

**Pull request closed without merging**
