### PR TITLE
Always open (and initialize) the entire database at once

### PR DESCRIPTION
**Pull request by pmatilai**
In some scenarios we previously only created some of the indexes only
lazy db init through query. Partially initialized databases don't make
sense and are only asking for trouble, in particular this was causing
issues with sqlite backend which is stricter about readonly-mode.

Except for the special case of reading a potentially damaged database
for rebuilding, always open all the indexes from openDatabase().

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Erk, oops, disregard that... I clicked the wrong thing...

**Comment by pmatilai** [comment]
Need to move on with this now...

**Comment by mlschroe** [comment]
Sorry, I haven't had time to have a closer look at this. Things are a bit chaotic here at SUSE with everything being locked down because of the corona virus.

But from my glancing over the changes everything looked fine.

**Comment by pmatilai** [comment]
Sure, no worries. Things are a bit chaotic everywhere...

**Pull request merged**
