### PR TITLE
First iteration of a 4.14.3 update release (rc1)

### PR DESCRIPTION
**Pull request by ffesti**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@ffesti one another thing which needs to be backported is definitely 15b296c324794d288750136b3b4f3350c3d0b8c7

**Comment by pmatilai** [comment]
Looking at the semaphoreci failure, there's a bunch of these:
> +++ /opt/rpm/tests/rpmtests.dir/at-groups/443/stderr	2020-02-18 07:51:48.219806927 +0000
> @@ -0,0 +1 @@
> +/opt/rpm/tests/rpmtests.dir/at-groups/443/test-source: line 48: python: command not found

Pulling commit d15ea79139304e14e6aaf6143af34c0405c41966 should minimally fix that.

**Comment by pmatilai** [comment]
Also as a reminder to us all, the final commit with version update is missing here, and along with that, rpm_version_info needs to be updated. There's at least one new API added so that needs to be reflected as well.

**Comment by Conan-Kudo** [comment]
@mlschroe Are there patches SUSE has been backporting for SLE 15 that should be included in here for 4.14.3?

**Comment by ffesti** [comment]
I wonder if it really is worth getting the Python test suite to pass on Python3. rpm-4.14 did only run the test suite on Python 2 and I don't really see the transition to Python3 as part of this update.
May be the easier way is to hard code the CI to use an older Fedora release which still includes Python 2 - as logn as this still lasts...

**Comment by pmatilai** [comment]
Oh, I thought /usr/bin/python is still Python 2 on Fedora 32 but that's not the case, the CI needs to be tweaked to use python2 explicitly. Getting Python 3 to pass would require pulling in the bytes -> strings change. Which would be a controversial thing to do...

**Comment by Conan-Kudo** [comment]
@pmatilai Well, you did it in Fedora and RHEL with RPM 4.14, so...

**Comment by pmatilai** [comment]
Yup. With RHEL we had no choice really, and in Fedora it was a canary for soon-to-land 4.15. With other users we don't know and can't control

In many ways the sanest option would be to pull those string changes to 4.14 too, and declare it a bug fix. But we'd need a community buy-in for such a change upstream.

**Comment by Conan-Kudo** [comment]
@pmatilai The reality is, we already dealt with it and "fixed" it because you forced the issue. At this point, "community buy-in" happened because you made us do it. What more do you want?

**Comment by pmatilai** [comment]
Okay, actually "distro buy-in" would the more appropriate expression. Community is upstreams, where it was largely dealt with. But distros who expect a stable branch to stay like it is are quite a different thing, stable branch updates are not supposed to do such things.

So explicit "please include the Python 3 string change" requests from distro people would go a long way.

**Comment by pmatilai** [comment]
We'll want to lock the Fedora version in CI to avoid the likes of the Python mess in case we ever need to do another 4.14.x release, but other than that I think this is good to go now. It's an RC afterall so there is still a chance to fix if something breaks.

**Comment by pmatilai** [comment]
> Use make check instead of make distcheck in CI

Eek, no to this! distcheck is a really, really powerful tool for ensuring the resulting tarball is good to go.

**Pull request merged**
