### PR TITLE
RPM 4.18.1 bugfix update

### PR DESCRIPTION
**Pull request by dmnks**
OK, time to make the first 4.18 maintenance update, please let me know if the commit selection works for you. The focus is, as always, on important bugfixes, regressions and security fixes.

Commits related to documentation or tests we usually pick unconditionally so those make up at least half of the whole commit log here.

Note that I deliberately stopped the selection process at commit 1f47b1cc0  (from master) to keep the amount of changes sane. That said, I still included a couple of specific commits made later, mostly to address regressions.

### CODE REVIEW

**Comment by pmatilai** [comment]
> I was also wondering if we shouldn't have done a soname bump before 4.18.0 due to the following commits which have changed or removed some public interfaces

Those interfaces are not considered public, even if the symbols may be visible in the DSOs. The rpm criteria for a public interface is whether something is present in our public headers or not.

**Comment by dmnks** [comment]
Makes sense, thanks!

**Comment by dmnks** [comment]
Not too late, really, it's actually just in time! Let's pick these `rpmsign` fixes too, then, they seem to be important enough for some folks and are regression fixes so typically a good choice for a maintenance update. Thanks for the note, @eaon!

**Comment by dmnks** [comment]
Should we also consider #2408?

**Comment by dmnks** [comment]
Oh, and I'll also drop b0c9b3d87 since that's not needed to fix the intended regression, as per #2344.

**Comment by dmnks** [comment]
OK, changes pushed, dropping the following ones:

b0c9b3d87 Calculate number of threads to use during build, not spec parse
d0867bcea Fix OpenMP enablement in librpmbuild (broken by cmake transition)
37ec18d86 Fix silent wait when missing input RPM package

The second one is a noop without the first one, the third one is related to the `rpm2archive` changes that I decided to drop in my previous comments.

**Comment by pmatilai** [comment]
If you want to trim your budget more:
- the check-buildroot cleanups, that script has been there for > 20 years without those changes...
- split testing population into a script
- drop historic remnants from test-suite PATH (unless something later depends on these two test-suite changes)

Not that I think those are harmful, just seem unnecessary. Other than that I think it looks good.

**Comment by dmnks** [comment]
> If you want to trim your budget more:
> 
>     * the check-buildroot cleanups, that script has been there for > 20 years without those changes...

Oh, truly. Let me drop that, too, then. One can never be overly conservative with updates :smile: 

>     * split testing population into a script
> 
>     * drop historic remnants from test-suite PATH (unless something later depends on these two test-suite changes)
> 
> 
> Not that I think those are harmful, just seem unnecessary. Other than that I think it looks good.

True, I think I included them originally just to avoid future cherry pick conflicts regarding the test suite, but all in all, it seems unnecessary, so let me try to drop those as well.

**Comment by dmnks** [comment]
Another update, this time removing the following:

8a74780c0 check-buildroot: harden $tmp creation
fb6ad2c74 check-buildroot script: use if-then-else
f2b4c647c check-buildroot: Redirect xargs stderr to $tmp
11458278a check-buildroot script: Double-Quote the variables
fd3ef9b09 check-buildroot script: use export to set LANG

e7e0b4df8 Split testing population into a shell-script
3a280308b Drop historic remnants from test-suite PATH
1e1e93ee5 Avoid buggy (if harmless) bin symlink in test when using /usr prefix
00c1bdfd7 Try to use pre-compiled libmagic, fall back to recreating if not found

**Review by pmatilai — APPROVED** [review]

**Comment by dmnks** [comment]
One last fixup: amend upstream commit e31fb5b75898bfa09180dba02475c6d01764d94f so that `Home-page` in the newly added `rpm.egg-info.in` is hardcoded (we don't define `@PACKAGE_URL@` so the field would've been empty).

**Comment by dmnks** [comment]
Oh, well... Commit e31fb5b75898bfa09180dba02475c6d01764d94f already was on the `rpm-4.18.x` branch :facepalm: So we need to make the above change a separate commit.

**Pull request merged**
