### PR TITLE
WIP: Add brp helper scripts derived from spec-helper

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This PR includes #122 and attempts to address the remaining feedback.

So far, the following changes have been made:

* pkgconfig manipulation was dropped. The script wasn't even included in #122, and it's not clear it was a desirable change, anyway.
* 'dont' was changed to 'disable', to be more consistent with other things in rpm
* all brp scripts are now marked as executable, so that they would actually run
* Small change in the comment in `brp-remove-rpath`

### CODE REVIEW

**Comment by proyvind** [comment]
disable_fix_foo are poor grammar, and not only 'disable' found to be consitent with was %_disable_source_fetch..

why changing "wuzz out"  to "quit" in comment? in order to not offend some unlikely person, or just plain political correctness (not really mutually exclusive)?

For pkgconfig, I made it more than evidently clear it being useful (and never dropped from #122).

It's the root cause for majority of all double slashes in paths with the result of different hacks added to debugedit without the actual ability to really workaround the issues for all scenarious..

The idea of that trimming away extra slashes in pkgconfig files having a high risk of causing breakage (despite of it's triviality), not even if it's clear that it's desirable is irrational.

Fixing the pkgconfig files and the actual root cause of most double slash issues with debugedit is hard to dispute as being desired over hacks and breakages with debugedit caused by not fixing the actual cause, which this script does..

I don't see the rationale for creating a new PR rather than just commenting on the existing one, nor much for the changes either.

Changing single comments in scripts fully authored by for no technical/practical reasons is what to be considered as poor etiquette..

**Comment by proyvind** [comment]
ah, you were right about the missing brp-fix-pkgconfig script though, I'll rather fix it in the original PR

**Comment by proyvind** [comment]
splitting the brp-check-elf-files script however, thx, I was planning on it ;)

**Comment by proyvind** [comment]
which I discovered that was me who had done.. :p 
my local branch on current workstation wasn't updated.. ;)

**Comment by Conan-Kudo** [comment]
@proyvind If you want to fix things, feel free to do so in your original PR. Also feel free to pull my changes in.

**Comment by Conan-Kudo** [comment]
> why changing "wuzz out" to "quit" in comment? in order to not offend some unlikely person, or just plain political correctness (not really mutually exclusive)?

Not really for offensiveness. I didn't know what you meant by that. I edited for clarity.

**Comment by Conan-Kudo** [comment]
> The idea of that trimming away extra slashes in pkgconfig files having a high risk of causing breakage (despite of it's triviality), not even if it's clear that it's desirable is irrational.

This should be properly fixed in upstream pkgconfig files, though. Otherwise we're just masking the problem.

**Comment by proyvind** [comment]
I'd say "wuzz out" is clear enough, while also more suggestive ;)

for pkgconfig files, this isn't really just a pure upstream problem, the foo.pc file is usually generated from ie. flags passed to configure..

And wrt. masking problems, a lot of the brp scripts simply fixes stuff easy to detect and fix, while being too widespread not worth the efforts of spend much time on pushing fixes for each and every package which the scripts are meant to fix and free us of.. ;)

It's meant to decrease the maintenance burden, not the other way araound ;)

**Comment by Conan-Kudo** [comment]
Closing for now, as #122 seems to be active again...

**Pull request closed without merging**
