### PR TITLE
Minor cleanups towards detaching rpmpgp_legacy from rpm internals

### PR DESCRIPTION
**Pull request by pmatilai**

### CODE REVIEW

**Comment by pmatilai** [comment]
This is nowhere near sufficient to make rpmpgp_legacy buildable outside rpm but this much is easy so why not.

**Comment by nwalfield** [comment]
I reviewed the change and it looks reasonable to me.

**Comment by pmatilai** [comment]
Oh, I didn't tag you in because I figured this is just uninteresting paper-shuffling type cleanup :sweat_smile:

**Comment by nwalfield** [comment]
No worries.  I figured that after I looked at it, but then I had already looked at it :D

**Pull request merged**
