### PR TITLE
testing GHPRB

### PR DESCRIPTION
**Pull request by mluscon**

### CODE REVIEW

**Comment by mluscon** [comment]
Test this please

**Comment by mluscon** [comment]
Test this please again :)

**Comment by mluscon** [comment]
retest this

**Comment by mluscon** [comment]
retest this

**Comment by mluscon** [comment]
test this please

**Comment by mluscon** [comment]
test this please

**Comment by cgwalters** [comment]
Any chance you could set up Jenkins against e.g. your personal fork of the repo and test things there first?

**Comment by mluscon** [comment]
Unfortunately, I need to test access rights of bot to exactly this repo. I am sorry for bothering you.

**Comment by ignatenkobrain** [comment]
@lkardos @ffesti could you close it?

**Pull request closed without merging**
