### PR TITLE
Run file verification and package signature checking in parallel threads

### PR DESCRIPTION
**Pull request by pmatilai**
While we're playing with parallelising things...

On my rusty old laptop, this tends to just slow things down unless
things are hot in cache, in which case it roughly halves the running time.

Might be worth more on SSD based setup, I'd be interested to hear results on such systems.
For now, this is just for giggles and benchmarking, not intended for merging.

Strictly speaking, this depends on PR #701 as we cannot fork while threading.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
If you could provide some script for testing this, I can do some benchmarks.

**Comment by pmatilai** [comment]
Dunno what there is to script. Try 'time rpm -Va' with and without, add "echo 1 > /proc/sys/vm/drop_caches" in between to see what happens with cold caches?

**Comment by pmatilai** [comment]
Hmm, couple of tests are failing: 
1) because errno isn't stored in the verify results, but that only affects the produced messages
2) ghost etc skipping isn't handled in the second loop

**Comment by ignatenkobrain** [comment]
With your PR (with/without dropping caches):

```
⋊> ~/P/u/rpm on master ⨯ time ./rpm -Va >/dev/null                                                                                                                          15:26:03
Command exited with non-zero status 1
297.33user 12.27system 1:03.35elapsed 488%CPU (0avgtext+0avgdata 46136maxresident)k
26104592inputs+128outputs (245major+17499minor)pagefaults 0swaps
⋊> ~/P/u/rpm on master ⨯ time ./rpm -Va >/dev/null                                                                                                                          15:27:09
Command exited with non-zero status 1
230.18user 6.50system 0:38.76elapsed 610%CPU (0avgtext+0avgdata 44048maxresident)k
0inputs+0outputs (0major+10576minor)pagefaults 0swaps
```

**Comment by ignatenkobrain** [comment]
And this is without your PR with dropping caches:

```
⋊> ~/P/u/rpm on master ⨯ time ./rpm -Va >/dev/null                                                                                                                          15:29:57
Command exited with non-zero status 1
53.21user 12.86system 1:51.69elapsed 59%CPU (0avgtext+0avgdata 42192maxresident)k
26088560inputs+128outputs (245major+16402minor)pagefaults 0swaps
```

**Comment by pmatilai** [comment]
Just to make sure, these are SSD numbers?

**Comment by ignatenkobrain** [comment]
Yes, one of NVMe devices. One of the fastest you can find in laptops.

**Comment by ignatenkobrain** [comment]
More specifically, `SAMSUNG MZVLB512HAJQ`

**Comment by pmatilai** [comment]
Added parallel signature checking with rpmkeys -K. For spinning disks, the results are (expectedly) quite similar: with cold cache its much slower, with hot cache much faster.

**Comment by pmatilai** [comment]
As for the parallel signature checking, rpmkeys -Kv output is (obviously) busted in parallel mode, fixing that would require more than one or two liner adjustments. So that part too is certainly just for tyre kicking and benchmarking for now.

**Comment by pmatilai** [comment]
Okay so this is *not* going in at this point no matter what, closing. I'll leave the branch around for the time being though in case people want to play around.

**Pull request closed without merging**
