### PR TITLE
Improve documentation for VCS tag

### PR DESCRIPTION
**Pull request by ffesti**
in reference manual and define a format

### CODE REVIEW

**Comment by pmatilai** [comment]
Works for me.

**Comment by mlschroe** [comment]
Sorry for chiming in so late, but is this really `<vcs>:<url>`? e.g. `git:git://foo.com/...`? Many other formats use `git+https://github.com` or similar.

**Comment by mlschroe** [comment]
(See the SPDX documentation for something similar)

**Comment by pmatilai** [comment]
Well, nothing looks or tries to enforce any particular format for this tag, so in reality it's just "whatever is people come up with".

**Comment by mlschroe** [comment]
Yes, this is a documentation issue.

**Pull request merged**
