### PR TITLE
RFC Building with PIC enabled is not supported in OS/2.

### PR DESCRIPTION
**Pull request by ydario**
Disable PIC flags in OS/2 build.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
The error in the CI is due to its dependency on #349.

**Comment by Conan-Kudo** [comment]
Erk, wrong PR for this.

**Comment by Conan-Kudo** [comment]
The CI failures in this PR are unrelated to this change.

**Comment by pmatilai** [comment]
The right thing to do is actually not have rpm mess with -fPIC and friends at all, these are up to distro/platform policies etc. Done in commit d7dfd0dc0c6ad7fc067a1d0e292a74e134b0720c so this PR is not needed at all. And by doing the right thing we actually end up reducing the need for those OS2-specific patches, and those kind of changes are always welcome.

**Pull request closed without merging**
