### PR TITLE
Accept --nocaps also for the package installation

### PR DESCRIPTION
**Pull request by lkundrak**
Makes it possible to work around trouble of installing packages that use
file capabilities in user namespaces.

It simply ignores the capabilities as opposed to setting a setuid bit.
This is a safer things to do, but possibly has a negative impact on some tools
(such as ping being usable only by the superuser).

https://bugzilla.redhat.com/show_bug.cgi?id=648654

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@lkundrak Could you please also add the required information to `doc/rpm.8`?

**Comment by pmatilai** [comment]
No objections on adding --nocaps, traditionally rpm has disablers for just about everything and this should've really been there from the start.

What I am wondering about is whether the capability business actually belongs into a plugin along with SELinux and the like, which would change the landscape somewhat.

**Comment by lkundrak** [comment]
> @lkundrak Could you please also add the required information to doc/rpm.8?

Added.

> What I am wondering about is whether the capability business actually belongs into a plugin along with SELinux and the like, which would change the landscape somewhat.

This is something I am not able to have an opinion about.

**Comment by pmatilai** [comment]
Merged, thanks for the patch!

**Pull request merged**
