### PR TITLE
update mkinstalldirs to latest version (2009)

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
There are no changes really in new version, but annoying when doing autoreconf -vfi locally and always I get changes in this file...

**Comment by n3npq** [comment]
You might just as easily drop mkinstalldirs. The original motivation for including mkinstalldirs was from last century: certain ancient SysV non-linux platforms lacked "mkdir -p". Carrying mkinstalldirs was the solution.

**Comment by ignatenkobrain** [comment]
@n3npq I think it was said recently in some other PR that it's still needed for some ancient platforms which we (are we?) support..

#205 it was

**Comment by n3npq** [comment]
There are 3 issues:
1) mkdir -p isn't portable and so mkinstalldirs is needed
2) mkinstalldirs is distributed in /usr/lib/rpm
3) mkinstalldirs is copied and tracked in git or other VCS

My comment was wrto issue #3: mkinstalldirs was originally added to RPM in order to assuage the bosses reluctance to use autoconf etc.

I suspect that /usr/lib/rpm/mkinstalldirs is seldom used, and there are zillions of copies for those platforms that might need: distributing everywhere to please a few oddball platforms (OS/2? Windoize? OS X?)

And the correct fix for racy mkdir breaking parallel builds (as described in the autoconf doc cited in pull #205) is to go fix GNU mkdir like install -d (if not already done long ago). 

*shrug* removing mkinstalldirs from git changes almost nothing and does fix your annoyance with autoreconf modifications.

**Comment by Conan-Kudo** [comment]
So today, the problem isn't that `mkdir -p` doesn't exist, but at least on my Mac (running macOS Sierra), it seems to fail the test by autoconf, so it's used in place of `mkdir -p`. I don't know if upstream BSD mkdir improved enough to pass the autoconf check, as I don't have a FreeBSD system set up to test yet.

**Comment by n3npq** [comment]
Again: my 1st suggestion was for a removal from git to avoid an annoying warning when the file (as always) is replaced by autoreconf.

I added historical context about why an otherwise generated file was added to CVS (at the time),
and have personally seen the annoyances that happen when otherwise generated boilerplate
ends up under source code control.

At the time I was also personally involved in maintaining RPM on HPUX and Irirx, on systems that were using modems for internet connectivity, and so I also added /usr/lib/rpm/mkinstalldirs to avoid the tedious task of fetching a copy of mkinstalldirs.

This was *NOT* a suggestion that
1) mkdir is portable so that mkinstalldirs can be removed everywhere.
2) mkinstalldirs should not be distributed in tarballs
3) there aren't portability problems between linux and other operating systems: both ways.

**Comment by n3npq** [comment]
Specific to OS X portability: there are no efforts to port RPM to OS X (or Mac OS) natively (i.e. using only utilities that come from the OS vendor) that I am aware of for ~15 years. All existing porting efforts involve Fink, MacPorts or Homebrew, and so "portability" includes duplicating existing system functionality:

> Use the PATH, Luke.

**Comment by Conan-Kudo** [comment]
@n3npq I've been working on it, fwiw.

**Comment by n3npq** [comment]
FWIW, I have *repeatedly* argued for native (i.e. --prefix=/usr, etc etc) installation on OS X to no avail.

I have also successfully ported and run RPM on OS X for many years.

Meanwhile I return to my original statement:
> ... there are no efforts to port RPM to OS X (or Mac OS) natively ...

by vote of the hoi polloi lemmings.

Meanwhile getting mkinstalldirs out of RPM git hurts nothing.

**Pull request merged**
