### PR TITLE
Come up with replace_optflags (#814).

### PR DESCRIPTION
**Pull request by marxin**
The macro function is intended for %{optflags} manipulation
(replacement, conditional addition).

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@marxin Why is this necessary?

**Comment by pmatilai** [comment]
I'm really reluctant to add one-trick-pony utility macros like this because over time they tend to become liabilities one way or the other, and have other issues.

Manipulating compiler flags is a very common need indeed and could use some help from rpm, but that need is not limited to %optflags, there are various other similar things as well and I certainly don't want separate macros for updating %build_cflags, %build_cxxflags, %build_ldflags and so on.

I'd be more inclined to consider a generic utility or macro primitive.

**Comment by marxin** [comment]
> I'm really reluctant to add one-trick-pony utility macros like this because over time they tend to become liabilities one way or the other, and have other issues.

Good.

> 
> Manipulating compiler flags is a very common need indeed and could use some help from rpm, but that need is not limited to %optflags, there are various other similar things as well and I certainly don't want separate macros for updating %build_cflags, %build_cxxflags, %build_ldflags and so on.

To be honest, I'm not much familiar with `m4` language and how `rpm` works. Can you please help me how should such macro look like? Should it take the variable name as a first argument?

> 
> I'd be more inclined to consider a generic utility or macro primitive that helps in these kind of tasks. Also, it's worth considering whether the flags be stored in a more manipulation friendly manner in the first place.

I'm open for a better-defined API. Can you help me with that as well?

**Comment by pmatilai** [comment]
Um, rpm macros have nothing to do with m4.
I don't have any concrete proposals at this time, just asking for a rethink and pointing to the general direction that I would find acceptable.

**Pull request closed without merging**
