### PR TITLE
revise ISANAME for loongarch

### PR DESCRIPTION
**Pull request by zhangwenlong8911**

### CODE REVIEW

**Comment by ffesti** [comment]
Please rebase onto current master.

The commit message needs an explanation on why the name change is needed and why the new name is more correct than the old one.

**Comment by zhangwenlong8911** [comment]
> Please rebase onto current master.
> 
> The commit message needs an explanation on why the name change is needed and why the new name is more correct than the old one.

loongarch is the architecture name, loongarch64 is only used to distinguish between 64-bit and 32-bit infrastructure

**Comment by pmatilai** [comment]
Yes, we can guess that much. As ffesti said, that explanation belongs to the *commit message*, chatter on GitHub is mostly irrelevant.

**Comment by ffesti** [comment]
Then there is the question if the change is really the right one. Even if the hardware architecture is actually named loongarch i guess the binaries are either 64 or 32 bit. If you can have both - either side by side or having all 32 or all 64 bit per installation/distribution - you need to distinguish them in packages.

**Comment by pmatilai** [comment]
@ffesti, this is about the ISA macro only, so this does seem the right thing to do. The difference is %_isa expanding to loongarch64-64 vs loongarch-64 (with this patch). And in particular if there actually is a 32-bit variant, loongarch64-32 makes no sense whatsoever.

**Pull request merged**
