### PR TITLE
RPM 4.15.1

### PR DESCRIPTION
**Pull request by pmatilai**
Preparation for 4.15.1 release, consisting of

- critical bugfixes here and there (arm, dynamic buildrequires rpmlib(), revert dbus shutdown)
- handful of various %{expr:...} related fixes
- ndb fixes (replacing PR #908 )
- add support for gcrypt crypto
- bunch of documentation updates
- misc other stuff

Did I miss anything critical? Note that %[] and ternary operator intentionally not backported here, they have related behaviour changes that don't seem appropriate in a stable branch.

### CODE REVIEW

**Comment by pmatilai** [comment]
Added a late fix for the Icon: crasher.

**Comment by pmatilai** [comment]
A few more leak fixes + document popt...

**Comment by pmatilai** [comment]
Unless new disasters or other surprises turn up, I'll release this on 11.11.

**Comment by Conan-Kudo** [comment]
@pmatilai The "new surprise" actually is probably #931... Apparently logical consequences escaped everybody for a while, who knew?

**Comment by pmatilai** [comment]
Nah, that's a new feature. Release stoppers would primarily be regressions introduced between 4.15.0 and 4.15.1, but if some critical new bug would be discovered over the weekend, that would be at least considered.

**Comment by Conan-Kudo** [comment]
Then I guess I got nothin'... 👍

**Comment by pmatilai** [comment]
Postponed by a week to 18.11. to give some time with the newly surfaced reproducible builds issues.

**Comment by ignatenkobrain** [comment]
@pmatilai looks good except 077f4003eec8eaaedd80fd709205ff326d4aad50 is missing.

**Comment by ignatenkobrain** [comment]
nvm, I see that it is already included in 4.15 branch.

**Comment by pmatilai** [comment]
Okay, that's it then. Thanks for the feedback.

**Pull request merged**
