### PR TITLE
Build fixes related to <bfd.h>

### PR DESCRIPTION
**Pull request by tpetazzoni**

### CODE REVIEW

**Comment by rpm-maint** [comment]
Hi rpm-maint,

On Thu, 2016-12-08 at 15:08 -0800, Thomas Petazzoni wrote:
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/rpm-software-management/rpm/pull/108

I am not sure what to make of this mail message, or how to properly
reply. It is somewhat inconvenient to not have the patch to review in
the message or attached but having to click-through and download it
separately. Assuming these emails are generated automatically could they
be changed to just include the patch.

>   * Detect bfd.h to enable/disable sepdebugcrcfix building
>   * tools/sepdebugcrcfix.c: fix build with recent binutils

I think the reliance on bfd.h was a mistake. The code was lifted from
bfd, but should be totally independent (it just calculates a CRC). The
attached fixes the type to be a normal size_t and include sys/stat.h
(which was included through bfd.h) to get the definitions of stat and
chmod.

Cheers,

Mark

**Comment by tpetazzoni** [comment]
What you've seen is a regular Github pull request. The patches themselves are visible at https://github.com/rpm-software-management/rpm/pull/108/commits/6f5bdadfb84dc980a0d84fff541314432ad9ac1f and https://github.com/rpm-software-management/rpm/pull/108/commits/f6a649f471d2533442a9e8bbd6422e3af1a9641d.

Indeed, if bfd.h is not needed, then it's even better. Could you apply and push your patch that fixes the bfd.h usage?

**Comment by rpm-maint** [comment]
On 12/09/2016 09:57 AM, Thomas Petazzoni wrote:
> What you've seen is a regular Github pull request. The patches
> themselves are visible at 6f5bdad
> <https://github.com/rpm-software-management/rpm/pull/108/commits/6f5bdadfb84dc980a0d84fff541314432ad9ac1f>
> and f6a649f
> <https://github.com/rpm-software-management/rpm/pull/108/commits/f6a649f471d2533442a9e8bbd6422e3af1a9641d>.
>
> Indeed, if bfd.h is not needed, then it's even better. Could you apply
> and push your patch that fixes the bfd.h usage?

Yeh, fewer dependencies is better, applied.

Thanks everyone,

	- Panu -

**Comment by rpm-maint** [comment]
On Thu, Dec 08, 2016 at 11:57:50PM -0800, DNF Bot wrote:
> Can one of the admins verify this patch?

Could you please include the patch you want to see verified in
your message?

Thanks,

Mark

**Pull request closed without merging**
