### PR TITLE
Xz support improvements

### PR DESCRIPTION
**Pull request by proyvind**
These commits enhances xz support, while also implementing multithreaded xz compression..

### CODE REVIEW

**Comment by ffesti** [comment]
Sorry for the late reply. I have been on vacation the last few weeks.

This looks pretty interesting. I am a bit concerned about compatibility with deltarpm, though. I'd rather like to see the settings be part of the %_source_payload and %_binary_payload as they are shipped in the package and could though be used by deltarpm to (hopefully) create the bit by bit identical package with them.

**Comment by proyvind** [comment]
Ie. something like 'w6T.xzdio', where 'T' would be the compression setting for enabling multithreaded compression?

If so, I guess that shouldn't be too hard to figure out. :)

**Comment by Conan-Kudo** [comment]
This branch has been obsoleted by #17. Please close this and review that one.

**Comment by ffesti** [comment]
Obsolete now.

**Pull request closed without merging**
