### PR TITLE
Revere Change %undefine macro to "func" style now that we can

### PR DESCRIPTION
**Pull request by JetXujing**
https://github.com/rpm-software-management/rpm/commit/aec8bdb53a3013eabf16368e17a65ab69c2136ee introduced function changes, which cause the output of the following command is changed.
     `rpm -D '%foo() %{expand:%define xxx 1} %{echo:%xxx}' -E +'%undefine xxx'-`
The result of the command is "+-" before https://github.com/rpm-software-management/rpm/commit/aec8bdb53a3013eabf16368e17a65ab69c2136ee, now is "+".

And according to https://github.com/rpm-software-management/rpm/commit/1d1f461f80138c44556a8d87433dd39884a7d44c, the return value is saved in "parsed".

### CODE REVIEW

**Comment by JetXujing** [comment]
In fact, "xxx-" is undefine instead of "xxx" after https://github.com/rpm-software-management/rpm/commit/aec8bdb53a3013eabf16368e17a65ab69c2136ee

**Comment by JetXujing** [comment]
@pmatilai please take a look

**Comment by pmatilai** [comment]
Some obscure corner-cases changing behavior is kinda expected in this kind of cleanup.
Is there some real-world usage which breaks because of this, something that can't be trivially fixed?

**Comment by JetXujing** [comment]
> Some obscure corner-cases changing behavior is kinda expected in this kind of cleanup. Is there some real-world usage which breaks because of this, something that can't be trivially fixed?

Through test cases, I found that the https://github.com/rpm-software-management/rpm/commit/aec8bdb53a3013eabf16368e17a65ab69c2136ee changed the function. As a result, the behavior of some commands is changed. Currently, there is no actual service problem. I haven't had any problems with the business until now.

In addition, through code analysis, I find that the character string of undefine is determined whether the character string belongs to "a-z" or "A-Z" or "0-9" or '_'

**Comment by JetXujing** [comment]
As there is no actual problem, it is closed temporarily.

**Comment by pmatilai** [comment]
I see no reason to revert this commit.

This seems to be how `--eval ."define x y".` has always behaved as well, so it's at least now consistent with that. The actual behavior doesn't make much sense either way, neither of these macros are intended to be used like that. There may be a bug in there, but this is not the fix.

**Pull request closed without merging**
