### PR TITLE
Add type hints to the Python interface

### PR DESCRIPTION
**Pull request by jamesjer**
I am working on a project that consumes the rpm python interface (https://pagure.io/depict for the curious).  I would like to typecheck my project, so I have created some stubs for that purpose.  Are you interested in having the rpm stubs?

Note that, with this commit applied, mypy has several complaints:
```
rpm/_rpm.pyi:583: error: Invalid signature "def [AnyStr in (builtins.str, builtins.bytes)] (rpm._rpm.hdr, Union[rpm._rpm.rpmTag, builtins.bytes]) -> Union[builtins.int, builtins.str*]" for "__getattr__"
rpm/_rpm.pyi:583: error: Invalid signature "def [AnyStr in (builtins.str, builtins.bytes)] (rpm._rpm.hdr, Union[rpm._rpm.rpmTag, builtins.bytes]) -> Union[builtins.int, builtins.bytes*]" for "__getattr__"
rpm/transaction.py:74: error: Signature of "addInstall" incompatible with supertype "ts"
rpm/transaction.py:87: error: Return type "None" of "addReinstall" incompatible with return type "bool" in supertype "ts"
rpm/transaction.py:93: error: Return type "None" of "addErase" incompatible with return type "bool" in supertype "ts"
rpm/transaction.py:121: error: Signature of "run" incompatible with supertype "ts"
rpm/transaction.py:137: error: Signature of "check" incompatible with supertype "ts"
rpm/transaction.py:179: error: Return type "None" of "hdrCheck" incompatible with return type "Tuple[rpmRC, Optional[str]]" in supertype "ts"
rpm/transaction.py:189: error: Return type "hdr" of "hdrFromFdno" incompatible with return type "Tuple[rpmRC, hdr]" in supertype "ts"
rpm/__init__.py:53: error: Cannot assign to a type
Found 10 errors in 3 files (checked 3 source files)
```

The first two errors arise from mypy having magic knowledge of what a `__getattr__` function's signature should look like.  I think the only way to eliminate those errors is to remove the `__getattr__` declarations and require any code that actually takes advantage of the non-str interface to work around mypy.

The remaining 8 errors can be fixed, but would require backwards-incompatible changes to rpm's python interface, mostly of the form "don't have a method in a subclass with the same name but a different signature as a function in a superclass".

I had to comment out the `file.class` attribute, as mypy objects to an attribute named "class".

Since `archive.hascontent` and `keyring.addKey` both return one of two integers (one zero and one nonzero), I wonder if it might not be better to make those functions return a boolean, although that would also be a backwards-incompatible change.

In `TransactionSet.check`, I made a change to check whether `p.altNEVR` is `None`.  I could not rule out that possibility by reading through the sources.

Let me know if this interests you.  I am willing to keep working on it until you are satisfied.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
We only support Python 3.6 and up, so I don't think this would be a problem for us.

**Comment by jamesjer** [comment]
Great.  Here is my thinking on the mypy errors noted above.

For the `hdr.__getattr__` case, I think those declarations should be replaced with a comment noting that an `rpmTag` or `AnyStr` value can be passed as an argument, and the corresponding `int` or `AnyStr` value will be the result.  I don't see any way of convincing mypy to like the existing declarations.  (See `TypeChecker.check_getattr_method` in the mypy distribution.)

For the `__init__.py` "Cannot assign to a type" case, I propose to add "# type: ignore" after `ts = TransactionSet` to tell mypy to ignore that line.  It is for backward compatibility, so I think ignoring it is okay.

Regarding `file.class`, my reading of https://docs.python.org/3/reference/lexical_analysis.html#keywords is that that attribute name really is illegal and should be changed.  Thoughts?

That leaves the methods in `TransactionSet` with the same name as but different signatures than methods in the superclass, `ts`.  This really is wrong.  If you have an object of type `ts` and call its `hdrFromFdno` method, the type of the returned value depends on whether your object is just a `ts` or is really a member of the subclass `TransactionSet`.  Fixing that properly means changing the method names in one class or the other, thereby breaking backwards compatibility.  Do any known consumers use the `ts` class directly?  If not, are you open to changing the `ts` method names?  If so, then another approach is to break the superclass-subclass relationship.  Make `TransactionSet` inherit from nothing, but contain a `ts` object to which it delegates.  If that isn't acceptable, then I can sprinkle more "# type: ignore" comments around to paper over the issue, but that will hamper type checking of consumers.

**Comment by ffesti** [comment]
While I like the overall idea of adding type hints to the binding I am not a big fan of the  content of python/rpm/_rpm.pyi. This basically duplicates the API implementation in the C based API and is very easy to get out of sync. Having this generated automatically during build time from the C based binding or even the C headers would be much preferred.
If this is not feasible we'd need at least some tests that make sure those declarations stay in sync with the binding.

**Comment by ffesti** [comment]
As said above this `python/rpm/_rpm.pyi` falling from blue sky is not acceptable. The preferred way would be if the type hints could be generated within the C bindings themselves. I have no idea (yet) if or how this is possible.

IMHO the changes to the native Python files can be merged after checking them for correctness (which I have not yet done).

**Comment by ffesti** [comment]
Guess this is just too much overhead  to be worth it in the end. Closing.

**Comment by DemiMarie** [comment]
> As said above this `python/rpm/_rpm.pyi` falling from blue sky is not acceptable. The preferred way would be if the type hints could be generated within the C bindings themselves. I have no idea (yet) if or how this is possible.

One approach would be to use ctypes or CFFI instead, which would allow the bindings to be implemented in Python instead of in C.

**Pull request closed without merging**
