### PR TITLE
configure.ac: use LIBDW always conditionally

### PR DESCRIPTION
**Pull request by ignatenkobrain**
References: https://bugzilla.redhat.com/show_bug.cgi?id=1365278
Reported-and-tested-by: Neal Gompa <ngompa13@gmail.com>
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@ffesti note, that I didn't tested it.

**Comment by Conan-Kudo** [comment]
@ffesti With this patch, I can build RPM on OS X again, so I'm happy with it.

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ffesti** [comment]
Pushed.

**Pull request closed without merging**
